### ISSUE TITLE
[Movemap] przechodzenie npc przez ściany/drzewa itp.

### ISSUE THREAD

**Issue by Mithras2801** [NoobSunwell/Sunwell-BugTracker#1]
**Opis** Mobki przechodzą przez ściany.

**Obecne działanie**: Moby przechodzą przez przeszkody.

**Oczekiwane działanie**: Mob powinien obiegać/przechodzić dookoła przeszkody.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Zaatakować npc
2. Schować się za ścianę
3. Zobaczyć jak przebiega przez nią

Link do NPC z filmika: http://wotlk.openwow.com/npc=299

Filmik: https://youtu.be/LjgwWD9cR5U

**Comment by Mithras2801** [comment]
Można dodać, że brak expa też

**Comment by Xanador** [comment]
Potwierdzam: http://imgur.com/a/xPbx0

**Comment by NoobSunwell** [comment]
Powinno działać po aktualizacji.
