### ISSUE TITLE
QUEST: Rite of Vision

### ISSUE THREAD

**Issue by Xanador** [NoobSunwell/Sunwell-BugTracker#10]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:Wszystko jest okej, po prostu wilk za szybko biega.

**Obecne działanie**:
Wszystko działa.

**Oczekiwane działanie**:
Po przywołaniu: http://wotlk.openwow.com/npc=2983 mob powinien poruszać się z naszą prędkością tzn 100%, tymczasem nie mamy możliwości go dogonić.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Wziąć quest: http://wotlk.openwow.com/quest=772
2. Przywołać http://wotlk.openwow.com/npc=2983   za pomocą   http://wotlk.openwow.com/item=4823
3. Próbować dogonić http://wotlk.openwow.com/npc=2983, niestety nie jest to możliwe, ponieważ wilczurek jest za szybki. 

( Fakt faktem... niby quest jest pokazany na mapie, że jest zrobiony i tak dalej, wystarczy się przebiec do wymaganego punktu, ale przyjemniej by było, gdybyśmy mogli biec obok zminiaturyzowanej szamańskiej formy ghost wolfa :) .)

**Comment by NoobSunwell** [comment]
Będzie poprawione po aktualizacji.
