### ISSUE TITLE
[QUEST] Free Your Mind

### ISSUE THREAD

**Issue by nexx94** [NoobSunwell/Sunwell-BugTracker#100]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:

**Obecne działanie**: Po zabiciu Vile, Lady Nightswood lub The Leaper resetują się lub znikają bez śladu, przez co niemożliwe jest użycie Sovereign Rod na ich ciałach i wykonanie questa

**Oczekiwane działanie**: Po zabiciu powinny zginąć i zostawić ciało

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Wziąć quest Free Your Mind
2. Próbować zabić moby
3. 

**Linki WoWHead/OpenWoW**:

1. http://wotlk.openwow.com/quest=12893
2. http://wotlk.openwow.com/npc=29769
3. http://wotlk.openwow.com/npc=29840
4. http://wotlk.openwow.com/npc=29770

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**: 
X: 8298 Y: 2658 Z:68p
https://imgur.com/a/THGRJ

**Comment by NoobSunwell** [comment]
Będzie naprawione po update.
