### ISSUE TITLE
[QUEST] The Amphitheater of Anguish: Yggdras!

### ISSUE THREAD

**Issue by nexx94** [NoobSunwell/Sunwell-BugTracker#101]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:

**Obecne działanie**: Da się ten quest otrzymać i ukończyć 2 razy, raz oddając go u Wodin the Troll Servant, raz u Gurgthock.

**Oczekiwane działanie**: Quest powinno dać się wykonać tylko raz, oddając go u w obu przypadkach Wodin the Troll Servant. Wersja questa którą dostajemy powinna być zależna od ukończenia areny w Nagrand.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Wziąć quest w Dalaran na arenę w Zul'Drak (The Champion's Call)
2. Polecieć do Zul'Drak i oddać quest
3. Można wziąć 2 questy na Yggdrasa i oba wykonać

**Linki WoWHead/OpenWoW**:

1. http://wotlk.openwow.com/quest=12932
2. http://wotlk.openwow.com/quest=12954 (tą wersje questa dostajemy gdy ukończymy arenę w nagrand, podejrzewam że to ten quest jest zbugowany)
3. http://wotlk.openwow.com/npc=30007
4. http://wotlk.openwow.com/npc=30009
5. http://wotlk.openwow.com/quest=12974

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
X: 5792 Y: -3018 Z:286
https://imgur.com/a/Drcdd

Dowody w komentarzach na wowhead:
http://www.wowhead.com/quest=12932/the-amphitheater-of-anguish-yggdras
http://www.wowhead.com/quest=12954/the-amphitheater-of-anguish-yggdras#comments

**Comment by NoobSunwell** [comment]
Będzie naprawione po update.
