### ISSUE TITLE
NPC w instancji Wailing Caverns ( MINOR BUG )

### ISSUE THREAD

**Issue by Xanador** [NoobSunwell/Sunwell-BugTracker#102]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:Mob atakuje bosa, chociaż nie powinien.

**Obecne działanie**: 
W instancji ( http://www.wowhead.com/zone=718/wailing-caverns )Mob ( http://wotlk.openwow.com/npc=3678 ) w encouterze budzi NPC ( http://wotlk.openwow.com/npc=3679 ), jednak gdy dostanie obrażenia bije bossa razem z party.

**Oczekiwane działanie**:  MOB ( http://wotlk.openwow.com/npc=3678 ) powinien przez cały encouter być immune na jakiekolwiek obrażenia, powinien zająć się tylko i wyłacznie budzeniem ( http://wotlk.openwow.com/npc=3679 )

**Co należy zrobić, aby odtworzyć ten błąd**:
1. Wejść do Wailing Caverns.
2. Ubić wszystkie bossy, bo móc zacząć walkę z ostatnim.
3. Uruchomić walkę z ostatnim bossem.
4. Gdy http://wotlk.openwow.com/npc=3678 dostanie obrażenia zaatakuje bossa.

**Linki WoWHead/OpenWoW**:
Wszystko opisane wyżej.

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by NoobSunwell** [comment]
Będzie naprawione po update.
