### ISSUE TITLE
[Thrallmar] Brak trenera latania.

### ISSUE THREAD

**Issue by Kougraa** [NoobSunwell/Sunwell-BugTracker#103]
**Opis**: W Thrallmar brak NPC. (Trener latania)

http://i.imgur.com/xU0FRj6.jpg

**Linki WoWHead/OpenWoW**:

1. http://www.wowhead.com/npc=35093/wind-rider-jahubo
2. http://wotlk.openwow.com/npc=35093
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
http://i.imgur.com/00BkRsB.jpg

**Comment by nexx94** [comment]
Added in patch 3.2.0
Serwer progresywny, prawdopodobnie usunięty celowo.

**Comment by NoobSunwell** [comment]
Dokładnie
