### ISSUE TITLE
[QUEST] Bodyguard for hire

### ISSUE THREAD

**Issue by turboszczur** [NoobSunwell/Sunwell-BugTracker#104]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Quest failed mimo że npce wszystkie przeżyły.

**Obecne działanie**: Quest jest eskortą a mimo to może zfailować nawet jeśli npce przeżyją.

**Oczekiwane działanie**: Quest nie powinien failować gdy npce są żywe. Na wowheadzie coś pisali w komentarzach że z rzadka ten bug występował też na globcu.

**Co należy zrobić, aby odtworzyć ten błąd**: 

1. Wziąść questa i eskortować
2. Poczekać na faila ?
3. 

**Linki WoWHead/OpenWoW**:

1. http://wotlk.openwow.com/quest=5821
2. http://www.wowhead.com/quest=5821/bodyguard-for-hire
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

http://imgur.com/a/1f1Jd

**Comment by NoobSunwell** [comment]
Będzie naprawione po update.
