### ISSUE TITLE
<quest> Challenge Overlord Mok'Morokk

### ISSUE THREAD

**Issue by valcy** [NoobSunwell/Sunwell-BugTracker#105]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:Brak jakiejkolwiek walki czy tez wymiany zdan.

**Obecne działanie**: Po wzieciu questa nic sie nie dzieje tylko zwyczajnie zalicza nam questa.

**Oczekiwane działanie**: https://www.youtube.com/watch?v=Vwt-MCb1TCw

**Co należy zrobić, aby odtworzyć ten błąd**:

1.Odpalic questa. 
2. 
3. 

**Linki WoWHead/OpenWoW**:

1. http://wotlk.openwow.com/quest=1173
2. http://wotlk.openwow.com/npc=4500
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
http://i.imgur.com/reyJm4n.jpg

**Comment by NoobSunwell** [comment]
Będzie naprawione po update.

**Comment by Xanador** [comment]
https://www.youtube.com/watch?v=uYSDPZ0McJk&feature=youtu.be

Error

**Comment by NoobSunwell** [comment]
Zapomniałem wgrać na serwer :) Będzie po update.
