### ISSUE TITLE
QUEST - Ruthless Cunning

### ISSUE THREAD

**Issue by microjp** [NoobSunwell/Sunwell-BugTracker#106]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:W queście chodzi o to aby zabijać moby i stawiać na nich sztandar

**Obecne działanie**: 
1.moby te są w grupkach po 2, po zabiciu jednego z nich mamy możliwośc postawienia sztandaru, lecz użycie quest itemu - szatandaru- zamienia pozostałego żywego moba w sztandar. 
2.Quest item powinien działać na wszystkich mobach w fortyfikacji, lecz działa tylko na "Kil'sorrow Deathsworn"

**Oczekiwane działanie**: po zabiciu moba powinniśmy móc postawić na nim sztandar używając quest itemu

**Co należy zrobić, aby odtworzyć ten błąd**:

1. użyć quest itemu po zabiciu jednego z Kil'sorrow Deathsworn w grupie
2. 
3. 

**Linki WoWHead/OpenWoW**:

1. http://www.wowhead.com/quest=9927/ruthless-cunning - QUEST 
2. http://www.wowhead.com/item=25552/warmaul-ogre-banner -QUEST ITEM
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
http://imgur.com/a/EztrN

**Comment by NoobSunwell** [comment]
Będzie poprawione po update.
