### ISSUE TITLE
[QUEST] Assault on the Sanctum

### ISSUE THREAD

**Issue by nexx94** [NoobSunwell/Sunwell-BugTracker#107]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: 

**Obecne działanie**: Można otrzymać quest Assault on the Sanctum od Krasus

**Oczekiwane działanie**: Powinno to być możliwe dopiero od patcha 3.3.5

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Wykonać quest On Ruby Wings (nie jestem pewien na 100%)
2. Wziąć od Krasus quest Assault on the Sanctum
3. 

**Linki WoWHead/OpenWoW**:

1. http://www.wowhead.com/quest=26013/assault-on-the-sanctum
2. http://www.wowhead.com/quest=12498/on-ruby-wings
3. http://wotlk.openwow.com/npc=27990

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
X:3529 Y:274 Z:343

**Comment by NoobSunwell** [comment]
Będzie naprawione po update.
