### ISSUE TITLE
Moby w Tanaris bez stealth

### ISSUE THREAD

**Issue by Lazybyku** [NoobSunwell/Sunwell-BugTracker#108]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Moby Wastewander Rogue, w krainie Tanaris, nie uzywaja swoich skili, tj. stealth.

**Obecne działanie**: Wastewander Rogue poruszaja sie bez stealth mode

**Oczekiwane działanie**: Powinny poruszać sie w stealth az do wykrycia ich, badz zaatakowania ich, badz bycia zaatakowanym przez nie.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Pojsc do krainy Tanaris
2. Odnalez moby Wastewander Rogue
3. 

**Linki WoWHead/OpenWoW**:

1. http://wotlk.openwow.com/npc=5615
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
 http://i.imgur.com/t2pMqoq.jpg

**Comment by NoobSunwell** [comment]
Będzie naprawione po update.
