### ISSUE TITLE
Moby w Tanaris bez skili

### ISSUE THREAD

**Issue by Lazybyku** [NoobSunwell/Sunwell-BugTracker#109]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Część mobow Southsea Freebooter  nie uzwaja skilla (nie strzelają)

**Obecne działanie**:  jak trzyma się moby na dystans nie robią nic

**Oczekiwane działanie**: PO odbiegnięciu na dystans powinny strzelać 
**Co należy zrobić, aby odtworzyć ten błąd**:

1. Pójść do krainy Tanaris
2. pullnac moba Southsea Freebooter 
3. odsunąć się od niego na dystans okolo 20yardow

**Linki WoWHead/OpenWoW**:

1. http://wotlk.openwow.com/npc=7856
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
http://i.imgur.com/ccD0jXL.jpg

**Comment by Lazybyku** [comment]
Ich umiejętności są w pierwszym odnośniku do openwow, wystarczy przescrollować niżej i zobaczyć "abilities"

**Comment by NoobSunwell** [comment]
Będzie naprawione po update.
