### ISSUE TITLE
[Mob Damage]Mountain Cougar/Mulgore

### ISSUE THREAD

**Issue by Ravenus** [NoobSunwell/Sunwell-BugTracker#11]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Zły damage mobów Mountain Cougar

**Obecne działanie**: Moby Mountain Cougar z Mulgore biją za 1 pkt obrażeń

**Oczekiwane działanie**: Powinny zadawać więcej obrażeń od 4 do 5 pkt

http://wotlk.openwow.com/npc=2961
**Co należy zrobić, aby odtworzyć ten błąd**: podnieść obrażenia minimalne i maksymalne moba

1. 
2. 
3.

**Comment by NoobSunwell** [comment]
Jakiś dowód, że ten NPC powinien zadawać takie obrażenia? openwow.com nie jest wiarygodnym źródłem na to, ponieważ damage mobów był nerfiony w jednym z patchy WotLK (3.3 bodajże). Moby do 5 levela mają od tego czasu niski DMG.

Jak będzie dowód - zostanie to odblokowane.
