### ISSUE TITLE
Mob nakłada fear na siebie.

### ISSUE THREAD

**Issue by Kougraa** [NoobSunwell/Sunwell-BugTracker#110]
**Obecne działanie**: Mob Bleeding Hollow Tormentor w Hellfire Peninsula, używając Feara, nakłada jego efekt na siebie, a nie tak jak powinno być - czyli na gracza.
https://www.youtube.com/watch?v=uk3eIsebsO8

**Oczekiwane działanie**: Feara powinien dostać gracz.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Pójść do Hellfire Peninsula.
2. Zaatakować Bleeding Hollow Tormentora..
3. 

**Linki WoWHead/OpenWoW**:

1. http://wotlk.openwow.com/npc=19424
2. http://www.wowhead.com/npc=19424/bleeding-hollow-tormentor
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
http://i.imgur.com/KOgCvx0.jpg

**Comment by NoobSunwell** [comment]
Będzie naprawione po update.
