### ISSUE TITLE
[QUEST] Grand theft palomino + into the realm of shadow

### ISSUE THREAD

**Issue by turboszczur** [NoobSunwell/Sunwell-BugTracker#111]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Visual bug przy Grand Theft Palomino, oraz niepokorny koń który zabija gracza.

**Obecne działanie**:
1. Koń którego dostarczamy w quescie Grand Theft Palomino został zabity przez NPC o nazwie  Salanar the Horseman w melee. Za drugim podejściem koń po prostu sobie stał ignorowany przez npce.
2. Podczas drugiego questa (Into the Realm of Shadows) npc o nazwie Acherus Deathcharger zabija gracza zadając ogromnie obrażenia nieadekwatne do jego poziomu uniemożliwijąc skończenie questa. 

**Oczekiwane działanie**:  
1. Koń dostarczony przez questa Grand Theft Palomino powinien zostać wessany przez czarny cyklon (visual).
2. Chabeta nie powinna zabijać gracza. Walka powinna odbyć się z jeźdźcem a szkape trza ukraść.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Zrobić dk u aliantów
2. Wziąść q i próbować zrobić.
3. 

**Linki WoWHead/OpenWoW**:

1. http://wotlk.openwow.com/quest=12680
2. http://wotlk.openwow.com/quest=12687
3. http://wotlk.openwow.com/npc=28653
4. http://wotlk.openwow.com/npc=28302
5. 
6.

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
http://imgur.com/a/u8bRH

Znalazłem filmik z globca jak ten quest powinien wyglądać. Pewnie lepiej wytłumaczy niż ja.
https://www.youtube.com/watch?v=cI5bWr9bdq0

**Comment by NoobSunwell** [comment]
https://www.youtube.com/watch?v=AFcO8U9wlfM - 1:17 - koń jak najbardziej powinien atakowac. DMG zmniejszony będzie po update. Co do wizuala - za chwilę.

**Comment by NoobSunwell** [comment]
Będzie naprawione po update.
