### ISSUE TITLE
[QUEST] Song of Fecundity

### ISSUE THREAD

**Issue by nexx94** [NoobSunwell/Sunwell-BugTracker#112]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:

**Obecne działanie**: Da się użyć quest itemu dużo razy nad jednym pagórkiem

**Oczekiwane działanie**: Powinna dać się użyć rogu tylko raz nad każdym pagórkiem

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Wziąć quest Song of Fecundity
2. Używać quest itemu stojąc dużo razy, raz za razem nad pagórkiem
3. 

**Linki WoWHead/OpenWoW**:

1. http://www.wowhead.com/quest=12737/song-of-fecundity
2. http://www.wowhead.com/item=39599/horn-of-fecundity
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
https://imgur.com/a/mNBXI

**Comment by NoobSunwell** [comment]
Brak ID itemu,

**Comment by nexx94** [comment]
Już jest

**Comment by NoobSunwell** [comment]
Będzie naprawione po update.
