### ISSUE TITLE
[NPC] Citizen of new avalon

### ISSUE THREAD

**Issue by turboszczur** [NoobSunwell/Sunwell-BugTracker#113]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Babka chyba nie wie że jest martwa.

**Obecne działanie**: NPC jest trupem ale wciążs stoi i udaje żywego.

**Oczekiwane działanie**: Powinien leżeć na glebie jak każdy przyzwoity trup

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Ciężko powiedzieć, natknąłem się na to podczas questa The Scarlet Onslaught Emerges.
Jak się zreplikuje to dodam screeny. 

**Linki WoWHead/OpenWoW**:

1. http://wotlk.openwow.com/npc=28559
2. http://wotlk.openwow.com/quest=12756
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

http://imgur.com/a/6s5kW

**Comment by NoobSunwell** [comment]
Będzie naprawione po update.

**Comment by turboszczur** [comment]
Ten npc to jakiś nieumarły, wciąż wraca zza grobu.

http://imgur.com/a/51gSc
