### ISSUE TITLE
ANIMACJA - Forge Camp: Anihilated

### ISSUE THREAD

**Issue by microjp** [NoobSunwell/Sunwell-BugTracker#114]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: po użyciu quest itemu, który dropi z elitki, na Fel Canon : Hate nie ma animacji

**Obecne działanie**: nie działająca animacja działa Fel canon

**Oczekiwane działanie**: po użyciu quest itemu działo powinno obrócić się w strone Forge Camp i wystrzelić laser.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Użyć quest itemu na działku
2. 
3. 

**Linki WoWHead/OpenWoW**:

1. http://www.wowhead.com/npc=19067/fel-cannon-hate - Działo
2. http://www.wowhead.com/quest=10011/forge-camp-annihilated - Quest
3. http://www.wowhead.com/item=25770/fel-cannon-activator - Quest item

 Dowód jak powinno działać:

https://www.youtube.com/watch?v=7uL_aPIWCJc

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
http://imgur.com/a/B7i9F

**Comment by NoobSunwell** [comment]
Będzie naprawione po update.
