### ISSUE TITLE
[QUEST] Fel Spirits

### ISSUE THREAD

**Issue by turboszczur** [NoobSunwell/Sunwell-BugTracker#116]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Kamień znika podczas robienia questa  (visual).

**Obecne działanie**: Kamień znika se ale wciąż możemy kontynuować questa.
**Oczekiwane działanie**: Kamień powinien zostać do końca swego cd.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Wziąść questa.
2. Próbować zrobić.
3. 

**Linki WoWHead/OpenWoW**:

1. http://wotlk.openwow.com/quest=10909
2. http://wotlk.openwow.com/spell=39183?object=185298
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

http://imgur.com/a/XwMim

**Comment by NoobSunwell** [comment]
Będzie naprawione po update.
