### ISSUE TITLE
Woda: Brak powietrza po wynurzeniu się.

### ISSUE THREAD

**Issue by Xanador** [NoobSunwell/Sunwell-BugTracker#117]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Po wynurzeniu się z pod wody, nasza postać nie " oddycha ".

**Obecne działanie**: 
Po wynurzeniu się z pod wody nasza postać jest jakby ciągle pod wodą. Nie oddycha ( nie napełnia się pasek " breath ". ( Chyba że wyskoczymy z wody, chociaż i to nie zawsze działa ).

**Oczekiwane działanie**: 
Po wyłonieniu się z wody nasza postać powinna natychmiast zacząć oddychać ( pasek " Breath " powinien się napełniać. )

**Co należy zrobić, aby odtworzyć ten błąd**:
1. Wejść gdziekolwiek do wody.
2. Zanurzyć się.
3. Wypłynąć.
4. Pasek powinien nadal ubywać.

**Linki WoWHead/OpenWoW**:
Eee... no nie ma xD?

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
http://imgur.com/a/8wlT8   ( GPS oraz zdjęcia )

**Comment by NoobSunwell** [comment]
https://vid.me/TSWB

U mnie ten błąd nie występuje.
