### ISSUE TITLE
[NPC] Lured Colossus

### ISSUE THREAD

**Issue by turboszczur** [NoobSunwell/Sunwell-BugTracker#118]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Gigtant się wkurzył i zabił quest givera.

**Obecne działanie**: Lured Colossus zabił npc luźno powiązanego z nim Thiah Redmane. Co jest niepokojące pojawił się ździebko daleko od swojego miejsca spawnu (quest earthbinder). Odbyło się to bez mojej żadnej interakcji.

**Oczekiwane działanie**: Myślę że kolos nie powinien szwendać się tak daleko i zabijać npców od innych questów.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Nie mam pojęcia.
2. 
3. 

**Linki WoWHead/OpenWoW**:

1. http://wotlk.openwow.com/npc=20599
2. http://wotlk.openwow.com/npc=16991#starts
3. http://wotlk.openwow.com/quest=10349#.

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

http://imgur.com/a/bhqKX

**Comment by turboszczur** [comment]
Mój błąd nie szwenda się daleko ale wciąż zabija quest giverów.

**Comment by NoobSunwell** [comment]
Jakbyś mógł wypisać mi ID questgiverów w tej okolicy, fix zająłby mi dosłownie minute :)

**Comment by turboszczur** [comment]
http://wotlk.openwow.com/npc=19293
http://wotlk.openwow.com/npc=16991#starts
http://wotlk.openwow.com/npc=16888
http://wotlk.openwow.com/npc=16885
http://wotlk.openwow.com/npc=19294

**Comment by NoobSunwell** [comment]
Cóż, to nie jest błąd, że je bije:

https://www.youtube.com/watch?v=qzqbBWC_IOY
https://www.youtube.com/watch?v=13RV76rNz7k

**Comment by turboszczur** [comment]
No tak ale on zabił innego npca (thiah redmane) który dawał innego questa, nie tego co go przywołał (Earthbinder Galandria Nightbreeze). Na screenach widać że eathbinder tam stoi na tej skale sobie zamiast z nim walczyć. Może to był jednorazowy przypadek.

**Comment by NoobSunwell** [comment]
Ktoś go musiał zostawić w takim stanie. Zabił pierwszego, wziął się za resztę.
