### ISSUE TITLE
[Skinning] Autoloot problem.

### ISSUE THREAD

**Issue by kovaq** [NoobSunwell/Sunwell-BugTracker#12]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:

**Obecne działanie**: Przy wiekszosci jak nie przy wszystkich probach zebrania lootu za pomoca shift+click'a (autoloot) pozostaje ikonka worka, blokujacy mozliwosc oskinowania moba. Przypadek spotkany zarowno na psach jak i na nietoperzach spotkanych w Tirisfal Glades. Wszystkie typy (zarowno Greater Duskbaty na 7lvlu jak i  Vampiric na 9).

**Oczekiwane działanie**: Kazdy mob powinien byc skinowalny, niezaleznie czy loot zbieram normalnie, czy autolootem.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Zabic moba.
2. Zebrac loot autolootem.
3. Probowac oskinowac moba.

**Comment by valcy** [comment]
a to nie bylo tak ze byles w party, a jezeli druga osoba ma loot w mobku to go nie zeskinujesz

**Comment by NoobSunwell** [comment]
Jak wspomniał @valcy - najprawdopodobniej byłeś w PT, bo ja tego buga nie mogę potwierdzić.
