### ISSUE TITLE
<quests> The green Hills of Stranglethorn (Chapters 1-4)

### ISSUE THREAD

**Issue by valcy** [NoobSunwell/Sunwell-BugTracker#120]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:Oddawanie chapterow jest powtarzalne.

**Obecne działanie**: Po oddaniu kartek do Chaptera mozna powtorzyc quest.
**Oczekiwane działanie**: Po oddaniu kartek questy nie powinny pojawic sie ponownie.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Zebrac i oddac kartki.
2. 
3. 

**Linki WoWHead/OpenWoW**:

1. http://imgur.com/a/7ddYS
2. http://wotlk.openwow.com/quest=339
3. http://wotlk.openwow.com/quest=340
4. http://wotlk.openwow.com/quest=341
5. http://wotlk.openwow.com/quest=342

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
http://imgur.com/a/7ddYS

**Comment by NoobSunwell** [comment]
Będzie naprawione po update.
