### ISSUE TITLE
[QUEST] Shizz Work

### ISSUE THREAD

**Issue by ThePuppetMaster** [NoobSunwell/Sunwell-BugTracker#121]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:
Generalnie quest działa, a błędy są kosmetyczne. Brakuje debuffa i quest npc się nie despawnuje.
Quest: 10629
Object: 184980
Debuff: 37695
NPC: 21847
Item: 30803

**Obecne działanie**:
Po użyciu objectu 184980 nie otrzymujemy debuffa 37695. Po zakończeniu questa ('oddaniu') NPC 21847 się nie despawnuje.

**Oczekiwane działanie**:
Po użyciu 184980 powinniśmy otrzymać debuff 37695, a po zakończeniu questa NPC 21847 powinien się zdespawnować.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Rozpocząć quest 10629
2. Wezwać NPC 21847 za pomocą itemu 30803 obok quest givera.
3. Wykonać quest objective wyciągając quest item z 'kupy' o id 184980 (ta, wiem...) NPC -ta 21847
4. Zakończyć/oddać questa.

**Linki WoWHead/OpenWoW**:

1. http://www.wowhead.com/quest=10629/shizz-work

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
Nie dotyczy chyba.

**Comment by NoobSunwell** [comment]
Będzie naprawione po update.
