### ISSUE TITLE
[QUEST] The Demoniac Scryer

### ISSUE THREAD

**Issue by ThePuppetMaster** [NoobSunwell/Sunwell-BugTracker#122]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:
Spawnujące się moby nie atakują quest NPC.
Quest: 10838
Mob: 22259, 22273
NPC: 22258

**Obecne działanie**:
Jak wyżej.

**Oczekiwane działanie**:
Spawnujące się moby powinny agrować się na quest NPC.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Użyć quest itemu, do przyzwania NPC 22258.
2. Stać w miejscu przy NPC i czekać nieruchomo.

**Linki WoWHead/OpenWoW**:

1. http://www.wowhead.com/npc=22259/hellfire-wardling
2. http://www.wowhead.com/quest=10838/the-demoniac-scryer
3. http://www.wowhead.com/npc=22273/fel-warden
4. http://www.wowhead.com/npc=22258/demoniac-scryer

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by NoobSunwell** [comment]
Będzie naprawione po update.
