### ISSUE TITLE
[Quest] As the Crow Flies (visual)

### ISSUE THREAD

**Issue by Kougraa** [NoobSunwell/Sunwell-BugTracker#124]
**Opis**:
https://youtu.be/KaIGsq5uSPo

**Obecne działanie**: Quest wykonalny. Jednak podczas lotu zwiadowczego ptakiem w quescie, pod koniec lotu - ptak znika, a my lecimy postacia w powietrzu. 

**Oczekiwane działanie**: W trakcie trwania lotu, gracz powinien być w formie ptaka.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Pójść do Zangarmarsh.
2. Wziąć quest od NPC.
3. Użyć quest itemu.

**Linki WoWHead/OpenWoW**:

1. http://www.wowhead.com/quest=9718/as-the-crow-flies
2. http://www.wowhead.com/npc=17841/ysiel-windsinger
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
http://i.imgur.com/41F6lic.jpg

**Comment by NoobSunwell** [comment]
Będzie naprawione po update.
