### ISSUE TITLE
MOB - Wyrm From Beyond

### ISSUE THREAD

**Issue by microjp** [NoobSunwell/Sunwell-BugTracker#126]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:

**Obecne działanie**: Mob jest nie widoczny

**Oczekiwane działanie**: 

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Mieć szczęście i znaleźć nie widocznego moba
2. 
3. 

**Linki WoWHead/OpenWoW**:

1. http://www.wowhead.com/npc=21796/wyrm-from-beyond
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
http://imgur.com/a/lfyk1

**Comment by NoobSunwell** [comment]
Będzie naprawione po update.
