### ISSUE TITLE
QUEST - Spirit Calling

### ISSUE THREAD

**Issue by microjp** [NoobSunwell/Sunwell-BugTracker#127]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:W queście chodzi o to aby postawić totem - Spirit Calling Totem- i w obrębie 15yd od niego zabijać smoki o nazwie Lesser Nether Drake. W tym okręgu powinny z nich dropić quest itemy - Lesser Nether Drake Spirit

**Obecne działanie**: Quest item dropi zawsze, niezależnie w jakiej odległości od Totemu

**Oczekiwane działanie**: Quest item powinien dropić tylko w odległości 15 yd od Totemu

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Postawić totem
2.  Zabić Lesser Nether Drake posiadając quest Spirit Calling w wiekszej odległości niż 15 yd
3. 

**Linki WoWHead/OpenWoW**:

1. https://www.youtube.com/watch?v=y_JmIzDxb1U - Youtube
2. http://www.wowhead.com/quest=10853/spirit-calling - Qest
3. http://www.wowhead.com/item=31663/spirit-calling-totems - Quest item przywołujący totem
4. http://www.wowhead.com/item=31656/lesser-nether-drake-spirit - Mob do Questa

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
http://imgur.com/a/ibf6G

**Comment by NoobSunwell** [comment]
Będzie naprawione po update.
