### ISSUE TITLE
[QUEST] Shoot 'Em Up

### ISSUE THREAD

**Issue by nexx94** [NoobSunwell/Sunwell-BugTracker#128]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:

**Obecne działanie**: Zabite smoki nie liczą się do progresu questa.

**Oczekiwane działanie**: Zabijanie smoków powinno umożliwić zrobienie questa.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Wziąć quest Shoot 'Em UP
2. Zabijać smoki harpunami
3. 

**Linki WoWHead/OpenWoW**:

1. http://www.wowhead.com/quest=13069/shoot-em-up#comments
2. http://wotlk.openwow.com/npc=30330
3. http://wotlk.openwow.com/npc=30337

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
https://imgur.com/a/jT3Z9

**Comment by NoobSunwell** [comment]
Będzie naprawione po update.

**Comment by nexx94** [comment]
Po fixie trochę lepiej ale nie do końca:
https://www.youtube.com/watch?v=RkbQOFdMkpI&feature=youtu.be
Nie zalicza wszystkich smoków, problem powtarza się.

**Comment by NoobSunwell** [comment]
Będzie naprawione po update.
