### ISSUE TITLE
Quest - Brak moba - Slay the Brood Mother

### ISSUE THREAD

**Issue by microjp** [NoobSunwell/Sunwell-BugTracker#129]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:W queście chodzi o zabicie smoka - Dreadwing

**Obecne działanie**: nie istnieje mob

**Oczekiwane działanie**: powinniśmy w odpowiednim miejscu znaleźć i zabić moba

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Udać się w odpowiednie miejsce i zobaczyć że mob nie istnieje
2. 
3. 

**Linki WoWHead/OpenWoW**:

1. http://www.wowhead.com/npc=21032/dreadwing - Mob
2. http://www.wowhead.com/quest=10845/slay-the-brood-mother - Quest
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
http://imgur.com/a/VfjBO

**Comment by NoobSunwell** [comment]
![image](https://cloud.githubusercontent.com/assets/22621466/19417878/09fe04b0-93b8-11e6-896b-86c2ea263b9a.png)

Musi być :)
