### ISSUE TITLE
[Mob] Lost Son of Arugal

### ISSUE THREAD

**Issue by kovaq** [NoobSunwell/Sunwell-BugTracker#13]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Spotkalem takie cudo miedzy The Skittering Dark a The Dead Fiend, Silverphine Forest. Jedzac na stealthie ser dalaranski. Mam 3 pkty w lepszego stealtha, mimo to rzucil sie na mnie jakbym wgl w nim nie byl, ale to akurat sprawa lvlu.

**Obecne działanie**: TO spotkalem na wolnosci: http://screenshooter.net/102844212/pdkplbk . Son of Arugal - mob buszujacy po sfk.
http://www.wowhead.com/npc=2529/son-of-arugal

**Oczekiwane działanie**: http://img.bubblesofmischief.com/2012/05/Lost-Son-of-Arugal.jpg Tak powinien prawidlowo wygladac ten mob. LOST Son of Arugal. Rare. Nie bijacy po 142, gdzie ja mam 240 hp. xd
http://www.wowhead.com/npc=47015/lost-son-of-arugal

Proponowalbym podmienie moba na wlasciwy typ.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Trzeba przedewszystkim go znalezc, powinien w gruncie rzeczy chodzic po calym Silverphine.
2. 
3.

**Comment by TomkiPL** [comment]
Added in patch 4.0.1 - Lost Son of Arugal.
http://www.wowhead.com/npc=47015/lost-son-of-arugal
