### ISSUE TITLE
[quest]  Diaphanous Wings

### ISSUE THREAD

**Issue by turboszczur** [NoobSunwell/Sunwell-BugTracker#130]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Q item ma prawdopodobnie zbyt niski drop rate.

**Obecne działanie**: Z npc Marshilight bleeder q item leci bardzo rzadko. Po zabiciu 6-7 Mashlight bleederów tylko 1 item poleciał.
**Oczekiwane działanie**: Z npc Marshilight bleeder powinien leciec q item z ratem okolo 80%. 

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Wziąść i zrobić questa.
2. 
3. 

**Linki WoWHead/OpenWoW**:

1. http://wotlk.openwow.com/npc=18133
2. http://wotlk.openwow.com/item=24372#objective-of
3. http://wotlk.openwow.com/npc=18133

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

http://imgur.com/a/bgyTk

**Comment by NoobSunwell** [comment]
http://www.wowhead.com/item=24372/diaphanous-wing#dropped-by

Ten QItem ma bardzo mały drop jak widać na wowhead. W bazie jest nieco wyższy i tak.
