### ISSUE TITLE
OBJECT - NPC - Quest - Felsworn Gas Mask

### ISSUE THREAD

**Issue by microjp** [NoobSunwell/Sunwell-BugTracker#131]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:W queście chodzi o to by "Porozmawiać" z objektem Legion Communicator

**Obecne działanie**: nie da sie kliknac na objekt

**Oczekiwane działanie**: powinnismy kliknac na objekt i oddac tam questa

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Wziąć quest i próbować go oddać
2. 
3. 

**Linki WoWHead/OpenWoW**:

1. http://www.wowhead.com/object=185165/legion-communicator - Objekt
2. http://www.wowhead.com/quest=10819/felsworn-gas-mask - quest
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
http://imgur.com/a/LeLNa

**Comment by NoobSunwell** [comment]
Nie masz założonej maski. U mnie po założeniu działa bez problemów.

![image](https://cloud.githubusercontent.com/assets/22621466/19418740/ad07cd3c-93ca-11e6-99a8-4eb4f9aa395f.png)

**Comment by NoobSunwell** [comment]
![image](https://cloud.githubusercontent.com/assets/22621466/19418742/bc19fc3c-93ca-11e6-8e96-9a9f97a5f59d.png)

**Comment by microjp** [comment]
Musiał sie duration time skonczyc, juz sprawdzam

**Comment by microjp** [comment]
Potwierdzone :D sory za klopot

**Comment by microjp** [comment]
a to że niema animacji ducha to zgłaszać osobno?
