### ISSUE TITLE
[quest] WANTED: Boss Grog'ak

### ISSUE THREAD

**Issue by turboszczur** [NoobSunwell/Sunwell-BugTracker#132]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:Mogę wziąść questa hordy jako aliant.

**Obecne działanie**: Mogę wziąść questa który jest od hordy a gram w ally.

**Oczekiwane działanie**: Quest powinien być dostępny tylko dla hordy.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Wziąść questa jako aluch.
2. 
3. 

**Linki WoWHead/OpenWoW**:

1. http://www.wowhead.com/quest=9820/wanted-boss-grogak
2. http://wotlk.openwow.com/quest=9820
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

http://imgur.com/a/PVWyz

**Comment by NoobSunwell** [comment]
Będzie naprawione po update.
