### ISSUE TITLE
[Quest] Hellscream's Vigil

### ISSUE THREAD

**Issue by kovaq** [NoobSunwell/Sunwell-BugTracker#133]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:Quest Hellscream's Vigil jest zdublowany. Oba mozna wziac, oba mozna oddac, oba daja 2 tysiace expierience points.
http://screenshooter.net/102844212/dijvdmy
http://screenshooter.net/102844212/pkdlvbv
GPS: http://screenshooter.net/102844212/jioegru
http://wotlk.openwow.com/quest=11585

ad:  na openwowie tez spotkalem sie z 2 sztukami tego zadania, co spowodowalo, ze zaczalem watpic, ze to przypadek. Mimo to zostaje przy fakcie, iz pojedynczy quest u givera w zupelnosci starczy.

**Obecne działanie**: Zdublowany q.

**Oczekiwane działanie**: Powinien byc 1?

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Podejsc do npc stojacego przy glownym wyjsciu z Warsong Hold.
2. 
3. 

**Linki WoWHead/OpenWoW**:

1. w/w
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
w/w

**Comment by NoobSunwell** [comment]
"The first one has Garrosh spitting in disgust at your evident fear. This one, in which he is kinder to you, happens if you have completed the Greatmother questline in Nagrand."

**Comment by kovaq** [comment]
Wciaz uwazam, ze powinien wystepowac jeden z nich, ale dziekuje za wyjasnienie genezy ich rozdwojenia.

**Comment by NoobSunwell** [comment]
Będzie naprawione po update.
