### ISSUE TITLE
{Quest] Taken by the Scrouge

### ISSUE THREAD

**Issue by kovaq** [NoobSunwell/Sunwell-BugTracker#134]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:Quest Taken by the Scrouge posiada powielone kokony w jednym pixelu. W zasadzie znalazlem tylko jedno takie miejsce, no ale zawsze.
http://screenshooter.net/102844212/pycixin
GPS: http://screenshooter.net/102844212/wogosio
http://wotlk.openwow.com/quest=11611

**Obecne działanie**: Powielony kokon

**Oczekiwane działanie**: Nie powinny sie nakladac, od biedy powinny stac obok, ale to tez by bylo niewlasciwe, najlepiej usunac zdublowany.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Podejsc w wybrane cordy.
2. Zbic jeden kokon, a pod nim pokaze sie drugi, nie ruszony.
3. 

**Linki WoWHead/OpenWoW**:

1. w/w
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
w/w

**Comment by NoobSunwell** [comment]
Będzie naprawione po update.
