### ISSUE TITLE
[Quest] Bury Those Cockroaches!

### ISSUE THREAD

**Issue by kovaq** [NoobSunwell/Sunwell-BugTracker#135]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Quest Bury Those Cockroaches! okazjonalnie nie zalicza wysadzenia dziury. Badalem zaleznosc, czy jezeli zostane przy bombie i wybuchne razem z nia to czy to bedzie powod niezaliczenia, lecz nie udalo mi sie dojsc co powoduje problem.
Byc moze krzywo klade bombe, naprawde nie wiem... w kazdym razie nastepne podlozenie bomby bylo sucesywne. (blizej srodka)
http://wotlk.openwow.com/quest=11608
Brak skrina / filmiku.
GPS: w poblizu http://screenshooter.net/102844212/wogosio

**Obecne działanie**: Wybuchajaca bomba nie zawsze zalicza zasypanie dziury.

**Oczekiwane działanie**: Jezeli mozemy postawic bombe to znaczy, ze jestesmy w zasiegu, co powinno byc tez zasiegiem do zaliczenia q.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Postawic bombe w dziurze do wysadzenia.
2. Czekac az wybuchnie, przy okazji delektujac sie pieknie dzialajacym skryptem na odliczanie na czacie ;p
3. 

**Linki WoWHead/OpenWoW**:

1. w/w
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
w/w

**Comment by NoobSunwell** [comment]
Niestety nie mam jak tego zweryfikować - jakbym miał jakiś filmik z tym, to pewnie bym wiedział w czym problem. Testowałem u siebie - za każdym razem zaliczyło bez problemu (nawet jak przeteleportowałem się na drugi koniec Borean).
