### ISSUE TITLE
[Language] Unikatowe jezyki gry dla danych ras.

### ISSUE THREAD

**Issue by kovaq** [NoobSunwell/Sunwell-BugTracker#137]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Krotko:
http://screenshooter.net/102844212/mokhtrr
Elfy nie mowia po elficku xd (brak jezyka Thallasian w menu wyboru, nie rozumiem rowniez Thallasianskiego gdy np Wretchedy z Eversong do mnie krzycza.)
http://wowwiki.wikia.com/wiki/Thalassian

**Obecne działanie**: Rasy nie maja swoich ojczystych jezykow, ally ma common, horda ma orcish i koniec.

**Oczekiwane działanie**: W moim przypadku powinienem miec do wyboru jeszcze jezyk elficki, czyli Thalassian.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Odkliknac ikonke na lewo od czatu (dymek)
2. Otworzyc zakladke language.
3. 

**Linki WoWHead/OpenWoW**:

1. w/w (wowwikia)
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
nie dotyczy.

**Comment by NoobSunwell** [comment]
Czy możesz założyć nową postać (ta sama rasa) i potwierdzić ten błąd?

![image](https://cloud.githubusercontent.com/assets/22621466/19421763/7d0f0030-9408-11e6-8635-a16c32c6d6f7.png)

**Comment by NoobSunwell** [comment]
Brak danych - aby mi się w oczy rzucało.

**Comment by kovaq** [comment]
http://screenshooter.net/102844212/gclphqb
Potwierdzam.

**Comment by nexx94** [comment]
https://imgur.com/a/ZHeLV
Również potwierdzam.

**Comment by NoobSunwell** [comment]
A jakbyście dla potwierdzenia zrobili inną klasę niż hunter? Bo co do niej mam małe podejrzenia.

**Comment by nexx94** [comment]
https://imgur.com/a/viqA5
Mag również nie zna języka.

**Comment by Ben1o** [comment]
Druid też ma tylko i wyłącznie common

**Comment by kovaq** [comment]
Rogala,Hunta i Maga juz mamy, a wiec:
http://screenshooter.net/102844212/gntjtid Palek.
http://screenshooter.net/102844212/kegafcw Prej.
http://screenshooter.net/102844212/fppefqp Lock.
http://screenshooter.net/102844212/pqjoiqj DK.
Zadna klasa krwawych elfow nie mowi po elficku.

**Comment by NoobSunwell** [comment]
Ok, mam przyczynę. Xinef i Pussy zostawili smaczek, że niektóre rasy uczą się złych języków (ale core do tego nie dopuszcza). Przez co blood elfy były uczone taureńskiego, nocne elfy - krwio-elfickiego i kilka innych przypadków.

Będzie naprawione po update.
