### ISSUE TITLE
[Quest] Plains of Nasam.

### ISSUE THREAD

**Issue by kovaq** [NoobSunwell/Sunwell-BugTracker#138]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:  Quest The Plains of Nasam dziala satysfakcjonujaco dobrze. Jedyne co tu nie dziala to zaliczanie rannych zolnierzy. Mianowicie robi to po 2 sztuki.
http://wotlk.openwow.com/quest=11652
http://screenshooter.net/102844212/vvthinf
http://screenshooter.net/102844212/tvvttbb .gps (maszyne bierze sie z plazy)

**Obecne działanie**: Zebranie rannego shamana powoduje dodanie 2 pktow progressu q, zamiast 1.

**Oczekiwane działanie**: 1 shaman = 1 punkt do progressu q.

**Co należy zrobić, aby odtworzyć ten błąd**:

1.  Po wzieciu q nalezy wsiasc do demolishera stojacego na plazy
2. Jadac demo w gore na pola rozwalamy sily scrouge, by przebic sie w koncu do rannych jednostek hordy
3. skill nr 5 powoduje zebranie rannego sojusznika

**Linki WoWHead/OpenWoW**:

1. w/w
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
w/w

**Comment by NoobSunwell** [comment]
Będzie naprawione po update.
