### ISSUE TITLE
[Quest] Foolish Endeavors.

### ISSUE THREAD

**Issue by kovaq** [NoobSunwell/Sunwell-BugTracker#139]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Quest Foolish Endeavors rowniez dziala dobrze, ale odkrylem tu maly smaczek. Mianowicie nekromanta ktorego mamy zabic co jakis czas bije aoe. Gdy moje zycie zeszlo do momentu gdzie nastepne aoe by mnie zabilo, postanowilem uciec sie do malego tricku vanish+feed. zjadlem i wracajac do walki walczacy duet poprostu znikl. na ten moment 3 razy. probowalem tez odejsc tak by saurfang zrobil za mnie robote przy podtrzymywaniu combatu thrownem. znikli. Dodam tez czysto informacyjnie, ze o ile nekromanta respi sie praktycznie odrazu, to quest giver pojawia sie po prawie 10 minutach.
Nie wyczytalem nigdzie, ze ten quest jest na jakis timer, wiec to conajmniej dziwne.
https://youtu.be/-K6TOGAkX5E (pelny przebieg questa, wraz ze skryptowaniem)
http://screenshooter.net/102844212/cjgyulv .gps
http://wotlk.openwow.com/quest=11705

Edit: Postanowilem przeforsowac sie z moim jedynym potkiem, by go zrobic, bez wychodzenia z walki za pomoca vanisha. Znikli na 19k hp (11%). 
Dodatkowo jego banka, ktora daje mu niepodatnosc przestala dzialac, pomimo ze sie wyswietla (nie zostal zabity i tak jakby zresetowal sie encounter ale juz nie sam status moba.) 
http://screenshooter.net/102844212/uscogtm

**Obecne działanie**: Encounter przerywa znikniecie obu npc z fazowania, po chwili wraca wrogi npc, nieco pozniej quest giver. 

**Oczekiwane działanie**: Skoro go bije to powinien dac sie zbic do konca, nie resetowac.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Wziac q
2. Podazac wedlug celow zadania (skrypt nas prowadzi)
3. Wziac udzial w encounterze.

**Linki WoWHead/OpenWoW**:

1. w/w
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
w/w

**Comment by NoobSunwell** [comment]
Będzie naprawione po update.
