### ISSUE TITLE
[Profesje] Nauka na wyzszy poziom "mistrzostwa"

### ISSUE THREAD

**Issue by kovaq** [NoobSunwell/Sunwell-BugTracker#14]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Historia na przykaldzie Skinningu. Z gry wyciagniety. Podejrzewam ,ze starczyloby mi skor by sprawdzic rowniez leatherworking, ale na ta chwile troche mi szkoda, sprawdze, gdy dostane informacje, ze skinning zostal poprawiony.

**Obecne działanie**: Po osiagnieciu skilla wymaganego do nauki Journeyman Skinning i wykupieniu go zauwazylem pewien niepokojacy fakt: http://screenshooter.net/102844212/xvkojrx profka sie wyzerowala.

**Oczekiwane działanie**: Profka powinna pozostac tak jak byla, tj akurat w moim przypadku 71 skilla.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Dobic wymagany poziom umiejetnosci do ulepszenia jej (min 50)
2. Pojsc do trenera.
3. Wytrenowac profke.

**Comment by NoobSunwell** [comment]
Będzie poprawione po aktualizacji.
