### ISSUE TITLE
[Frakcja] D.E.H.T.A

### ISSUE THREAD

**Issue by kovaq** [NoobSunwell/Sunwell-BugTracker#140]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Frakcja D.E.H.T.A - Panowie druidzi powinni byc dla nas agresywni jezeli mamy na sobie debuff z krwi dowolnego zwierzecia. Pomimo ze sam debuff naklada sie, oraz zmywa jak trzeba, to sam jego efekt nie dziala.
http://wowwiki.wikia.com/wiki/Druids_fo ... of_Animals
https://youtu.be/IL0mbaqKXGE
http://screenshooter.net/102844212/sjskvlt .gps

**Obecne działanie**: Druidzi mimo krwi zwierzecia nie zwracaja na mnie uwagi.

**Oczekiwane działanie**: Druidzi powinni sie rzucac na kazdego kto sie zblizy, bedac usmarowanym krwia.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Zabic dowolnego niewinnego zwierzaka.
2. Pojsc do obozu.
3.

**Linki WoWHead/OpenWoW**:

1. w/w
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
w/w

**Comment by NoobSunwell** [comment]
Będzie naprawione po update.
