### ISSUE TITLE
[Quest] The Emissary.

### ISSUE THREAD

**Issue by kovaq** [NoobSunwell/Sunwell-BugTracker#141]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Quest The Emissary. Celem jest Leviroth, kraken plywajacy w wodzie. "Plywajacy" to za duzo powiedziane, gdyz lezy on bez ruchu w wodzie. Nawiazujac do innych zrodel, wszedzie potwierdzone jest, ze ruszac to on raczej sie nie rusza, wiec tego nie ma co roztrzasac.
Kwestią buga natomiast jest fakt, ze harpun w momencie rzutu najpierw wyrzuca informacje "You cant do that yet" budzac krakena do zycia (ujawniajac rowniez jego nameplate), po czym dopiero ponowne klikniecie wykonuje prawidlowego casta. Damage harpuna jest ok, cala reszta po tym fakcie rowniez.
http://wotlk.openwow.com/quest=11626
http://www.wowhead.com/item=35850/trident-of-nazjan
https://youtu.be/okw9wZdReXc
http://screenshooter.net/102844212/hmcohqu .gps

**Obecne działanie**: Harpun najpierw wywoluje efekt "You cant do that yet", a sam kraken dopiero ozywa, drugi rzut dopiero dziala prawidlowo.

**Oczekiwane działanie**: Harpun odrazu jest "able" by uderzyc krakena.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Wziac q, poplynac do krakena.
2. Uzyc q itemu.
3.

**Linki WoWHead/OpenWoW**:

1. w/w
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
w/w

**Comment by NoobSunwell** [comment]
Powinno być ok po update (visual i item).
