### ISSUE TITLE
[QUEST] Battle at Valhalas: Carnage!

### ISSUE THREAD

**Issue by nexx94** [NoobSunwell/Sunwell-BugTracker#142]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:

**Obecne działanie**: Mob używa tylko skilla War Stomp. Spawni się z powietrza. Wejścia innych bossów z chaina są również nie prawidłowe, nie wiem czy otwierać osobne zgłoszenia. NPC dający questa, Geirrvif unosi się za wysoko nad ziemią, nie można z nią zagadać będąc na ziemi, tak jak DK na filmiku.

**Oczekiwane działanie**: Powinien używać również autoattacku i Smash. Wejście na arenę pokazane jest na filmiku https://www.youtube.com/watch?v=KhU8lNBgBUs

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Wziąć quest Battle at Valhalas: Carnage!
2. Bić bossa
3. 

**Linki WoWHead/OpenWoW**:

1. http://wotlk.openwow.com/npc=31271#abilities
2. http://wotlk.openwow.com/spell=61065
3. http://wotlk.openwow.com/spell=61070
4. http://wotlk.openwow.com/quest=13217
5. http://www.wowhead.com/npc=31135/geirrvif

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
https://imgur.com/a/yJVdO

**Comment by NoobSunwell** [comment]
![image](https://cloud.githubusercontent.com/assets/22621466/19481541/97566752-954e-11e6-9d37-4ff7342bf8ac.png)

Widzę, że skilli używa poprawnie.

Co do NPC - został on obniżony.

Po update.
