### ISSUE TITLE
[QUEST] Ashenvale Outrunners

### ISSUE THREAD

**Issue by Kokaina** [NoobSunwell/Sunwell-BugTracker#143]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Banalny quest polegający na zabiciu 9x NPC o nazwie Ashenvale Outrunner

**Obecne działanie**: Obecnie NPC które mamy zabijać mają niekompletny zestaw skilli, brakuje im spella Ashenvale Outrunner Sneak (dalej nazywany stealthem), gdyż domyślnie tych NPC nie powinno być widać gdy nie mają na sobie combatu. Mimo to NPC są widoczne z powodu oczywistego braku w/w skilla. Umieszczam dowód w screenie z GPSem

**Oczekiwane działanie**: NPC powinny mieć domyślnie spell stealtha 

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Podlecieć do NPC i mu się przyjrzeć, nawet bez brania questa
2. 
3. 

**Linki WoWHead/OpenWoW**:

1. https://www.youtube.com/watch?v=pbDNYnfxR1c - pokazuje działanie questa na globie (ok. 40sekunda widać, że NPC są w stealthu)
2. NPC Ashenvale Outrunner ID: 12856 (http://wotlk.openwow.com/npc=12856)
3. ID brakującego spella: 20540 (http://wotlk.openwow.com/spell=20540)
4. Quest ID: 6503 (http://wotlk.openwow.com/quest=6503)

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
https://s10.postimg.org/ej6wm212h/Wo_WScrn_Shot_101616_191911.jpg

**Comment by NoobSunwell** [comment]
Będzie naprawione po update.
