### ISSUE TITLE
[Quest] Help Those, Who Cannot Help Themselves.

### ISSUE THREAD

**Issue by kovaq** [NoobSunwell/Sunwell-BugTracker#144]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:  Quest Help those who cannot help themselves - czyli mamuty zlapane w plapke. Pierwsze uzycie uwalnia mamuta, ktory zaczyna chodzic wokol plapki. Czas cd na mlotek to 15 sekund i w tym czasie mamut spowrotem podchodzi do plapki. Jezeli ustawil sie dogodnie, to bedzie w zasiegu by drugi raz walnac mlotkiem w ta plapke, napijajac drugi punkt do questa. Po zniknieciu mamuta pusta plapka zaczyna dzialac prawidlowo, nie pozwalajac na kolejne nabicie progressu questa.
https://youtu.be/BWwJlBbv4vQ
http://wotlk.openwow.com/quest=11876
http://screenshooter.net/102844212/foctnrs .gps

**Obecne działanie**: Przy wprawnym uderzaniu mlotkiem, mozna na jednej plapce zrobic 2 punktu progressu questa.

**Oczekiwane działanie**: Powinna byc 1 plapka na 1 punkt do zadania.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Wziac q
2. Podejsc do plapki, uderzyc ja q itemem.
3. Po zejsciu cooldownu, ale przed zniknieciem malego uwolnionego mamuta uzyc ponownie q itemu.

**Linki WoWHead/OpenWoW**:

1. w/w
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
w/w

**Comment by NoobSunwell** [comment]
Będzie naprawione po update.
