### ISSUE TITLE
[Quest] Load'er Up!

### ISSUE THREAD

**Issue by kovaq** [NoobSunwell/Sunwell-BugTracker#146]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Quest Load'er Up! Po oddaniu osiołek z escorty dalej mnie followuje zamiast zniknac.
http://wotlk.openwow.com/quest=11881
http://screenshooter.net/102844212/nwnwqup dowod + .gps
Relog pomaga.

**Obecne działanie**: Osiołek nie znika

**Oczekiwane działanie**: Osiołek powinien zostawac przy goblinie/ znikac.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Odeskortowac osiolka i oddac q.
2. Obserwowac jego zachowanie po oddaniu q
3. 

**Linki WoWHead/OpenWoW**:

1. w/w
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
w/w

**Comment by NoobSunwell** [comment]
Będzie naprawione po update.
