### ISSUE TITLE
[QUEST] Battle at Valhalas: Final Challenge

### ISSUE THREAD

**Issue by nexx94** [NoobSunwell/Sunwell-BugTracker#147]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:

**Obecne działanie**: Quest kończy się powodzeniem bez walki z bossem

**Oczekiwane działanie**: Trzeba walczyć i pokonać bossa

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Wziąć questa Battle at Valhalas: Final Challenge
2. Zaczekać
3. Quest zakończony pomyślnie bez walki

**Linki WoWHead/OpenWoW**:

1. http://www.wowhead.com/quest=13219/battle-at-valhalas-final-challenge
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
https://imgur.com/a/hqNFz

**Comment by NoobSunwell** [comment]
Będzie naprawione po update.
