### ISSUE TITLE
[Statystyki] Largest Hit Dealt oraz Total Damage Done.

### ISSUE THREAD

**Issue by kovaq** [NoobSunwell/Sunwell-BugTracker#148]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Rubryka statystyk zwiazanych z Largest Hit Dealt nie dziala.
http://screenshooter.net/102844212/snclpig
To samo dotyczy Total Damage Done:
http://screenshooter.net/102844212/cdricox

**Obecne działanie**: Nie nalicza w/w statystyk.

**Oczekiwane działanie**: Powinno sledzic na biezaco nasze poczynania i je aktualizowac w statach.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Klawisz Y
2. zakladka Statistics
3. Larget Hit Dealt to podajze 6 pozycja, Total Damage Done jest nieco nizej.

**Linki WoWHead/OpenWoW**:

1. Nie dotyczy.
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
Nie dotyczy.

**Comment by NoobSunwell** [comment]
Obie statystyki zostały z tego co widzę wyłączone przez pussywizarda z powodów optymalizacyjnych (podobnie jak kilka innych statystyk odnośnie DMG - zbyt częste aktualizacje - gdzie przy 4k graczy nie dziwi mnie ta decyzja).
