### ISSUE TITLE
[Quest] Weakness To Lightning.

### ISSUE THREAD

**Issue by kovaq** [NoobSunwell/Sunwell-BugTracker#149]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Quest Weakness to lightning. Jeden typ robotow nie nalicza sie do questa. Jest to Scavenge-bot.
http://wotlk.openwow.com/quest=11896
http://wotlk.openwow.com/npc=25752
http://screenshooter.net/102844212/atykinq .gps
http://screenshooter.net/102844212/glyphou

**Obecne działanie**: Jeden z robotow nie nalicza progressu zadania.

**Oczekiwane działanie**: Wszystkie roboty w danej lokacji powinny zaliczac progress.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Wziac q
2. Pojechac na The Geyser Fields
3. Oslabic q itemem robota oraz po tym go zniszczyc. W Wypadku Scavenge Bota nie naliczy nam progressu.

**Linki WoWHead/OpenWoW**:

1. w/w
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
w/w

**Comment by NoobSunwell** [comment]
Będzie naprawione po update.
