### ISSUE TITLE
[NPC] Aleric Hawkins

### ISSUE THREAD

**Issue by kovaq** [NoobSunwell/Sunwell-BugTracker#15]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Robie zadanie dotyczace chain questu klasowego dla rogue'a. Jest to odpowiednik na 10ty lvl w kazdej stolicy. http://www.wowhead.com/quest=1978/the-deathstalkers . 
Gdy przychodzi do oddania q, no coz... http://screenshooter.net/102844212/xhayxwv tak jak pisal quest, http://screenshooter.net/102844212/mcsdlye Hall of Dark Lady - tu go nie ma. Z podpowiedzi w q na mapie wyniklo, ze moze wyszedl ponad ta sale, bo jest ona pod jeziorem, a jest tam napisane Lordamere Lake, ale tu tez go nie bylo. http://screenshooter.net/102844212/rhotpus . Dodatkowo to ciekawe, ze q wysyla mnie do sali Sylvanas, a na mapie pokazuje jakoby to bylo na jeziorze. W wersji na wowheadzie mamy podana nazwe Varimathras. Jest on bezposrednio powiazany z eventem Battle of the Undercity. Czy to moze byc powodem jego nieobecnosci w Hall of Dark Lady? (brakuje rowniez straznikow Undercity, zarowno abomek jak i kor'kronow)

**Obecne działanie**: Nie ma goscia.

**Oczekiwane działanie**: Powinien stac.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Robic class quest dla rogue'a.
2. Dotrzec do danego ogniwa tego chain questa.
3. Przejsc do Hall of Dark Lady i przekonac sie, ze go tam nie ma.

**Comment by NoobSunwell** [comment]
Powinno działać po aktualizacji.
