### ISSUE TITLE
[Quest] Breaking Through.

### ISSUE THREAD

**Issue by kovaq** [NoobSunwell/Sunwell-BugTracker#150]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Quest Breaking Through. Po zabiciu objective'ow nie mozna ponownie wejsc portalem na poziom Prince'a Valanara. Zamiast tego przenosi nas na dach, gdzie stoi wrogo do nas nastawiony Thassarian.
http://wotlk.openwow.com/quest=11898
http://screenshooter.net/102844212/cxlifjn (gps)
Dodatkowo w samym quescie Prince Valanar jest zabugowany. Chcialem go nagrac ale niestety afczac na jego powrot zrespil sie mobek obok i mnie zaciukal. Stad problem powyzej, nie moge do niego wrocic, by go nagrac. Dlatego tez opisuje.
http://wotlk.openwow.com/npc=25601
Prince Valanar. Mag, ktory z melee bije tyle co z shadowbolta (900-1200 melee, 1100 spell). Ale to jeszcze mozna zrozumiec, elita, musi sie jakos bronic, ok.
Natomiast Soulblast (http://wotlk.openwow.com/spell=50992) bije po -1, a Soul Deflection (http://wotlk.openwow.com/spell=51009) po wycatowaniu robi 100% dmg zreflektowanego z... zera. W tym momencie jest to bardziej pomocny spell, gdyz boss castujac go daje sie klepac, a sam nie robi nic poza pustym castem.
To, co udalo sie wymuskac z combat logow:
http://screenshooter.net/102844212/vxstcgg
http://screenshooter.net/102844212/eaplyfx

Dodam, ze smierc w nekropolii konczy sie instantowym podniesieniem na cmentarzu, zamiast "maratonu ducha", ale zdaje sie, ze to jest prawidlowe rozwiazanie, ze wzgledu na lokacje do ktorej wchodzi sie teleportem.

Dorzucam podpunkt kolegi, na wersje aliancka:
http://forum.sunwell.pl/viewtopic.php?f=74&t=377 punkt 1. 
Dodam, ze mi nikt nie tankuje Prince'a jak w wersji alianckiej, oraz sklonny jestem uznac, ze wcale malo nie bije, gdyby nie to ze rowniez zrobilem go solo, a to q na 3man party. (zaznaczam, nie bylo latwo, pomogly bugi moba.)

**Obecne działanie**: Zle dzialajacy Prince Valanar, oraz dziwna zaleznosc portalu do questa.

**Oczekiwane działanie**: Powinien normalnie bic, a teleport powinien byc dostepny by moc wejsc na poziom princa.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Wziac q, dostac sie do nekropolii
2. Zabic princa, jezeli solo to zapewne bez wykorzystania jego zabugowanych umiejetnosci sie nie obejdzie.
3. Wyjsc (ew zginac jak ja) z tego pietra, po czym probowac wejsc ponownie.

**Linki WoWHead/OpenWoW**:

1. w/w
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
w/w

**Comment by NoobSunwell** [comment]
![image](https://cloud.githubusercontent.com/assets/22621466/19622043/aba1708a-98a0-11e6-89e4-c64b6ec8a04f.png)

![image](https://cloud.githubusercontent.com/assets/22621466/19622046/b2f4ab2c-98a0-11e6-9848-485332dcb6ca.png)

Castuje ok. Co do zależności - wydaje mi się normalna - w końcu nie ma po co wracać do tego pomieszczenia po zabiciu. Dlaczego tak uważam? Kto by nie chciał móc swobodnie sobie przebywać w nekropolii, do której nie ma dostępu z zewnątrz?
