### ISSUE TITLE
[Quest] Keep the Secret Safe.

### ISSUE THREAD

**Issue by kovaq** [NoobSunwell/Sunwell-BugTracker#152]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:  Quest Keep the Secret Safe. Stworki z ktorych nalezy zbierac esencje okazjonalnie spadaja pod tekstury. Dzieje sie tak, gdyz zlatuja one z gory i niekiedy ustawiaja sie 50.50 w teksturze na tak zwany styk. (na 8 mobow 3 spadly)
http://wotlk.openwow.com/quest=11914
http://wotlk.openwow.com/npc=25721
http://screenshooter.net/102844212/hssvaij (gps) tu powinny byc 2 ciala. Czarna skalka po lewej jest delikatnie wybrzuszona do gory i wlasnie tam zniknal mi 1 smok.

**Obecne działanie**: Moby zlatujace z gory czesto laduja w teksturze.

**Oczekiwane działanie**: Nie wazne gdzie, zawsze powinny opadac na teren, nie pod niego.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Pullnac moba z powietrza.
2. Po jego zlocie on sie ustawi na naszej wysokosci.
3. Jezeli jest w specyficznym miejscu jak w/w nalezy go zabic i obserwowac upadek.

**Linki WoWHead/OpenWoW**:

1. w/w
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
w/w

**Comment by NoobSunwell** [comment]
Będzie poprawione po update.
