### ISSUE TITLE
[Talenty] Talents widziane przez drugiego gracza.

### ISSUE THREAD

**Issue by kovaq** [NoobSunwell/Sunwell-BugTracker#155]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Dogadalem sie, ze zglosi to kto inny, ale nie widzialem tego zgloszenia, wiec zrobie to osobiscie.
Wystepuje dosyc nieprzyjemny visual talentow u innych graczy.
Zwyczajnie ich nie widac.
http://screenshooter.net/102844212/cigxddw
http://screenshooter.net/102844212/mthujqf
Dziekuje rowniez Kougrze za pomoc :)

**Obecne działanie**: Nie widac talentow innych graczy.

**Oczekiwane działanie**: Powinienem miec mozliwosc "podejrzenia" w czym jest inny gracz.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. prawym przyciskiem myszy na portret kolegi/kolezanki.
2. przycisk inspect.
3. zakladka talents.

**Linki WoWHead/OpenWoW**:

1. Nie dotyczy.
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
Nie dotyczy.

**Comment by NoobSunwell** [comment]
Będzie naprawione po update.

**Comment by Kougraa** [comment]
Nie ma za co :)

**Comment by nexx94** [comment]
https://imgur.com/a/FnOme
Błąd dalej występuje w przypadku podglądania graczy przeciwnej frakcji w terenach Sanctuary

**Comment by NoobSunwell** [comment]
Przeciwnej frakcji nie można podglądać do któregoś z patchy późniejszych w WotLK, nie pamiętam teraz któego.

**Comment by Kougraa** [comment]
Błąd nadal występuje.
