### ISSUE TITLE
[Movemapy] Winterfin Shorestriker

### ISSUE THREAD

**Issue by kovaq** [NoobSunwell/Sunwell-BugTracker#157]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Winterfin Shorestriker w Winterfin Village na plaskiej plazy podczas run away in fear effect uciekl centralnie w dol. Nie ma tam zadnej jaskini by mogl przeniknac "pietro" nizej.
http://screenshooter.net/102844212/tlqsoqi
http://screenshooter.net/102844212/yubrcfm (gps)
http://wotlk.openwow.com/npc=25215

Zglaszam dla pewnosci, lepiej by bylo niepotrzebne, niz by brakowalo.

Dodatkowo drugi murlok zrobil to samo na wyjsciu z jaskini (to samo miejsce, tylko nalezy obrocic kamere i wejsc pod gorke jakies 50yardow)

**Obecne działanie**: w/w

**Oczekiwane działanie**: Niech biega po ziemi.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Bic moba w miejscu gdzie mozna trafic na "zepsuty" punkt.
2. Zbic mu zycie do resztki by wywolac efekt away in fear.
3. Obserwowac jego znikanie w teksturze.

**Linki WoWHead/OpenWoW**:

1. w/w
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
w/w

**Comment by NoobSunwell** [comment]
Powinno być ok po update (problem po zmianach do VMap nie wystąpił w tym miejscu u mnie dzisiaj).
