### ISSUE TITLE
[Line of sight] Magmoth Forager.

### ISSUE THREAD

**Issue by kovaq** [NoobSunwell/Sunwell-BugTracker#158]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Magmoth Forager zapadniety w podloge.
http://screenshooter.net/102844212/uexyplv (gps)
http://wotlk.openwow.com/npc=25429

**Obecne działanie**: kobold zapadl sie w teksture, powoduje efekt line of sight.

**Oczekiwane działanie**: Nalezaloby go wyjac z tekstury.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Podejsc do niego.
2. Probowac go bic.
3. 

**Linki WoWHead/OpenWoW**:

1. w/w
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
w/w

**Comment by NoobSunwell** [comment]
Będzie naprawione po update.
