### ISSUE TITLE
<class> Hunters pet

### ISSUE THREAD

**Issue by valcy** [NoobSunwell/Sunwell-BugTracker#16]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:Po revive pet huntera cofa sie w rozwoju...

**Obecne działanie**: Hunterowy pet traci lvle w momencie gdy po despawnie jego ciala uzyjemy revive.

**Oczekiwane działanie**: Po uzyciu revive pet jest identyczny jak przed zgonem i despawnem.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Sprawic zeby pet padl.
2. Poczekac az zdespawnuje sie cialo peta (albo tez pasc zaraz po nim zeby przyspieszyc ten proces).
3. Uzyc revive.

**Comment by valcy** [comment]
to dzieje sie najwidoczniej przy jakim kolwiek despawnie peta bo jak zsiadam z mounta lvl peta tez sie cofa (ogolem zawsze ma 5 lvli mniej niz ja)

**Comment by turboszczur** [comment]
pet też wyłącza sobie growla co jakiś czas i growl też potrafi zniknąć z paska od peta i trzeba go znów wyciągąć

**Comment by turboszczur** [comment]
Z tego co zauważyłem dotychczas: pet gdy dostaje rozkaz zaatakowania czasem go ignoruje i zdarza się to przy większych odległościach, rzadko biega tam i z powrotem mniej więcej do połowy celu jak bumerang. Spelle ( m.in. growl jak pisałem wyżej) mają zwyczaj znikania z paska, chyba to jest związane z lvl up peta i dodawaniem spella wyższego poziomu. Pety też mają problem z utrzymaniem agro ale myślę że jest to związanie i ich niedorozwojem gdy im cofa lvle.

**Comment by turboszczur** [comment]
Ponadto petowi resetują się talenty przy cofaniu lvla i punkty są nierozdane.

**Comment by turboszczur** [comment]
Ale tu spamuje. Dmg peta jest zbyt mały. Ciężko to udowodnić jakimiś konkretnymi screenami ale mój pet (gram w bm) bije połowe tego co ja, a zazwyczaj jest odwrotnie to pet powinien robić główny dmg w bm podczas levelovania.

**Comment by NoobSunwell** [comment]
Spamuj śmiało, czym więcej informacji tym lepiej. Problem jest na tyle uciążliwy, że występuje tylko na serwerze dedykowanym (Linux).

**Comment by turboszczur** [comment]
Ten reset talentów peta jest nieregularny - myślałem wpierw że po relogu lecz też nie. Pytałem innych hunterów też czasem resetowały się petom talenty lecz ciężko to zreplikować. Aktualnie nie mogę wskazać bezpośredniej przyczyny. Devilsaur od paru ładnych godzin zachował swe talenty, może reset występuję w momencie gdy pet dostaje nowy talent point. Ciężko stwierdzić.

**Comment by turboszczur** [comment]
Szarża peta powoduje że mobki podskakują przez ułamek sekundy.

https://www.youtube.com/watch?v=hgehZ1gbj6A&feature=youtu.be
https://www.youtube.com/watch?v=yoWwqWgycbU&feature=youtu.be

**Comment by turboszczur** [comment]
Pet se znika czasem (chyba w texturach). Nagrane po dzisiejszym updacie.

https://www.youtube.com/watch?v=a2b7GdA3_Qg&feature=youtu.be

**Comment by NoobSunwell** [comment]
Ale dzisiaj nie było update przed 19tą.

**Comment by turboszczur** [comment]
Tak, zmylił mnie changelog, my bad.

**Comment by turboszczur** [comment]
Spell Intimidation nabija threata na nas zamiast na peta. Pet jest tym który wykonuje atak więc on powinien dostrać tego threata.

**Comment by NoobSunwell** [comment]
Problem z petem naprawiony - nie będzie już mu cofało levela, tak samo spelli. 

Intimidation - działa bez zarzutu - testowane na elitkach w Outland - miałem 65% aggro, po użyciu i ataku przez peta - spadło do 45.

**Comment by turboszczur** [comment]
Nic nie napisałeś o szarży peta. A co do intimadtion to takie coś występuję, ale też nieregularnie. 

https://www.youtube.com/watch?v=b4Db5BjhURw&feature=youtu.be
https://www.youtube.com/watch?v=rgFhPry3wQ0&feature=youtu.be

Jak widać część wrogów się na mnie rzuca gdy pet używa intimidation. Dzieję się tak z innymi npcami też czasem.

Kordy: http://imgur.com/a/88fw1

**Comment by NoobSunwell** [comment]
Co do szarży peta - to ogólnie sprawa tak się prezentuje z rootami (np u maga frostbite) - podnosi o ten kawałek nad ziemię, aby nie było problemów z wpadaniem pod ziemię. Co do tego z aggro - stawiałbym na coś innego. Potem to sprawdzę.

**Comment by turboszczur** [comment]
No możliwe bo jak używam bestial wratha albo gdy zabijemy 1 wroga to reszta czasem się na mnie rzuca bez powodu.

**Comment by HeartWell** [comment]
Why this problem only for Linux?
