### ISSUE TITLE
[Quest] Escape from the Winterfin Caverns.

### ISSUE THREAD

**Issue by kovaq** [NoobSunwell/Sunwell-BugTracker#160]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Quest Escape from the Winterfin Caverns. Murlok, ktorego wyprowadzamy z jaskini pulla sie na wszystko wokol. Aby mu pomoc, musimy wylaczyc disguise (murloc suit) i bic sie razem z nim.
http://screenshooter.net/102844212/acipoeq (gps)
Ad. Zabawna sytuacja. wrocilem, by zrobic skrina gpsu, a tu mob wyszedl sobie kulturalnie z klatki i bije sie z jednym z murlokow. Po wszystkim wrocil do klatki.
http://screenshooter.net/102844212/lntmrar
http://wotlk.openwow.com/quest=11570
Co do samych sciezek jakimi podaza murlok to nie mam zastrzezen.

**Obecne działanie**: Murlok bije sie z innymi, gdy jestesmy na disguisie. Dodatkowo poza questem napiera sie z najblizszym murlokiem "straznikiem".

**Oczekiwane działanie**: Powinien byc neutralny dla przeciwnika. Poza questem powinien grzecznie stac w klatce.

**Co należy zrobić, aby odtworzyć ten błąd**:

Z Questem:
1. Podejsc tam.
2. Wziac q i zaczac eskorte.
3. Obserwowac agresje.

Poza questem:
1. Podejsc tam.
2. Obserwowac jak murlok rzuca sie na "straznika" w momencie gdy tylko ten znajdzie sie w jego zasiegu.

**Linki WoWHead/OpenWoW**:

1. w/w
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
w/w

Dorzucam jeszcze to:
http://screenshooter.net/102844212/odakmho
161 q zrobionych, 18 wymienionych wyzej wymaga minimalnych poprawek, 0 powaznych bugow. Jest naprawde przyjemnie, dziekuje :)

**Comment by NoobSunwell** [comment]
https://www.youtube.com/watch?v=thFtcw_L024 1:23 - na każdym filmiku widzę, że ludzie robią to bez przebrania - a we wskazanym momencie widać, że powinien on aggrować na inne moby.

https://www.youtube.com/watch?v=KWaalMs0OKE 2:37 - tak samo.

https://www.youtube.com/watch?v=6_gL7u_BdEE - tu już dowód z przebraniem.

**Comment by kovaq** [comment]
Ok, czy agrowanie sie z klatki tez w takim razie jest nie wazne? npc ma ponad 10k hp, a moby maja po 8k, wiec w pojedynku 1na1 raczej nie przegra i nie zginie, uniemozliwiajac wziecie q, ale czy to pewne?
