### ISSUE TITLE
[NPC] Fizzcrank Bomber

### ISSUE THREAD

**Issue by ShatteredGlassx** [NoobSunwell/Sunwell-BugTracker#161]
Obecne działanie: Kilkadziesiąt samolotów w jednej teksturze przelatuje nad Fizzcrank Airstrip 

Oczekiwane działanie: Jeden samolot przelatuje nad Fizzcrank Airstrip

Co należy zrobić, aby odtworzyć ten błąd:

Nie mam pojęcia, po prostu przelatywały, ale co spowodowało ten bug, to niestety nie wiem.

Linki WoWHead/OpenWoW:

1.  http://wotlk.openwow.com/npc=25765
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
GPS: 4194 , 5411 , 28 , 571

Screen: https://zapodaj.net/1a754abdc339c.jpg.html

**Comment by NoobSunwell** [comment]
Mi to bardziej wygląda na glitch graficzny po stronie klienta. U mnie spokojnie lata 1 NPC.
![image](https://cloud.githubusercontent.com/assets/22621466/19421505/293e69a0-9403-11e6-9863-58b9709dabd4.png)
