### ISSUE TITLE
[Mob] Shadowy Tormentor.

### ISSUE THREAD

**Issue by kovaq** [NoobSunwell/Sunwell-BugTracker#163]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Lokacja Agmar's Hammer wypelniona jest mobami nazwanymi Shadowy Tormentor, ktore przynaleza do questa The Power to Destroy, wywolujacym fazowanie w tak zwany "realm of shadows" przez Koltire Deathweaver'a. Skoro sa w normalnym swiecie, to zapewne fazowanie nie dziala.
http://wotlk.openwow.com/npc=26966
http://wotlk.openwow.com/quest=12132
http://screenshooter.net/102844212/qmdvmrc (gps)

**Obecne działanie**: Tormentory chodza nie w tej fazie co trzeba.

**Oczekiwane działanie**: Dopiero w momencie wziecia questa powinno nas wrzucac do realm of shadows, podczas gdy tu, mozna powiedziec nawet nie wiem, ze bede miec takie zadanie, a juz je widze i mnie bija.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Przyjechac do Agmar's Hammer.
2. 
3. 

**Linki WoWHead/OpenWoW**:

1. w/w
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
w/w

**Comment by NoobSunwell** [comment]
![image](https://cloud.githubusercontent.com/assets/22621466/19421477/929e68c4-9402-11e6-876d-dae98f6f629f.png)

![image](https://cloud.githubusercontent.com/assets/22621466/19421479/9e9e1836-9402-11e6-8dfe-fe0e29a967d4.png)

Pamiętasz jakiego questa robiłeś przed tym (spoza chaina u tego NPC)?

**Comment by kovaq** [comment]
Nie robilem zadnego zadania w Agmar's Hammer. Ostatnie jakie zrobilem to przejscie z wioski taurenow na granicy Borean i Dragonblight, do wlasnie Agmar's Hammer.
http://wotlk.openwow.com/quest=12008

**Comment by kovaq** [comment]
Jakby co to po ponownym zalogowaniu do gry juz bylo wszystko ok (po Twojej interwencji Noob, wiec moze uzyles jakiejs magii ;p), wlasnie skonczylem questa z nimi zwiazanym i jego rowniez ok.
