### ISSUE TITLE
QUEST:  Breaking the Ward

### ISSUE THREAD

**Issue by Xanador** [NoobSunwell/Sunwell-BugTracker#164]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Quest ogółem działa, ale brakuje skryptu wykonywania zaklęcia.

**Obecne działanie**: Po wzięciu zadania, nasz http://wotlk.openwow.com/npc=7783 nie castuje zaklęcia, tak jak jest to napisane w zadaniu:
"Wait for Loramus to complete the enlightenment spell. "
Tylko od razu jest autocomplete.

**Oczekiwane działanie**: TU WPISZ JAK TO POWINNO WYGLĄDAĆ
Tu jest mały problem, ponieważ nie mogę znaleźć ID zaklęcia ...
Po wzięciu questa, NPC powinien zacząć castować? Przywoływać coś? Dopiero po skończeniu "tego czegoś" quest powinien zaliczyć się.

**Co należy zrobić, aby odtworzyć ten błąd**: PS. To długi chain.
1. Zrobić quest: http://wotlk.openwow.com/quest=2721
2. Zrobić quest: http://wotlk.openwow.com/quest=2743
3. Zrobić quest: http://wotlk.openwow.com/quest=2744
4. Zrobić quest: http://wotlk.openwow.com/quest=3141
5. Wziąć quest: http://wotlk.openwow.com/quest=3508
6. Autocomplete, bez żadnego przywoływania ...

**Linki WoWHead/OpenWoW**:

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**: SS3
http://imgur.com/a/Xn1DP

####EDIT: Nie ma również nigdzie filmu :C.

**Comment by NoobSunwell** [comment]
Niestety dopóki nie będę miał jakiegoś video lub spella, to nic nie zrobię. W życiu tego questa na oczy nie widziałem, spella też znaleźć odpowiedniego nie mogę w DBC.
