### ISSUE TITLE
[Quest] Re-Cursive

### ISSUE THREAD

**Issue by ShatteredGlassx** [NoobSunwell/Sunwell-BugTracker#165]
Obecne działanie: Użycie quest itema na martwym Fizzcrank Mechagnome zalicza quest podwójnie. 2/6, 4/6 itd

Oczekiwane działanie:  Użycie quest itema na martwym Fizzcrank Mechagnome powinno zaliczać quest pojedynczo 1/6, 2/6 itd.

Co należy zrobić, aby odtworzyć ten błąd:

1. Wziąć quest http://wotlk.openwow.com/quest=11712
2. Zabić Fizzcrank Mechagnome
3. Użyć Re-Cursive Transmatter Injection na martwym Fizzcrank Mechagnome

Linki WoWHead/OpenWoW:

1. http://wotlk.openwow.com/quest=11712
2. http://wotlk.openwow.com/item=34973
3. http://wotlk.openwow.com/npc=25814

Lokalizacja z koordynatów GPS (X, Y, Z, Map):
4247 5176 13 571

**Comment by NoobSunwell** [comment]
Będzie naprawione po update.
