### ISSUE TITLE
[Quest] Repurposed Technology

### ISSUE THREAD

**Issue by ShatteredGlassx** [NoobSunwell/Sunwell-BugTracker#166]
Obecne działanie: Po użyciu quest itema na martwym Harvest Collectorze ciało nie znika.

Oczekiwane działanie: Po użyciu quest itema na martwym Harvest Collectorze ciało powinno znikać.

Co należy zrobić, aby odtworzyć ten błąd:

1. Wziąć quest Repurposed Technology
2. Zabić Harvest Collector
3. Użyć quest item na martwym Harvest Collector

Linki WoWHead/OpenWoW:

1. http://wotlk.openwow.com/quest=12035
2. http://wotlk.openwow.com/item=35943
3. http://wotlk.openwow.com/npc=25623

Lokalizacja z koordynatów GPS (X, Y, Z, Map):
2535 5197 37 571

**Comment by NoobSunwell** [comment]
Będzie naprawione po update.
