### ISSUE TITLE
[Quest] Take No Chances

### ISSUE THREAD

**Issue by ShatteredGlassx** [NoobSunwell/Sunwell-BugTracker#167]
Obecne działanie: Podchodząc do niespalonego worka i używając na niego quest item, quest jest zaliczany 1/8, ale dalsze używanie quest itema zalicza go ponownie na 2/8 itd.

Oczekiwane działanie: Spalony worek nie powinien zaliczać questa, powinniśmy szukać nowego worka, aby zaliczać quest dalej.

Co należy zrobić, aby odtworzyć ten błąd:

1. Wziąć quest Take No Chances
2. Użyć quest item na workach.

Linki WoWHead/OpenWoW:

1. http://wotlk.openwow.com/quest=11913
2. http://wotlk.openwow.com/item=35491
3. 

Lokalizacja z koordynatów GPS (X, Y, Z, Map):
2524 5347 32 571

**Comment by NoobSunwell** [comment]
Będzie naprawione po update.
