### ISSUE TITLE
[QUEST] Protect Kanati Greycloud

### ISSUE THREAD

**Issue by Kokaina** [NoobSunwell/Sunwell-BugTracker#168]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Po wzięciu Questa od NPC1 powinien on zostać zaatakowany przez 4x NPC2. Naszym zadaniem jest obronić questgivera i zabić cztery zespawnione mobki

**Obecne działanie**: Po pobraniu questa od NPC1 pojawiaja się 4x NPC2, które jednak nie atakują guestgivera lecz stoją bezczynnie w znacznej odległości, po kilku sekundach quest zalicza się samoistnie

**Oczekiwane działanie**: Zespawnione 4x NPC2 powinny zaatakować questgivera, natomiast credit za questa powinien wpaść dopiero po zabiciu tych NPC2

**Co należy zrobić, aby odtworzyć ten błąd**: 

1. Wykonać prequesta żeby móc pobrać zgłaszany quest
2. Przypatrywać się

**Linki WoWHead/OpenWoW**:

1. PREQUEST ID: 4881 (http://wotlk.openwow.com/quest=4881) 
2. QUEST ID: 4966 (http://wotlk.openwow.com/quest=4966)
3. NPC1 ID *questgiver: 10638 (http://wotlk.openwow.com/npc=10638)
4. NPC2 ID *zespawnione npc: 10720 (http://wotlk.openwow.com/npc=10720)

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
https://s13.postimg.org/52rdw3aif/Wo_WScrn_Shot_101616_210621.jpg

**Comment by NoobSunwell** [comment]
Będzie naprawione po update.
