### ISSUE TITLE
[QUEST] Ravager Egg Roundup - wyświetlanie

### ISSUE THREAD

**Issue by nirvaaa** [NoobSunwell/Sunwell-BugTracker#169]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: http://wotlk.openwow.com/quest=9349

**Obecne działanie**: Nie wyświetla przy mobie dropiącym q item

**Oczekiwane działanie**: Wyświtlać, które moby dropią q item

**Co należy zrobić, aby odtworzyć ten błąd**: Zacząć q i najechać kursorem na wskazanego poniżej moba.

1. http://wotlk.openwow.com/npc=16932 - mob przy którym nie wyświetlany jest q item drop
2. http://wotlk.openwow.com/item=23217 - q item 
3. A poniżej 2 inne moby, ktore powinny dropic q item ale ja ani razu go nie wydropilem:
http://wotlk.openwow.com/npc=19189
http://wotlk.openwow.com/npc=16933

**Comment by NoobSunwell** [comment]
![image](https://cloud.githubusercontent.com/assets/22621466/19420377/b27d4218-93ea-11e6-8f08-b6f598e0df07.png)
![image](https://cloud.githubusercontent.com/assets/22621466/19420379/b8dd317c-93ea-11e6-9713-45db6cf68d3a.png)

Wyczyść cache.

**Comment by nirvaaa** [comment]
nie pokazałeś na screenach moba, o którym mówiłem i nie odniosłeś się do zerowego dropu.

**Comment by NoobSunwell** [comment]
Sry, źle odczytałem.

**Comment by NoobSunwell** [comment]
Wyświetlanie będzie poprawione po update (przypominam, o wyczyszczeniu cache).

Co do dropu: http://www.wowhead.com/item=23217/ravager-egg - z racji, że ten quest jest dostępny na globie - tego się trzymamy. W bazie jest odpowiednio: 20, 4, 1%.
