### ISSUE TITLE
[QUEST] The Sprouted Frond

### ISSUE THREAD

**Issue by Bainit123** [NoobSunwell/Sunwell-BugTracker#17]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:  Nie da się wziąć questa w tytule

**Obecne działanie**: Po wykonaniu questa The Shimmering Frond [http://www.wowhead.com/quest=931/the-shimmering-frond](url) nie jest dostępny następny quest z chaina. Zespawniony NPC (3 kwiatki) ma znak do oddania questa a po zagadaniu z nim mówi "Greetings" i nie ma żadnych opcji dialogowych.

**Oczekiwane działanie**: Cytując komentarz pod questem: "The Denalan [...] will spawn the Sprouted Frond and you can pick up the next quest The Shimmering Frond. Zespawnione Sprouted Frond powinny dać następny quest, obecnie tego nie robią. 

**Co należy zrobić, aby odtworzyć ten błąd**: 

1. Wykonać quest The Shimmering Frond (start w 35:28, Teldrassil).
2. Po oddaniu do Denalana zaczekać chwilę aż NPC użyje przyniesionego mu przedmiotu żeby zespawnić kwiatki.
3. Spróbować wziąć następny quest id tych kwiatków.

**Comment by NoobSunwell** [comment]
![image](https://cloud.githubusercontent.com/assets/22621466/19475541/f81f13a0-9534-11e6-8aca-24be5de0d31b.png)

Działa bez problemu.
