### ISSUE TITLE
 Jadefire Shadowstalker

### ISSUE THREAD

**Issue by Lilianka88** [NoobSunwell/Sunwell-BugTracker#171]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Moby, ktore nie uzywaja swojego skilla

**Obecne działanie**: 
Jadefire Shadowstalkerzy w krainie Felwood, nie uzywaja swojego skilla, tj. stealtha. Dodatkowo nie posiadaja nameplatow, dopiero po ich stargetowaniu, pomimo wlaczonej opcji nameplatow w blizzardowskiej wersji, nameplate sie pojawia ale jest tylko napisem, bez pokazywania paska hp moba

**Oczekiwane działanie**:  Jadefire Shadowstalker powinien chodzic w stealth mode az do zaatakowania gracza, badz bycia zaatakowanym (jak rowniez powinien posiadac poprawnie dzialajace nameplate'y)

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Udac się do krainy Felwood.
2. W celu odnalezienia mobow warto wziac q The Corruption of the Jadefire.
3. Odnalezc moby.

**Linki WoWHead/OpenWoW**:

1. http://wotlk.openwow.com/quest=4421 - q do wziecia
2. http://wotlk.openwow.com/npc=7110 - skille, ktorych powinny uzywac Jadefire Shadowstalkerzy
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
http://i.imgur.com/K807sSi.jpg
http://i.imgur.com/vqm6aM6.jpg

**Comment by NoobSunwell** [comment]
Będzie naprawione po update.
