### ISSUE TITLE
[QUEST]Scalewing Serpent

### ISSUE THREAD

**Issue by Ladarius** [NoobSunwell/Sunwell-BugTracker#172]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:Scalewing Serpenty w queście: Mok Nathal Treets, Blade's Edge Mountains.

**Obecne działanie**: Nie pokazuje przynależności do questa w UI.
**Oczekiwane działanie**: Po zaznaczeniu moba, powinno pokazywać, że należy on do danego questa.

**Co należy zrobić, aby odtworzyć ten błąd:**
1. Pójść do Blade Edge Mountains
2. Odnaleźć Wyrmcult Blackwhelp'sy

**Linki WoWHead/OpenWoW**:
http://www.wowhead.com/npc=20749/scalewing-serpent

GPS
<a href="http://pl.tinypic.com?ref=2ivimav" target="_blank"><img src="http://i63.tinypic.com/2ivimav.jpg" border="0" alt="Image and video hosting by TinyPic"></a>
<a href="http://pl.tinypic.com?ref=23has2d" target="_blank"><img src="http://i68.tinypic.com/23has2d.jpg" border="0" alt="Image and video hosting by TinyPic"></a>

**Comment by NoobSunwell** [comment]
Brak ID QItemow

**Comment by Xanador** [comment]
QID: http://wotlk.openwow.com/quest=10860
ItemID: http://wotlk.openwow.com/item=31671   ;     http://wotlk.openwow.com/item=31670

**Comment by NoobSunwell** [comment]
Będzie naprawione po update - przypominam o cache.
