### ISSUE TITLE
[QUEST] Wyrmcult Blackwhelp

### ISSUE THREAD

**Issue by Ladarius** [NoobSunwell/Sunwell-BugTracker#173]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:Wyrmcult Blackwhelp, Blades Edge Mountains

**Obecne działanie**: Whelpy czasem mają visual buga, który powoduje, że leżą na ziemi, choć są żywe.
**Oczekiwane działanie**: Powinny latać nad ziemią.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Pójść do Blade Edge Mountains
2. Odnaleźć Wyrmcult Blackwhelp'sy
3. 

**Linki WoWHead/OpenWoW**:
http://www.wowhead.com/npc=21387/wyrmcult-blackwhelp
1. 
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
<a href="http://pl.tinypic.com?ref=334kkzq" target="_blank"><img src="http://i67.tinypic.com/334kkzq.jpg" border="0" alt="Image and video hosting by TinyPic"></a>
<a href="http://pl.tinypic.com?ref=nqsims" target="_blank"><img src="http://i65.tinypic.com/nqsims.jpg" border="0" alt="Image and video hosting by TinyPic"></a>

**Comment by NoobSunwell** [comment]
Brak ID NPC i QItemow.

**Comment by NoobSunwell** [comment]
Będzie naprawione po update.
