### ISSUE TITLE
[QUEST] They Stole Me Hookah and Me Brews!

### ISSUE THREAD

**Issue by Ladarius** [NoobSunwell/Sunwell-BugTracker#174]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:Bloodmaul Skrimisher, jak i reszta ogrów w danej wiosce.

**Obecne działanie**: Nie pokazują przynależności do danego questa. They Stole Me Hookah and Me Brews!.

**Oczekiwane działanie**:Po zaznaczeniu mobka powinniśmy wiedzieć, że to właśnie z niego mamy zbierać quest itemy.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Wziąć questa [They Stole Me Hookah and Me Brews!]
2. Odnaleźć ogry.
3. 

**Linki WoWHead/OpenWoW**:
1.http://www.wowhead.com/quest=10542/they-stole-me-hookah-and-me-brews. 
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
<a href="http://pl.tinypic.com?ref=2h8232q" target="_blank"><img src="http://i67.tinypic.com/2h8232q.jpg" border="0" alt="Image and video hosting by TinyPic"></a>
<a href="http://pl.tinypic.com?ref=whfxqv" target="_blank"><img src="http://i65.tinypic.com/whfxqv.jpg" border="0" alt="Image and video hosting by TinyPic"></a>

**Comment by NoobSunwell** [comment]
Brak ID NPC i QItemow.

**Comment by Xanador** [comment]
NPC : http://wotlk.openwow.com/npc=19957  ;   http://wotlk.openwow.com/npc=21452
QID  : http://wotlk.openwow.com/item=30468

**Comment by NoobSunwell** [comment]
Informacja dodana do Brewmasterów. W innych mobkach nie ma lootu (w końcu item to Brew, więc dropi Brewmaster) - przypominam o cache.

Będzie po update.
