### ISSUE TITLE
Quest: Bounty on Garrick Padfoot

### ISSUE THREAD

**Issue by Lazybyku** [NoobSunwell/Sunwell-BugTracker#175]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Quest: Bounty on Garrick Padfoot, polegający na zabiciu "szefa wraz z obstawą" i zabrać jego głowę.

**Obecne działanie**: Mobek przy Garrick Padfoot, spokojnie przygląda się jak zabijamy Garricka Padfoota.

**Oczekiwane działanie**: Mob stojący obok Garricka Padfoota, tzw. "obstawa", powinien zagrować się zaraz po zaatakowaniu Garricka, co niestety, nie ma miejsca.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Iść do Elewyn Forrest.
2. Wziąć q Bounty on Garrick Padfoot
3. Zaatakować Garricka Padfoota.

**Linki WoWHead/OpenWoW**:

1. http://www.wowhead.com/quest=6/bounty-on-garrick-padfoot
2. https://www.youtube.com/watch?v=HviG0miDzaE - jak powinien dzialać q
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
http://i.imgur.com/bgM2SFv.jpg

**Comment by NoobSunwell** [comment]
Mechaniki frakcji w startowych lokalizacjach zmieniły się w patchu 3.3 - nie ma tam chain aggro, a 99% mobów jest neutral.

http://www.wowhead.com/forums&topic=134831/something-not-in-the-patch-notes
