### ISSUE TITLE
Quest: Princess Must Die!

### ISSUE THREAD

**Issue by Lazybyku** [NoobSunwell/Sunwell-BugTracker#176]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Quest: Princess Must Die!, polegający na zabiciu świnki z Elewynn Forrest.

**Obecne działanie**: Atakując Princess, dwie pozostałe świnie, przez blizzarda wyznaczone jako obstawa, się nie agrują.

**Oczekiwane działanie**: Przy zaatakowaniu Princesski, dwie pozostałe świnie powinny się zagrować na nas.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Udać się do Elewynn Forrest.
2. Wziąć q Princess Must Die!
3. Zaatakować Księżniczkę Świń (bez używania AoE)

**Linki WoWHead/OpenWoW**:

1. http://www.wowhead.com/quest=88/princess-must-die
2. https://www.youtube.com/watch?v=Lw5rUiNM7M4 - link do yt, jak powinien działać q
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
http://i.imgur.com/zL1GlsW.jpg

**Comment by NoobSunwell** [comment]
Mechaniki frakcji w startowych lokalizacjach zmieniły się w patchu 3.3 - nie ma tam chain aggro, a 99% mobów jest neutral.

http://www.wowhead.com/forums&topic=134831/something-not-in-the-patch-notes
