### ISSUE TITLE
Zbugowany drop z Prowler'ów

### ISSUE THREAD

**Issue by Lazybyku** [NoobSunwell/Sunwell-BugTracker#177]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Prowlery są to wilki występujące w krainie Elewynn Forrest, zwyczajne moby non-elite, non-rare.

**Obecne działanie**: Prowlery bardzo "bogato" wyrzucają z siebie drop, często obdarowując nas itemkami z Defias setu

**Oczekiwane działanie**: Wilki powinny rzucać drop adekwatny do swojego lvlu i zgodny z tym, co przypisal im blizzard.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Udać się do Elewynn Forrest, a dokładniej do Eastvale Logging Camp.
2. Zabić pare Prowlerów i zebrać z nich loot.
3. Udać się na ah i wszystko opylić -> cieszyć się szybko zarobionym goldem

**Linki WoWHead/OpenWoW**:

1. http://www.wowhead.com/npc=118/prowler - możliwy drop z wilków
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
http://i.imgur.com/0YJ4HqX.jpg

**Comment by NoobSunwell** [comment]
Będzie naprawione po update.
