### ISSUE TITLE
Essence of Wintergasp w Kalimdorze ?

### ISSUE THREAD

**Issue by Xanador** [NoobSunwell/Sunwell-BugTracker#178]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:
Buff z Wintergasp Battle załączył mi się w tej lokacji ( SS1 )

**Obecne działanie**:
Buff z Wintergasp Battle załączył mi się w tej lokacji ( SS1 )

**Oczekiwane działanie**: TU WPISZ JAK TO POWINNO WYGLĄDAĆ
Ten buff powinien tylko i wyłącznie działać na terenie Northrend .

**Co należy zrobić, aby odtworzyć ten błąd**:
1. Udać się we wskazane miejsce w Thousand Needles ( SS1 )

**Linki WoWHead/OpenWoW**:
1. http://wotlk.openwow.com/spell=57940
2. http://wotlk.openwow.com/spell=58045

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
http://imgur.com/a/j3Hnq

Zauważyłem tego buffa tylko w tym miejscu.

**Comment by NoobSunwell** [comment]
Będzie naprawione po update.
