### ISSUE TITLE
QUEST DUNGEON:  What Is Going On?

### ISSUE THREAD

**Issue by Xanador** [NoobSunwell/Sunwell-BugTracker#179]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:
 Brak spawnu wrogów.

**Obecne działanie**:
Po wzięciu questa nic się nie dzieje.

**Oczekiwane działanie**: TU WPISZ JAK TO POWINNO WYGLĄDAĆ
Po wzięciu questa ( http://wotlk.openwow.com/quest=3982 ) po chwili powinny rzucić się na mnie i NPC stojącego przy mnie 4 osobowa armia wrogich NPC ( Niestety nie wiem z jakich żołnierzy składa się ta armia, ale przypuszczam, że chodzi o tych żołnierzy: http://wotlk.openwow.com/?search=Anvilrage , nie wliczając nie elit i Capitana). Po chwili 15-25 sekund, powinna pojawić się kolejna grupa tych samych mobów. Po ubiciu obu grupek, powinniśmy móc oddać quest.

**Co należy zrobić, aby odtworzyć ten błąd**:
1. http://wotlk.openwow.com/quest=3981 Zrobić ten quest;
2. http://wotlk.openwow.com/quest=3982 wziąć ten quest.
3. Nic się nie dzieje.

**Linki WoWHead/OpenWoW**:
1. http://wotlk.openwow.com/quest=3982 Quest
2. http://wotlk.openwow.com/?search=Anvilrage

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
http://imgur.com/a/WNOEc

**Comment by Xanador** [comment]
Cytat z Wowhead " 
By Gambitthecajun on 07/20/2008 (Patch 2.4.3)
waves of elite soldiers enters the room. This might call a wipe if not threated properly. You might want to clear the hallway first of mobs before talking to Gorshak. When the troopers enters the room, have your warrior/priest/warlock fear them before they get in the room. Eliminate them one by one. CC the rest as your group can.

A second wave of elite guards will appear too and might do before you're not finished with the first ones."

**Comment by NoobSunwell** [comment]
Będzie naprawione po update. A bynajmniej będzie działało, bo nie znamy dokładnych spawnów, także dodałem te sugerowane + AI.
