### ISSUE TITLE
Zachowanie peta( Razormane Wolf ) moba ( Razormane Hunter )

### ISSUE THREAD

**Issue by Xanador** [NoobSunwell/Sunwell-BugTracker#18]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:
Pet( http://wotlk.openwow.com/npc=3939 ) nie atakuje gracza, który zaatakował moba ( http://wotlk.openwow.com/npc=3265 ). Powinien od razu rzucić się na gracza.
Warto zaznaczyć, że dzieje się to przy odległości około 12y+ od NPC.

**Obecne działanie**: 
Pet(Razormane Wolf) nie broni swojego właściciela tak jak powinien tj. nie atakuje gracza z odległości ~12y od swojego pana (Razormane Hunter) 

**Oczekiwane działanie**:
Zaraz po zaczęciu combatu z Razormane Hunter, jego pet Razormane Wolf, powinien zacząć nas atakować. 
**Co należy zrobić, aby odtworzyć ten błąd**:
1. Pójść do Thron Hill w The Barrens ( 57,24 )
2. Zaatakować z daleka moba o nazwie Razormane Hunter ( http://wotlk.openwow.com/npc=3265 )
3. Pet ( http://wotlk.openwow.com/npc=3265 ) nie reaguje, chyba, że podejdziemy za blisko ( około 12 yardów )

**Comment by Xanador** [comment]
@ EDIT 
# zapomniałem o dowodach http://imgur.com/a/9yQm4

**Comment by Rzuuf** [comment]
to samo dzieje się z innymi typami mobow np. Burning Blade Apprentice
dowód: https://www.youtube.com/watch?v=wXs0KcBzunM - sory za muza, zapomniałem, ze nagrywam z dzwiekiem xd
coordy :1.19 i dalej w jaskini
id npc: 3198

**Comment by NoobSunwell** [comment]
Będzie naprawione po update.
