### ISSUE TITLE
[Quest] Meat on the Hook

### ISSUE THREAD

**Issue by ShatteredGlassx** [NoobSunwell/Sunwell-BugTracker#180]
Obecne działanie: Po użyciu quest itema przy haku, Tu'u'gwar pojawia się natychmiastowo przy nas.

Oczekiwane działanie: Po użyciu quest itema Tu'u'gwar powinien płynąc w stronę haka, potem go okrążyć, aż w końcu złapać się na przynętę. Tak jak tutaj: https://www.youtube.com/watch?v=aSJuTb1toLA

Co należy zrobić, aby odtworzyć ten błąd:

1. Wziąć quest "Meat on the Hook
2. Pójść w wyznaczone miejsce
3. Użyć quest itemu.

**Linki WoWHead/OpenWoW**:

1. http://wotlk.openwow.com/quest=12017
2. http://wotlk.openwow.com/npc=26510
3. http://wotlk.openwow.com/item=35838

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
2713 941 0 571

**Comment by NoobSunwell** [comment]
Będzie naprawione po update.
