### ISSUE TITLE
[QUEST] Rescuing the Rescuers

### ISSUE THREAD

**Issue by Aezyn** [NoobSunwell/Sunwell-BugTracker#182]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: quest jak najbardziej można zrobić, ale wystarczy podejść do jednego uwięzionego i kliknąć 8x na quest item - zalicza instantowo, a nie powinno.

**Obecne działanie**: Istnieje możliwość wykonania questa na jednym uwięzionym Vrykulu.

**Oczekiwane działanie**: Trzeba uwolnić 8 więźniów, a nie jednego więc wystarczy sprawić, by "dzida" którą przybity jest Vrykul znikała po podniesieniu jej.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Wziąć quest od NPC Vice Admiral Keller w Valgarde w Howling Fjord.
2. Pójść w miejsce więźniów przybitych do ziemi dzidami.
3. Kliknąć 8x na jedną dzidę.

**Linki WoWHead/OpenWoW**:

1. http://www.wowhead.com/quest=11244/rescuing-the-rescuers

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
http://imgur.com/a/P9skF

**Comment by NoobSunwell** [comment]
Będzie naprawione po update.
