### ISSUE TITLE
[QUEST] There Exist No Honor Among Birds

### ISSUE THREAD

**Issue by Aezyn** [NoobSunwell/Sunwell-BugTracker#183]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: ptak, którym powinniśmy zbierać jajka po prostu nie lata. Można wykonać questa "na raty" skacząc po skałkach na sam dół i zaczynać od nowa jak się zrespią, ale nie tak to powinno wyglądać. Do tego nie jestem pewien, czy działają skille owego ptaka, ale raczej wątpię. 

**Obecne działanie**: Problem polega na tym, że nie można prawidłowo pozbierać jajek. Ptakiem, którym sterujemy po uzyciu quest itema nie można latać, a tylko i wyłącznie skakać (chyba nie chcemy na sunwellu skaczących ptaków, prawda?)

**Oczekiwane działanie**: Ptak, którym sterujemy powinien być zdolny do latania, a dodatkowo powinny działać 3 skille: Scavenge, Soar, Escape.

**Co należy zrobić, aby odtworzyć ten błąd**:
1. Wziąc quest od NPC Hidalgo w Explorers' League Outpost (Howling Fjord).
2. Udać się na miejsce w którym przejmujemy kontrolę nad ptakiem (te podane jako GPS).

**Linki WoWHead/OpenWoW**:

1. http://www.wowhead.com/quest=11470/there-exists-no-honor-among-birds
2. http://www.wowhead.com/spell=44422/scavenge
3. http://www.wowhead.com/spell=44423/soar
4. http://www.wowhead.com/spell=44424/escape

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
http://imgur.com/a/y1U3k

**Comment by NoobSunwell** [comment]
Będzie naprawione po update.
