### ISSUE TITLE
[NPC] Frigid Abomination Attacker

### ISSUE THREAD

**Issue by ShatteredGlassx** [NoobSunwell/Sunwell-BugTracker#184]
Opis**:

Obecne działanie: Po przejściu obok Frigid Abomination Attacker, NPC agruje się na nas, jednak gdy NPC gubi nas z targetu, a w pobliżu jest NPC Ruby Keeper, to przerzuca się na niego. Podchodząc do atakowanego przez Frigid Abomination Attacker'a, Ruby Keepera w celu zaliczenia questa "Return to the Earth", Ruby Keeper znika, a Frigid Abomination Attacker agruje się na nas nie zadając DMG, nie robiąc combatu, ale ślepo podążając za nami.

Oczekiwane działanie: 1. Frigid Abomination Attacker nie powinien agrować się na Ruby Keepera i go atakować, bo Ruby keeper jest martwy.
2. Frigid Abomination Attacker nie powinien nas śledzić po tym, jak użyliśmy quest itemu na Ruby Keeperze, powinien nam zadawać DMG i zgubić się po przejściu kilkunastu yardów - tak jak każdy normalny mobek, a on po prostu za nami chodzi i nie chce nas zostawić.
Screen: https://zapodaj.net/67eb7e91bbf15.jpg.html

Co należy zrobić, aby odtworzyć ten błąd:

1. Wziąć quest Return to the Earth
2. Przejść obok  Frigid Abomination Attacker, który znajduje się obok Ruby Keeper
3. Odejść od Frigid Abomination Attacker i doprowadzić do sytuacji, aby podczas powrotu przechodził obok Ruby Keeper'a
4. Użyć Quest item na Ruby Keeper 

**Linki WoWHead/OpenWoW**:

1. http://wotlk.openwow.com/npc=27530
2. http://wotlk.openwow.com/quest=12417
3. http://wotlk.openwow.com/npc=27531

Lokalizacja z koordynatów GPS (X, Y, Z, Map):
3648 757 82 571

**Comment by NoobSunwell** [comment]
Będzie naprawione po update.
