### ISSUE TITLE
[QUEST] Scare the Guano Out of Them!

### ISSUE THREAD

**Issue by Aezyn** [NoobSunwell/Sunwell-BugTracker#188]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: wszystkie przedmioty do questa można pozbierać używając quest item na jednym mobku, a więc bez dwóch zdań jest to błędem.

**Obecne działanie**: Po użyciu "Feknut's Firecrackers" pod mobem "Darkclaw Bat" poprawnie zlatuje na ziemie i zostawia quest item, ale myk polega na tym, że można zrobić to dziesięciokrotnie na tym samym nietoperzu.

**Oczekiwane działanie**: Poprawnie powinno wyglądać to tak, że 1 Bat = 1 Quest Item. Z tego co się dowiedziałem po zebraniu Quest Itema owy Darkclaw Bat nie znika tylko można go zabić, ale w żadnym razie nie powinno się móc zrobić tego questa wyłącznie na jednym nietoperzu.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Wziąć quest od NPC Engineer Feknut w Steel Gate (Howling Fjord).
2. Polecieć w poszukiwaniu moba "Darkclaw Bat".
3. Użyć 10x quest item pod jednym nietoperzem. 

**Linki WoWHead/OpenWoW**:

1. http://www.wowhead.com/quest=11154/scare-the-guano-out-of-them
2. http://www.wowhead.com/item=33129/feknuts-firecrackers
3. http://www.wowhead.com/npc=23959/darkclaw-bat
4. http://www.wowhead.com/item=33084/darkclaw-guano

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
http://imgur.com/a/D6TYv
http://imgur.com/a/hNO8k

**Comment by NoobSunwell** [comment]
Będzie naprawione po update.
