### ISSUE TITLE
[MECHANICS] NPC atakowani ze zbyt dużej odległości regenerują hp ciągle i resetują combat

### ISSUE THREAD

**Issue by turboszczur** [NoobSunwell/Sunwell-BugTracker#189]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Od czasu do czasu Npce które są atakowane ze znacznej odległości regenerują hp jakby były poza combatem. Jak pet lub ja wejdziemy w bliższy zasięg npc normalnie się agruje i przestaje regenerować hp. Błąd jest spotykany wszędzie, nagrałem przykładowy w outach.

**Obecne działanie**: Regen hp i brak combatu (reset).

**Oczekiwane działanie**: Powinien normalnie się combat załączać.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Pograć trochę jakimś dystansowcem i atakować z dużej odległości.
2. 
3. 

**Linki WoWHead/OpenWoW**:

1. http://wotlk.openwow.com/npc=21661
2. https://www.youtube.com/watch?v=_bp4_c4atzI&feature=youtu.be
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

http://imgur.com/a/yfymp

**Comment by NoobSunwell** [comment]
Kiedy był ten filmik nagrywany? Bo w tym miejscu nie mogę ani u siebie ani na serwerze tego odtworzyć.

**Comment by nirvaaa** [comment]
Myślałem, że wszyscy wiedzą o tym bugu. 
Noob to się dzieje bardzo często, magiem uderzając z fireballa w loch modan miałem to z co drugim mobem przy max zasięgu.

**Comment by turboszczur** [comment]
Nie zgłaszałem wcześniej tego bo myślałem że to ma związek z movemapami

**Comment by NoobSunwell** [comment]
Do sprawdzenia po update - występuje na serwerze - u mnie już tego nie ma. Możliwe, że problem się zmniejszył.

**Comment by turboszczur** [comment]
Póki co wydaje się działać dobrze, jeśli napotkam jakiś problem to nagram i wrzucę filmik.
