### ISSUE TITLE
[Movement] Niewidzialne ściany, NPC stoją w miejscu

### ISSUE THREAD

**Issue by Hehedzki** [NoobSunwell/Sunwell-BugTracker#19]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: NPC zawieszają się w powietrzu, wchodzą pod ziemię lub "skaczą" do połowy w ziemii. 

**Obecne działanie**: NPC i mobki zawieszają się w powietrzu, wchodzą pod ziemię lub "skaczą" do połowy w ziemii. To samo tyczy się mobków pullniętych ze skarpy, czy wprowadzonych do wody. http://i.imgur.com/LODWDyP.jpg

**Oczekiwane działanie**: Mobki powinny omijać skarpę, lub się po niej wspinać, npc nie powinny wpadać pod ziemię. Mobki w wodzie powinny pływać.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Przejść się po stormwind lub innym mieście, gdzie jest dużo chodzących npc
2. Pullnąć mobka ze skarpy

**Comment by NoobSunwell** [comment]
Są to pojedyncze przypadki. Należy podać ID takiego NPC jak i koordynaty, w których to nastąpiło.

**Comment by vadren** [comment]
Podaję:
NPC ID: 1504
Coordy w Tirisfal Glades między dwoma górkami: 28.7 56.4

NPC latał idąc z jednego wzgórza na drugie.

**Comment by vadren** [comment]
NPC ID: 1536 w Tirisfal Glades
Coordy: 53.4 68.1
W drodze z górki na podanych coordach w stronę Undercity NPC instantowo przesuwa się minimalne kawałki w lewo i prawo idąc prosto.

**Comment by Rzuuf** [comment]
npc id 3203 w Durotar
Coordy: 10.27
stoję na podanych coordach i atakuję mobka z dystansu, on wchodzi po niewidzialnych schodach, przechodzi przez pulke skalna i mnie bije

**Comment by NoobSunwell** [comment]
Po aktualizacji powinno być ok.

**Comment by Xanador** [comment]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: 
Moby jakby zatrzymują się na niewidzialnej ścianie. Dotyczy to wszystkich mobów znajdujących się w tamtej okolicy.

**Obecne działanie**: 
Mob nie potrafi podejść do mnie mimo, że nie ma między nami żadnej przeszkody.

**Oczekiwane działanie**: 
Mob powinien iść w linii prostej do mnie.

**Co należy zrobić, aby odtworzyć ten błąd**:
1. Iść do The Barrens do Blackthorn Ridge
2. Próbować kite'ować moby z okolicy : 41, 78
3. Moby powinny zatrzymywać się o ? Niewidzialną ścianę ?

**Linki WoWHead/OpenWoW**:
1. http://wotlk.openwow.com/npc=3459
2. http://wotlk.openwow.com/npc=3458
3. http://wotlk.openwow.com/npc=3457
4. http://wotlk.openwow.com/npc=3456

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:  SS 1
http://imgur.com/a/VOVqR

Film instruktażowy:  https://youtu.be/8ii7-2vx3u8

**Comment by NoobSunwell** [comment]
Wskazane zgłoszenia dotyczą tego samego problemu, temu oznaczyłem je jako duplikaty. Z racji, że te zgłoszenie (thx @Xanador ) jest najlepiej opisane - ustawiam jako główne.

**Comment by Xanador** [comment]
Teraz można podpisywać w ten sposób, czy też trzeba robić wall of tekst ? Jeśli tak, to poprawię.
Tutaj to samo, gdy podchodze do moba, atakuje mnie, jednak gdy chce ja chce odejść, mob stoi w miejscu.

GPS:   http://imgur.com/a/IusNk
Mob:   http://wotlk.openwow.com/npc=3374  ;   http://wotlk.openwow.com/npc=6668

**Comment by NoobSunwell** [comment]
Raczej bym stwierdził, że tego błędu nie trzeba więcej zgłaszać. Postaram się na tygodniu przejrzeć dokładnie ekstraktor MMap (bo przy wyłączonych movement działa dobrze).

**Comment by Xanador** [comment]
Zrozumiałem.

**Comment by NoobSunwell** [comment]
Niewidzialne ściany nie będą już problemem po update.
