### ISSUE TITLE
[Quest] Battery Recharging Blaster

### ISSUE THREAD

**Issue by Kougraa** [NoobSunwell/Sunwell-BugTracker#190]
**Opis**:  "Losowe" zaliczanie energii z questa.
https://youtu.be/P8NL6AIPKOc
https://youtu.be/FdioDM4lU44

**Obecne działanie**: Nie przy każdym użyciu qitmu pod koniec żywotności mobów, zalicza nam zebranie z nich energii.
**Oczekiwane działanie**: Przy każdym użyciu qitemu powinno zaliczyć graczowi zebranie energii z moba.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Wziąć quest u NPC
2. Odnaleźć Phase Hunter's
3. Użyć q itemu pod koniec zbicia mobka.

**Linki WoWHead/OpenWoW**:

1. http://www.wowhead.com/quest=10190/recharging-the-batteries
2. http://www.wowhead.com/npc=19578/bot-specialist-alley
3. http://www.wowhead.com/item=28369/battery-recharging-blaster

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
http://i.imgur.com/fQwADqg.jpg

Przy okazji - nie pokazuje przynależności do questa.
http://i.imgur.com/J0Par2E.jpg

**Comment by NoobSunwell** [comment]
Problem polegał na tym, że aggrowano petem. Będzie oczywiście naprawione po update.
