### ISSUE TITLE
[Quest] When the cows come home

### ISSUE THREAD

**Issue by Kougraa** [NoobSunwell/Sunwell-BugTracker#191]
**Opis**: Za pierwszym razem quest udało się wykonać. Jednak przy drugim podejściu krowa w pewnym momencie zatrzymuje się i nie udaje się wykonać zadania. 
W dodatku w chwili ataku mobów z każdej strony, krowa idzie nadal do przodu, pozostawiając gracza w tyle - co bardzo utrudnia przeprowadzenie NPC do wyznaczonego miejsca. Gracz samotnie wykonując questa nie dość, że musi uporać się z dużą ilością mobów, które atakują z każdej strony to w dodatku podążać za krową, aby jej czasem nie zgubić.  
https://youtu.be/1Y8sNGV0VdE
https://youtu.be/x7hU3BGY_Hw

**Oczekiwane działanie**: Krowa w chwili naszej konfrontacji z mobami powinna czekać do chwili utraty combatu oraz powinna doprowadzić nas do miejsca zakończenia questa.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Wziąć quest od NPC.
2. Podążać za krową.
3. 

**Linki WoWHead/OpenWoW**:

1. http://www.wowhead.com/quest=10337/when-the-cows-come-home
2. http://www.wowhead.com/npc=20415/bessy
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
http://i.imgur.com/xGgOzSy.jpg

**Comment by NoobSunwell** [comment]
Będzie poprawione po update.
