### ISSUE TITLE
[Quest] Destroy Naberius!

### ISSUE THREAD

**Issue by Kougraa** [NoobSunwell/Sunwell-BugTracker#192]
**Opis**: W chwili gdy gracz zbija (+,-) 50% hp Naberiu'sowi, ten rzuca chain, dzięki któremu kontroluje gracza na 10sekund prowadząc go w ciągle to samo miejsce, w tym czasie regenerując swoje hp na full.
Takim sposobem quest jest niewykonalny.
https://youtu.be/co13rT86o4w

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Wziąć quest od NPC.
2. Udać się w miejsce Naberiusa.
3. Próbować go zabić.

**Linki WoWHead/OpenWoW**:

1. http://www.wowhead.com/npc=19488/custodian-dieworth
2. http://www.wowhead.com/quest=10320/destroy-naberius
3. http://www.wowhead.com/npc=20483/naberius

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
http://i.imgur.com/2YMeWEv.jpg

Po wejściu do środka, nie ma możliwości wyjścia i ponownego wejścia do budynku poprzez zablokowane przejście.
https://youtu.be/gblRMquBAiI

**Comment by NoobSunwell** [comment]
Powinno być ok po update (nie będzie rzucał MC gdy walczy z nim jedna osoba).
