### ISSUE TITLE
[Movemapy] The Pit of Narjun.

### ISSUE THREAD

**Issue by kovaq** [NoobSunwell/Sunwell-BugTracker#193]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Do jaskini o nazwie The Pit of Narjun przenikaja moby z powierzchni, to jest Blighted Elk i Rabid Grizzly. Ponadto dosyc dziwna sytuacja bylo, ze 2 niedzwiedzie najpierw sie na mnie zagrowayl, a potem zgubily sciezke i wrocily grzecznie na powierzchnie. Gdy wrocilem by zrobic ss gpsu (mialem wylaczony program i nie zapisaly sie ssy) to te mobki juz poprawnie chodza po powierzchni. Niestety tylko te 2 udalo mi sie "wyprowadzic" na gore, reszta jest nie agrowalna.

**Obecne działanie**: Moby wpadaja do jaskini.

**Oczekiwane działanie**: Powinny chodzic po powierzchni.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Wejsc do The Pit of Narjun
2. Znalezc pierwsze lepsze moby nienalezace do tej lokacji.
3. 

**Linki WoWHead/OpenWoW**:

1. http://wotlk.openwow.com/npc=26616
2. http://wotlk.openwow.com/npc=26643
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
http://screenshooter.net/102844212/ynlgtul

Tak jak przy kazdym przypadku movemap, wole zglosic niz, zeby potem nie bylo o tym informacji.
Prosze rowniez o zwrocenie mi uwagi, jezeli myle pojecia movemap i vmap, probowalem sie z tego wyedukowac by, nie robic sobie wstydu, aczkolwiek dalej mam watpliwosci. ;)

**Comment by NoobSunwell** [comment]
Powinno być lepiej po update (miśka udało mi się wykryć w teksturach, elka już strzelałem po najbliższym).
