### ISSUE TITLE
[Quest] Bloody Imp-ossible!

### ISSUE THREAD

**Issue by Kougraa** [NoobSunwell/Sunwell-BugTracker#194]
**Obecne działanie**: Nie pokazuje przynależności moba do questa.
http://i.imgur.com/Xy9SJkr.jpg

**Oczekiwane działanie**: Po zaznaczeniu moba, powinno pokazywać, że należy on do danego questa.

**Linki WoWHead/OpenWoW**:

1. http://www.wowhead.com/quest=10924/bloody-imp-ossible
2. http://www.wowhead.com/npc=22479/sabaoth
3. http://www.wowhead.com/item=31813/warp-chaser-blood
4. http://www.wowhead.com/npc=18884/warp-chaser

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
http://i.imgur.com/47gKK4f.jpg

**Comment by NoobSunwell** [comment]
Brak ID NPC który ma pokazywać jak i Itemu, ktory ma być wyświetlany.

**Comment by Kougraa** [comment]
Poprawione

**Comment by NoobSunwell** [comment]
https://www.youtube.com/watch?time_continue=22&v=18-EQSrBCis

To nie błąd.
