### ISSUE TITLE
[quest] Venomhide Eggs (part 2 of 3)

### ISSUE THREAD

**Issue by MorgothPalantir** [NoobSunwell/Sunwell-BugTracker#195]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Chain quest na mounta Venomhide Ravasaur w Un'Goro Crater. Containery, które zawierają quest item są nieaktywne. Nie działa żaden container na mapie.

**Obecne działanie**: Containery zawierające item questowy są nieaktywne.

**Oczekiwane działanie**: Container powinien być używalny.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Wziąć pierwszą część chaina i ją wykonać (Toxic Tolerance - http://www.wowhead.com/quest=13850/toxic-tolerance )
2. Wziąć drugą część chaina
3. 

**Linki WoWHead/OpenWoW**:

1. http://www.wowhead.com/quest=13887/venomhide-eggs
2. http://www.wowhead.com/object=195022/venomhide-egg
3. http://www.wowhead.com/item=46364/venomhide-ravasaur-egg

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
https://imgur.com/a/RkdZl

**Comment by NoobSunwell** [comment]
Bo quest dodany w 3.2. Będzie zablokowany aż do 3.2 po update.
