### ISSUE TITLE
[QUEST] Gluttonous Lurkers

### ISSUE THREAD

**Issue by Aezyn** [NoobSunwell/Sunwell-BugTracker#197]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Wszystko co powinienem napisałem niżej. 

**Obecne działanie**: Po nakarmieniu "Lurking Basilisk" szczurem o nazwie "Zul' Drak Rat" bazyliszek prawidłowo dostaje aure jako "Fed" czyli nakarmiony, ale po zabiciu nie daje quest itemu.

**Oczekiwane działanie**: Wszystko tak jak wyżej - gdy bazyliszek jest nakarmiony szczurem po zabiciu go w loocie powinien widnieć quest item "Basilisk Crystal".

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Wziąć questa od NPC Alchemist Finklestein w shrine at Heb'Valok (Zul' Drak)
2. Iść w miejsce, gdzie respią się "Lurking Basilisk" i nakarmić je w/w szczurem "Zul' Drak Rat".
3. Zabić podczas trwania efektu "Fed" = nie będzie quest itemu, który powinien. 

**Linki WoWHead/OpenWoW**:

1. http://www.wowhead.com/quest=12527/gluttonous-lurkers
2. http://www.wowhead.com/npc=28145/lurking-basilisk

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
http://imgur.com/a/4uUqX

**Comment by NoobSunwell** [comment]
Będzie naprawione po update.

**Comment by NoobSunwell** [comment]
http://www.wowhead.com/quest=12527/gluttonous-lurkers#videos:id=76245

Nie tak ten Q działa. Należy 5x użyć "szczura" aby NPC się zmienił.
