### ISSUE TITLE
[Quest] It's a Fel Reaver, But with Heart completed.

### ISSUE THREAD

**Issue by Kougraa** [NoobSunwell/Sunwell-BugTracker#198]
**Opis**: Robot ani drgnie.
https://youtu.be/lMNA2WOkc-A

**Obecne działanie**: Po użyciu quest itemu, który ma za zadanie ożywić Scrapped Fel Reaver'a - nie dzieje się nic. NPC można ubić - zaliczając tym samym questa. Robot leniwie leży i ani drgnie.

**Oczekiwane działanie**: Robot po użyciu q itemu, mającego na celu ożywienie NPC, powinien wstać i dzielnie walczyć o przetrwanie.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Wziąć quest.
2. Udać się do Scrapped Fel Reaver'a.
3. Użyć quest itemu.

**Linki WoWHead/OpenWoW**:

1. http://www.wowhead.com/npc=20243/scrapped-fel-reaver
2. http://www.wowhead.com/quest=10309/its-a-fel-reaver-but-with-heart
3. http://www.wowhead.com/npc=19690/n-d-meancamp
4. http://www.wowhead.com/item=29447/fel-zapper

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
http://i.imgur.com/EYMgBnV.jpg

**Comment by NoobSunwell** [comment]
https://www.youtube.com/watch?v=b_yPpphm888

Zdziwisz się, ale on tak powinien działać :)

**Comment by Kougraa** [comment]
Hmm.. Nie rozumiem w takim razie dlaczego quest jest dla kilku osób :D no nic..
