### ISSUE TITLE
[Quest] A Heap of Ethereals

### ISSUE THREAD

**Issue by Kougraa** [NoobSunwell/Sunwell-BugTracker#199]
**Obecne działanie**:  Nie pokazuje dropu quest itemu z moba do questa.
http://i.imgur.com/o3S2Teo.jpg

**Oczekiwane działanie**: Po zaznaczeniu moba, powinno pokazywać, że quest item można dropnąć z owego mobka do danego questa.

Linki WoWHead/OpenWoW:

1. http://www.wowhead.com/quest=10262/a-heap-of-ethereals
2. http://www.wowhead.com/npc=19880/nether-stalker-khayji
3. http://www.wowhead.com/item=29209/zaxxis-insignia
4.  http://www.wowhead.com/npc=18875/zaxxis-raider
http://www.wowhead.com/npc=19642/zaxxis-stalker
http://www.wowhead.com/npc=20772/netherock

Lokalizacja z koordynatów GPS (X, Y, Z, Map):
http://i.imgur.com/067TRaC.jpg

**Comment by NoobSunwell** [comment]
https://youtu.be/Y4TDYqm44Z8?t=30s

To nie błąd.
