### ISSUE TITLE
QUEST: Burning Blade Medallion ( oraz ) Sting of the Scorpid

### ISSUE THREAD

**Issue by Xanador** [NoobSunwell/Sunwell-BugTracker#2]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: 
Brak informacji na temat quest itemu, czy dany mobek go dotyczy czy też nie.
Oczywiście, nie zawsze się to sprawdza.
Na razie złapałem to przy Questach:
Sting of the Scorpid: http://wotlk.openwow.com/quest=789 
NPC: http://wotlk.openwow.com/npc=3124  http://wotlk.openwow.com/npc=3281
ITEM: http://wotlk.openwow.com/item=4862
______________________________________________________________
Burning Blade Medallion: http://wotlk.openwow.com/quest=794 
NPC: http://wotlk.openwow.com/npc=3183
ITEM: http://wotlk.openwow.com/item=4859

**Obecne działanie**: 
Po najechaniu myszką na jakiegoś moba, którego to quest dotyczy w prawym dolnym rogu powinna pojawić się informacja o tym, że ten mob ma związek z questem np: że wypada z tego moba przedmiot.
Aktualnie wygląda to tak, że jest pare questów, które tą informację posiadają, jednakże można spotkać takie, które nie pokazują( patrz dwa wyżej ).  +  załączę SS.

**Oczekiwane działanie**: 
Po najechaniu myszką na moba powinniśmy otrzymać informację, że quest item powinien z niego wypaść. + Załączę SS

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Wziąć quest grając orkiem/trollem ( bo najszybciej ). http://wotlk.openwow.com/quest=794
2. Najechać myszką na moba, który powinien wydropić przedmiot potrzebny do ukończenia zadania ( http://wotlk.openwow.com/npc=3183 )
3. Zobaczyć w prawym dolnym rogu, że brakuje informacji na temat questa, że mob nie dropi przedmiotu. ( http://wotlk.openwow.com/item=4859 )

SS: http://imgur.com/a/6RtaA

**Comment by Xanador** [comment]
To samo jest przy queście: http://wotlk.openwow.com/quest=1516
NPC: http://wotlk.openwow.com/npc=3102
ITEM: http://wotlk.openwow.com/item=6640

**Comment by NoobSunwell** [comment]
Będzie naprawione po aktualizacji.

**Comment by NoobSunwell** [comment]
PS: Bym zapomniał - wymagane usunięcie Cache w tym przypadku.
