### ISSUE TITLE
QUEST: Fungal Spores

### ISSUE THREAD

**Issue by Xanador** [NoobSunwell/Sunwell-BugTracker#20]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: 
Po najechaniu myszką na grzyba brakuje informacji, że z niego można zebrać quest item.

**Obecne działanie**: 
Działa prawie poprawnie. Nawet grzyby są podświetlone i błyszczą. Nie ma informacji, że z grzybków wypada quest item.

**Oczekiwane działanie**: 
Po najechaniu myszką na grzyba powinna być informacja, że dotyczy questa.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Wziąć quest: http://wotlk.openwow.com/quest=848
2. Przejść się do "The Forgotten Pools" w The Barrens ( okolice 45,22 )
3. Najechać myszką na grzyba ( http://wotlk.openwow.com/object=3640 ) .
4. Spojrzeć, że nie ma informacji na temat przedmiotu, który powinniśmy móc zebrać ( http://wotlk.openwow.com/item=5012 ).

SS: http://imgur.com/a/rfeCl

**Comment by Xanador** [comment]
EDIT: Powinienem to umieścić https://github.com/NoobSunwell/Sunwell-BugTracker/issues/2  tutaj ?

**Comment by NoobSunwell** [comment]
![image](https://cloud.githubusercontent.com/assets/22621466/19286379/be5e0130-8ffd-11e6-923a-5e498c8b31bf.png)

![image](https://cloud.githubusercontent.com/assets/22621466/19286368/b39fe998-8ffd-11e6-8883-ee2e1a1985b9.png)

Proszę wyczyścić Cache podczas gry gra jest wyłączona.

Jak to nie zadziała, zrobić to ponownie po aktualizacji - u mnie działa bez zarzutu na realmie lokalnym.
