### ISSUE TITLE
[quest] An improper burial

### ISSUE THREAD

**Issue by turboszczur** [NoobSunwell/Sunwell-BugTracker#200]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Jaki klikamy q itema wystarczająco szybko to mamy syndrom ats (zalicza nam q wielokrotnie w zależności od kliknięć).

**Obecne działanie**: Jak użyjemy pochodni wystarczająco szybko to nam zaliczy 2-3 razy na jednym trupie.

**Oczekiwane działanie**: Powinna zaliczać 1 za każdego trupa.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Wziąść i zrobić questa
2. 
3. 

**Linki WoWHead/OpenWoW**:

1. http://wotlk.openwow.com/quest=10913
2. http://wotlk.openwow.com/item=31769
3. http://wotlk.openwow.com/npc=21859
4. http://wotlk.openwow.com/npc=21846

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

http://imgur.com/a/5jdVc

**Comment by NoobSunwell** [comment]
Będzie naprawione po update.
