### ISSUE TITLE
NPC Jangdor Swiftstrider - Missing Text.

### ISSUE THREAD

**Issue by Xanador** [NoobSunwell/Sunwell-BugTracker#201]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: 
" MISSING TEXT " u NPC.

**Obecne działanie**: 
Brakuje tekstu przy dialogu u NPC.

**Oczekiwane działanie**: 
NPC powinien mieć tekst, jak klikniemy na niego ppm.

**Co należy zrobić, aby odtworzyć ten błąd**:
1. Wcisnąć ppm na NPC.

**Linki WoWHead/OpenWoW**:
1. http://wotlk.openwow.com/npc=7854 NPC.
2. http://imgur.com/a/KhVAb

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
Nie potrzebne.

**Comment by NoobSunwell** [comment]
Będzie naprawione po update.
