### ISSUE TITLE
[Quest] Elemental Power Extraction

### ISSUE THREAD

**Issue by Kougraa** [NoobSunwell/Sunwell-BugTracker#202]
**Obecne działanie**:  Nie pokazuje, że mob jest potrzebny do wykonania questa.
http://i.imgur.com/0wBhVhm.jpg

**Oczekiwane działanie**: Po zaznaczeniu moba, powinno pokazywać, że jest potrzebny do wykonania danego questa.

**Linki WoWHead/OpenWoW**:

1. http://www.wowhead.com/quest=10226/elemental-power-extraction
2. http://www.wowhead.com/npc=19709/chief-engineer-trep
3. http://www.wowhead.com/item=28548/elemental-power
4. http://www.wowhead.com/object=183933/elemental-power

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
http://i.imgur.com/X9r3stL.jpg

**Comment by NoobSunwell** [comment]
https://www.youtube.com/watch?time_continue=21&v=u2dLIEg5sm8

To nie błąd.
