### ISSUE TITLE
[Quest] Bloodgem Crystals

### ISSUE THREAD

**Issue by Kougraa** [NoobSunwell/Sunwell-BugTracker#203]
**Obecne działanie**:  Nie pokazuje dropu quest itemu z moba do questa.

**Oczekiwane działanie**: Po zaznaczeniu moba, powinno pokazywać, że quest item można dropnąć z owego mobka do danego questa.

**Linki WoWHead/OpenWoW**:

1. http://www.wowhead.com/quest=10204/bloodgem-crystals
2. http://www.wowhead.com/npc=19469/magistrix-larynna
3. http://www.wowhead.com/npc=18855/sunfury-magister
4. http://www.wowhead.com/item=28452/bloodgem-shard

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
http://i.imgur.com/zD2bqsM.jpg

**Comment by NoobSunwell** [comment]
https://youtu.be/Ns0efjMi-7M?t=20s

To nie błąd.
