### ISSUE TITLE
[Quest] Flight of the Wintergarde Defender

### ISSUE THREAD

**Issue by ShatteredGlassx** [NoobSunwell/Sunwell-BugTracker#204]
Quest nie dziala, nie można go zaliczyć.

Obecne działanie: Po zabiciu Vengeful Geist, Trapped Wintergarde Villager ucieka, ale nie zalicza questa.

Oczekiwane działanie: Po ucieczce Trapped Wintergarde Villager powinien zaliczać quest. 

Co należy zrobić, aby odtworzyć ten błąd:

1. Wziąć quest Flight of the Wintergarde Defender
2. Udać się w miejsce GPS
3. Zabić Vengeful Geist, który znajduje się obok Trapped Wintergarde Vilager

Linki WoWHead/OpenWoW:

1. http://wotlk.openwow.com/quest=12237
2. http://wotlk.openwow.com/npc=27370
3. http://wotlk.openwow.com/npc=27359

Lokalizacja z koordynatów GPS (X, Y, Z, Map):
3686 -833 165 571

**Comment by NoobSunwell** [comment]
Brak ID NPC

**Comment by ShatteredGlassx** [comment]
Gotowe

**Comment by ShatteredGlassx** [comment]
Jest to bardzo ważny quest, bez którego nie można zrobić kolejnych 15-20 questów.

**Comment by NoobSunwell** [comment]
Źle wykonujesz questa - Twoim zadaniem w nim jest ratowanie "Helpless Villager" za pomocą grypha.

![image](https://cloud.githubusercontent.com/assets/22621466/19524974/ccc98da2-961f-11e6-9494-686fe142b01e.png)

Quest działa bez zarzutów.

**Comment by NoobSunwell** [comment]
Źle wykonujesz zadanie - musisz ratować "Helpless Villager"ów za pomocą grypha.

![image](https://cloud.githubusercontent.com/assets/22621466/19525053/08fd1438-9620-11e6-8f3c-a55dc38f5034.png)

![image](https://cloud.githubusercontent.com/assets/22621466/19525073/192f2ecc-9620-11e6-8d3a-1509cf6aae78.png)

**Comment by ShatteredGlassx** [comment]
Boże, beznadziejny Carbonite pokazywał mi inne miejsce i byłem pewien, że to ten quest w którym trzeba ratować ludzi w domach przed tymi Geistami, nawet nie zobaczyłem, że to ten quest z gryfem ~~.
