### ISSUE TITLE
[Quest] A Convincing Disquise

### ISSUE THREAD

**Issue by Kougraa** [NoobSunwell/Sunwell-BugTracker#205]
**Obecne działanie**: Nie pokazuje dropu quest itemu z moba do questa.

**Oczekiwane działanie**: Po zaznaczeniu moba, powinno pokazywać, że quest item można dropnąć z owego mobka do danego questa.

**Linki WoWHead/OpenWoW**:

1. http://www.wowhead.com/quest=10197/a-convincing-disguise
2. http://www.wowhead.com/item=28637/sunfury-guardsman-medallion http://www.wowhead.com/item=28635/sunfury-arcanist-robes
http://www.wowhead.com/npc=20134/sunfury-arcanist http://www.wowhead.com/npc=20135/sunfury-arch-mage
3. http://www.wowhead.com/npc=18850/sunfury-guardsman

[Rękawice pokazuje z jakiego moba dropnąć.]

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
http://i.imgur.com/Dg5jtQy.jpg

**Comment by NoobSunwell** [comment]
Będzie naprawione po update - przypominam o cache.
