### ISSUE TITLE
[quest]EVIL DRAWS NEAR

### ISSUE THREAD

**Issue by turboszczur** [NoobSunwell/Sunwell-BugTracker#207]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Oakun nie chce odebrać questa.

**Obecne działanie**: Npc Oakun nie chce odebrać questa którego zakończyliśmy i który jest complete.

**Oczekiwane działanie**: Po skończenie questa i przyniesieniu itema powienien go odebrać.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Wziąść i zrobić questa
2. 
3. 

**Linki WoWHead/OpenWoW**:

1. http://wotlk.openwow.com/quest=10925
2. http://wotlk.openwow.com/npc=22456
3. http://wotlk.openwow.com/item=31811

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

http://imgur.com/a/0WP6P

**Comment by NoobSunwell** [comment]
Nie wiem skąd masz questa o ID 10925 - on nie jest dostępny od żadnego z NPC. Za to quest: 10923 - jak najbardziej. I można było go oddać. 10925 nie jest ogólnie dostępny w grze.

**Comment by turboszczur** [comment]
https://github.com/NoobSunwell/Sunwell-BugTracker/issues/319

Chyba nie jestem jedyny który miał z tym problem. A co do id mogłem się pomylić, od teraz będę sprawdzał też przez carbonita.
