### ISSUE TITLE
[Quest] Information Gathering.

### ISSUE THREAD

**Issue by Kougraa** [NoobSunwell/Sunwell-BugTracker#209]
**Opis**: W queście przy pomocy quest itemu [Sunfury Disguise] powinno się móc przejść do Commandera w taki sposób, aby nic w około nie miało prawa nas nie zaatakować . Jednak tutaj pojawia się problem. Mianowicie - jeden Arcane Annihilator oraz Sunfury Technician, znajdują się w środku i w chwili wejścia do środka - atakują. Nie można przejść obok spokojnie. W chwili gdy nie atakujemy NPC, a także gdy zaatakujemy - przebranie traci swą moc i w żaden sposób nie możemy skończyć owego questa. Jednym sposobem na wykonanie questa jest to, aby wczesniej zbić Arcane Annihilatora jak i Sunfury Techniciana. NPC'ki, które wg mnie - nie powinny być nawet w owym miejscu.
Jeśli zacznie coś zadawać nam obrażenia - quest jest przerywany, a Commander bez końca będzie potrafił podążać za swoim targetem.

http://i.imgur.com/dLYAaUe.jpg
http://i.imgur.com/xAfYY91.jpg
http://i.imgur.com/kE7DCZJ.jpg

**Oczekiwane działanie**: W miejscu wykonywania questa nie powinno być w/w NPC, które uniemożliwiają spokojne wykonanie Questa "Information Gathering.".

**Linki WoWHead/OpenWoW**:

1. http://www.wowhead.com/quest=10198/information-gathering
2. http://www.wowhead.com/item=28607/sunfury-disguise
3. http://wotlk.openwow.com/npc=20218
4. http://wotlk.openwow.com/npc=18856

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Wziąć questa Information Gathering.
2. Użyć qitemu.
3. Iść w strone Commandera.

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
http://i.imgur.com/yBYxuYv.jpg

**Comment by NoobSunwell** [comment]
Annihilator będzie patrolował całe pomieszczenie zamiast stać przy wejściu.

Co do "Sunfury Technician" - nie mogłem to tam znaleźć. Z tego co widzę, to jest on na "wyspie" powyżej.
