### ISSUE TITLE
[NPC] Deathguard Terrence

### ISSUE THREAD

**Issue by kovaq** [NoobSunwell/Sunwell-BugTracker#21]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Przepraszam za nieprofesjonalizm, ale ten straznik najzwyczajniej w swiecie sie zjaral.
https://youtu.be/7Bk-Bg76QDw
To z serii "duperelkow" na wolna chwile ;)

**Obecne działanie**: Zapetlony smiech, slychac w calym brill.

**Oczekiwane działanie**: Jezeli w ogole powinien sie smiac to chyba raz...

**Co należy zrobić, aby odtworzyć ten błąd**:

1.  Znalezc go w brill, po smiechu bedzie to proste.
2. Postac chwile i posluchac.
3.

**Comment by NoobSunwell** [comment]
Proszę o podanie ID NPC z openwow/wowhead.

**Comment by kovaq** [comment]
http://wotlk.openwow.com/npc=1738 Mapa pokazuje dobrze go w brill, ale sam fakt, ze poprzez mape western to juz nie komentuje.

**Comment by vadren** [comment]
ID 1738 i tyle starczy, ale w sumie ten bug jest dosc znany z sunwella :P

**Comment by NoobSunwell** [comment]
Będzie naprawione po aktualizacji.
