### ISSUE TITLE
[Quest] The Flesh lies..

### ISSUE THREAD

**Issue by Kougraa** [NoobSunwell/Sunwell-BugTracker#211]
**Opis**: Zwłoki wydające dźwięki oraz brak przynależności do questa.

https://youtu.be/HBGXz3CERTQ

**Obecne działanie**: Podczas palenia ciał w queście, martwe już moby bez oznaczeń do questa, wydają dźwięk umierania.

**Oczekiwane działanie**: Brak odgłosów umierających NPC w chwili palenia ciał oraz oznaczenia zwłok do questa.

**Co należy zrobić, aby odtworzyć ten błąd**: 
1. Wziąć questa
2. Odnaleźć i użyć quest itemu na ciałach.

**Linki WoWHead/OpenWoW**:

1. http://www.wowhead.com/quest=10345/the-flesh-lies
2. http://www.wowhead.com/npc=20561/withered-corpse
3. http://www.wowhead.com/item=29473/protectorate-igniter

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
http://i.imgur.com/SOwXzyF.jpg

+długi czas oczekiwania na respawn ciał.

**Comment by NoobSunwell** [comment]
Będzie naprawione po update + skrócony respawn (faktycznie był za długi).
