### ISSUE TITLE
[Quest] Escape from the Staging Grounds

### ISSUE THREAD

**Issue by Kougraa** [NoobSunwell/Sunwell-BugTracker#212]
**Opis**: Bezbronny i niewinny NPC  zostaje bezwzględnie zamordowany przez Ethereum Gladiator'a.

http://i.imgur.com/iaDrEpq.jpg
http://i.imgur.com/ts5J5y6.jpg

**Obecne działanie**: W miejscu tak licznie wyposażonym w questy z błędami napotykam NPC z questem, który jest atakowany przez innego. Oczywiście wszystko byłoby OK, gdyby nie to, że MY, Ethereum'a Gladiatora nie mamy możliwości zaatakować. Quest możliwy do zdobycia, jednak nie możliwy do wykonania przez moba, z którym nie mamy możliwości konfrontacji. 

**Oczekiwane działanie**: Gracz powinien mieć możliwość walki z Ethereum Gladiator'em. Natomiast NPC z questem z eskortą nie powinien być ciągle atakowany przez Gladiatora.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Odnaleźć NPC.
2. [Ew. "próbować" go obronic]
3. 

**Linki WoWHead/OpenWoW**:

1. http://www.wowhead.com/quest=10425/escape-from-the-staging-grounds
2. http://www.wowhead.com/npc=20763/captured-protectorate-vanguard
3. http://www.wowhead.com/npc=20854/ethereum-gladiator

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
http://i.imgur.com/9T0N9ll.jpg

**Comment by NoobSunwell** [comment]
Gladiatora będzie można atakować po update.
