### ISSUE TITLE
[QUEST] Have You Ever Seen One of These?

### ISSUE THREAD

**Issue by ThePuppetMaster** [NoobSunwell/Sunwell-BugTracker#214]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:

 Quest: 9816
Mamy postawić klatkę na kamiennej płycie po czym mają z niej uciec murlocki.

**Obecne działanie**:

1. Dumnie stoi sobie NPC, którego nie powinno tam być.
2. Brak animacji wypuszczania murlocków z klatki.

**Oczekiwane działanie**:
https://www.youtube.com/watch?v=dn0zBRlwHvA
1. Brak NPC zamieszczonego na ss'ie podanym niżej
2. Animacja wypuszczania murlocków z klatki

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Postawić klatkę na kamiennej płycie.
2. Zobaczyć niepotrzebnego murlocka NPC, który jest friendly.

**Linki WoWHead/OpenWoW**:

1. http://www.wowhead.com/quest=9816/have-you-ever-seen-one-of-these

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

1. https://dl.dropboxusercontent.com/u/65775453/WoWScrnShot_101816_030304.jpg

**Comment by NoobSunwell** [comment]
https://www.youtube.com/watch?v=-r1I3eTbCX8 - 0:58 - jak widać one nie wychodzą "dosłownie" z klatki, tylko stoją przed nią przy rozpoczęciu skryptu.

Murlock musiał być pozostałością po poprzedniej osobie, która do robiła - będzie poprawione po update.
