### ISSUE TITLE
NPC Zorbin Fandazzle kupowanie/sprzedawanie.

### ISSUE THREAD

**Issue by Xanador** [NoobSunwell/Sunwell-BugTracker#216]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:
Zaraz gdy zagadamy do NPC możemy u niego sprzedawać, co jest nie poprawne.

**Obecne działanie**: TU WPISZ NA CZYM POLEGA PROBLEM
Gdy podchodzimy do NPC możemy u niego sprzedawać, mimo że nie powinniśmy.

**Oczekiwane działanie**: TU WPISZ JAK TO POWINNO WYGLĄDAĆ
Po rozmowie z NPC, ten powinien mieć opcje 2 questów
1. http://www.wowhead.com/quest=25466
2. http://www.wowhead.com/quest=25465
Dopiero po wykonaniu tych questów powinniśmy móc z nim rozmawiać. To znaczy, sprzedawać bądź kupować przedmioty.

**Co należy zrobić, aby odtworzyć ten błąd**:
1. Podejść do http://wotlk.openwow.com/npc=14637
2. Zobaczyć, ze od razu możemy sprzedawać i kupować przedmioty.

**Linki WoWHead/OpenWoW**:
1. http://www.wowhead.com/quest=25466  1szy quest 
2. http://www.wowhead.com/quest=25465  2gi quest
3. http://wotlk.openwow.com/npc=14637    NPC

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
GPS : http://imgur.com/a/QdYKX

**Comment by NoobSunwell** [comment]
Questy dodane w 4.0.3 - jakiś dowód, że na WotLK nie powinniśmy z nim gadać?

**Comment by NoobSunwell** [comment]
Będzie naprawione po update.
