### ISSUE TITLE
Outlands - przywitanie

### ISSUE THREAD

**Issue by nirvaaa** [NoobSunwell/Sunwell-BugTracker#217]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: zdjęcia mówią same za siebie :)

<a href='https://postimg.org/image/erdlusv25/' target='_blank'><img src='https://s14.postimg.org/bkj2b6am9/Wo_WScrn_Shot_101816_131604.jpg' border='0' alt='WoWScrnShot_101816_131604'/><br /><a target='_blank' href='https://postimage.org/'>upload image online</a><br /><br />
<a href='https://postimg.org/image/rx1w30bgd/' target='_blank'><img src='https://s14.postimg.org/94q0zff29/Wo_WScrn_Shot_101816_131550.jpg' border='0' alt='WoWScrnShot_101816_131550'/><br /><a target='_blank' href='https://postimage.org/'>image sharing</a><br /><br />

**Obecne działanie**: chyba powinno działać inaczej

**Comment by Xanador** [comment]
Dlaczego skasowałeś opis i zrobiłeś " to coś " ?

**Comment by nirvaaa** [comment]
bo więcej komentarza nie trzeba, żeby zrozumieć w czym rzeczy. Ale widzę, że nie dla wszystkich...

**Comment by Xanador** [comment]
Pokażę Ci coś.
https://github.com/NoobSunwell/Sunwell-BugTracker/issues/223
Zgłoszony przeze mnie bug. Sześć minut później mój bug już był naprawiony. Ciekawe, co nie ?

**Comment by nirvaaa** [comment]
nie pamiętam deva Xanadora - działaj zgodnie ze swoją funkcją i rób co Ci polecono

**Comment by kovaq** [comment]
Jak juz masz wkurwiac Nooba to rob to tak, bysmy my na tym nie tracili.
A tu masz jeszcze notke, ktorej pewnie nie czytales: http://forum.sunwell.pl/viewtopic.php?f=74&t=348

**Comment by NoobSunwell** [comment]
https://github.com/NoobSunwell/Sunwell-BugTracker/issues/227 - o wiele lepiej zgłoszone.

**Comment by nirvaaa** [comment]
Drogi kovaq`u co Ci do stania na straży humoru Nooba??
Czy lepiej, wg schematu po prostu, informacja jest oczywista po jednym zdjęciu.
Życzę powodzenia w waszych aplikacjach, ale nie popieram takiego poziomu "zdobywania plusów".

**Comment by kovaq** [comment]
Dbam o swoj (a przy okazji tez o innych) interes, doczytaj zdanie do konca. Jezeli utrudniasz robote, to nie dziw sie, ze reaguje. Pozatym jezeli chcesz pokazac jakim jestes rebelem to nie tu, naprawde ;)
