### ISSUE TITLE
[QUEST]  Red Snapper - Very Tasty! (początkowa lokacja)

### ISSUE THREAD

**Issue by nirvaaa** [NoobSunwell/Sunwell-BugTracker#218]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: http://wotlk.openwow.com/quest=9452

**Obecne działanie**: Angry murlock znika po ok. 10 sekundach.

**Oczekiwane działanie**: Murlock powinien nie znikać lub pozostać przez czas, w którym można go spokojnie zabić.

**Co należy zrobić, aby odtworzyć ten błąd**: Zacząć q i zarzucić sieć na red snappery, czasem pojawi się angry murlock.

1. http://wotlk.openwow.com/item=23654 - q item sieć
2. http://wotlk.openwow.com/npc=17102 ; http://www.wowhead.com/npc=17102/angry-murloc#drops - Angry murlock

<a href='https://postimg.org/image/fkupq1jff/' target='_blank'><img src='https://s9.postimg.org/q7oivgrkv/Wo_WScrn_Shot_101816_135946.jpg' border='0' alt='WoWScrnShot_101816_135946'/><br /><a target='_blank' href='https://postimage.org/'>photo share</a><br /><br />
<a href='https://postimg.org/image/dnlod7n8t/' target='_blank'><img src='https://s14.postimg.org/xuz45ikq9/Wo_WScrn_Shot_101816_135948.jpg' border='0' alt='WoWScrnShot_101816_135948'/><br /><a target='_blank' href='https://postimage.org/'>upload image online</a><br /><br />

**Comment by NoobSunwell** [comment]
Będzie naprawione po update.
