### ISSUE TITLE
[Quest] Shutting Down Manaforge Duro

### ISSUE THREAD

**Issue by Kougraa** [NoobSunwell/Sunwell-BugTracker#219]
**Opis**: Uciekające moby.
https://www.youtube.com/watch?v=WcPkUhws0ec

**Obecne działanie**: Quest wykonalny. Problem w tym, iż niektóre moby należące do questa, uciekają w przeciwną stronę. Tym sposobem quest jest łatwiejszy do wykonania.

**Oczekiwane działanie**: Moby, które się pojawiaja powinny kierować się w stronę Consoli.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Wziąć quest od NPC. 
2. Wydropić qitem z Overseera Theredisa.
3. Użyć Consoli.

**Linki WoWHead/OpenWoW**:

1. http://www.wowhead.com/quest=10338/shutting-down-manaforge-duro
2. http://www.wowhead.com/npc=19468/spymaster-thalodien
3. http://www.wowhead.com/npc=20218/sunfury-technician
4. http://www.wowhead.com/npc=20435/overseer-athanel
5. http://www.wowhead.com/item=29397/duro-access-crystal

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
http://i.imgur.com/aQ2NqEr.jpg

**Comment by NoobSunwell** [comment]
Sprawdź po update.
