### ISSUE TITLE
Itemy, których nasza postać nie może założyć nie są na czerwono

### ISSUE THREAD

**Issue by ellynd** [NoobSunwell/Sunwell-BugTracker#22]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:

**Obecne działanie**: Jeżeli wydropimy, chcemy kupić lub wybieramy jako nagrode jakiś item to bardzo często po najechaniu na niego jest widoczny jako możliwy do założenia.  Np. grając priestem gra mnie informuje, że mogę założyć mail albo leather a tak naprawdę nie mogę.

**Oczekiwane działanie**: Rodzaj przedmiotu, którego nie możemy założyć powinien być napisany na czerwono.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Wybrać dowolną klasę i najechać na item, którego nasza klasa nie może nosić.
2. 
3. 

Poniżej screeny:
http://i.imgur.com/AC2FS1d.jpg
http://i.imgur.com/slgaS2g.jpg
http://i.imgur.com/D3GJkZl.jpg

**Comment by Piootrek** [comment]
Spróbuj usunąć catche. U mnie wszystko jest ok 
http://i.imgur.com/T0tHAKs.jpg

**Comment by ellynd** [comment]
Kilkukrotne skasowanie cache i WTF pomogło :)
