### ISSUE TITLE
Sunfury nethermancer nie atakuje.

### ISSUE THREAD

**Issue by Kougraa** [NoobSunwell/Sunwell-BugTracker#220]
**Opis**: Mob nie atakuje.
https://youtu.be/AY-0XWdotFg

**Obecne działanie**:  Mob pomimo targetu - nie atakuje.

**Oczekiwane działanie**: Mob powinien atakować.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Odnaleźć Nethermancera
2. Stanąć blisko npc/zaatakować.
3. 

**Linki WoWHead/OpenWoW**:

1. http://www.wowhead.com/npc=20248/sunfury-nethermancer
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
http://i.imgur.com/pwmD45b.jpg

**Comment by NoobSunwell** [comment]
Będzie naprawione po update.
