### ISSUE TITLE
[Quest] Heated Battle

### ISSUE THREAD

**Issue by kovaq** [NoobSunwell/Sunwell-BugTracker#221]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Zaczalem robic q, ktory polega na biciu mobkow atakujacych posterunek u szczytu gory. 12 ghuli, 8 geistow - lajcik, chwila moment, dodatkowo wystarczy raz abilitem uderzyc moba i juz nasze npce robia reszte (ladnie zalicza). Problemem jest Frigid Abomination Attacker, ktory sie nie pojawia.
Majac w pamieci, ze na innych servach abomki gubily droge, pobieglem na dol i tam znalazlem brakujace moby. Co ciekawe, abomka ma zasieg patrolowania (nie lapie evade po odbiegnieciu dosc znacznego obszaru) w gore wniesienia az do jednostek walczacych. Kulturalnie sobie podprowadzilem jedna i tam lucznicy pomogli mi ja ubic. MImo to uwazam, ze abomka powinna miec w glowie zamysl podejscia samemu.

**Obecne działanie**: Abomka nie wchodzi na gore.

**Oczekiwane działanie**: Abomka powinna sama wbiegac i dolaczyc do walki.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Rozpoczac quest.
2. Bic sie "na gorze"
3. Po paru minutach mozna zauwazyc, ze mobki respia sie na gorze, ale nie abomki.
4. Majac w pamieci stare serwery, zbieglem na dol i tam znalazlem abomke do q.

**Linki WoWHead/OpenWoW**:

1. http://wotlk.openwow.com/quest=12448
2. http://wotlk.openwow.com/npc=27531
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
http://screenshooter.net/102844212/ffayllx gora.
http://screenshooter.net/102844212/hvpymnc dol. (w miejscu kursora stala druga abomka)

**Comment by kovaq** [comment]
Przy okazji:
http://screenshooter.net/102844212/xcigswx
Tutaj rowniez mobek przegrywa walke, co powoduje, ze moze go brakowac do q. (ten sam co wyzej na skrinie grzecznie stoi.)

**Comment by NoobSunwell** [comment]
Ruby Guardianów nie będzie atakował - naprawiałem w poprzednich zgłoszeniach.

Dodano 2 spawny - po 1 u Ally i Hordy z dosyć niskim respawnem (2 min).
