### ISSUE TITLE
[Mob] Emerald Skytalon

### ISSUE THREAD

**Issue by kovaq** [NoobSunwell/Sunwell-BugTracker#222]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:  http://screenshooter.net/102844212/spqeisf

**Obecne działanie**: Sowa niemoga znalezc drogi na dol.

**Oczekiwane działanie**: Jako flying mob powinna miec skypointy (czy jak tego nie nazwac) by moc zleciec na ziemie.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. podejsc w dane gpsu.
2. zaatakowac ranged atakiem pokazana sowe (u mnie akurat thrown)
3. obserwowac jej reakcje

**Linki WoWHead/OpenWoW**:

1. http://wotlk.openwow.com/npc=27244
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
http://screenshooter.net/102844212/spqeisf

**Comment by NoobSunwell** [comment]
Będzie naprawione po update.
