### ISSUE TITLE
QUEST: A Strange Request .

### ISSUE THREAD

**Issue by Xanador** [NoobSunwell/Sunwell-BugTracker#223]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Nie można oddać zadania .

**Obecne działanie**: 
Po wzięciu zadania powinniśmy go móc oddać do http://wotlk.openwow.com/npc=36208 ( jeśli używamy patcha 3.2.0), lub do http://wotlk.openwow.com/npc=3216 ( jeśli jesteśmy przed patchem 3.2.0 ). Jednakże nie możemy oddać zadania.

**Oczekiwane działanie**: TU WPISZ JAK TO POWINNO WYGLĄDAĆ
Po wzięciu http://www.wowhead.com/quest=3121, powinniśmy móc oddać zadanie do ( jesli mamy patch 3.2.0 ) http://wotlk.openwow.com/npc=36208 ( bądź jeśli jesteśmy przed 3.2.0 ) http://wotlk.openwow.com/npc=3216. 
Następnie ( jeśli mamy 3.2.0 ) http://wotlk.openwow.com/npc=36208 ( lub jeśli przed 3.2.0 ) http://wotlk.openwow.com/npc=3216 powinien kontynuować chain -> ( http://wotlk.openwow.com/quest=3122 ) tym zadaniem. 

**Co należy zrobić, aby odtworzyć ten błąd**:
1. Być hordą,
2. Udać się do Feralas.
3. Wziąć quest od: http://wotlk.openwow.com/npc=8115 
4. Nie ma się gdzie go oddać.

**Linki WoWHead/OpenWoW**:
1. NPC od startu chaina: http://wotlk.openwow.com/npc=8115
2. QUEST: http://www.wowhead.com/quest=3121
3. NPC przed 3.2.0 ( do którego powinniśmy móc oddać zadanie:http://wotlk.openwow.com/npc=3216
4. NPC po 3.2.0 którego prawidłowo nie ma: http://wotlk.openwow.com/npc=36208

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
http://imgur.com/a/2Py29

**Comment by NoobSunwell** [comment]
Będzie naprawione po update.
