### ISSUE TITLE
[Mob] Summoned Searing Totem

### ISSUE THREAD

**Issue by kovaq** [NoobSunwell/Sunwell-BugTracker#224]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: https://youtu.be/wYwRi5lUqDU Summoned Searing Totem stawiany przez Snowplain Shamana.

**Obecne działanie**: Searing Totem nie zadaje damage'u.

**Oczekiwane działanie**: Toten ten powinien castowac Sear (od nazwy) powodujace fire damage.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Zaatakowac kobolda shamana.
2. poczekac az odpali totem
3. obserwowac zachowanie totemu

**Linki WoWHead/OpenWoW**:

1. http://wotlk.openwow.com/npc=22895
2. http://wotlk.openwow.com/npc=27279
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
http://screenshooter.net/102844212/fcewuao

**Comment by NoobSunwell** [comment]
Będzie naprawione po update.
