### ISSUE TITLE
[Quest-EVENT]  "Let The Fires Come!"

### ISSUE THREAD

**Issue by Kougraa** [NoobSunwell/Sunwell-BugTracker#225]
**Opis**:  Nie widać, że przy pomocy wody gasimy pożar oraz bos, którego mamy zabić - nie pojawia się po ugaszeniu ognia.

**Obecne działanie**: 
https://youtu.be/kjeOFu2g1yY

**Oczekiwane działanie**: 
https://www.youtube.com/watch?v=TVkpTMXtuMA

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Wziąć quest.
2. Pobrać wodę i gasić ogień.
3. 

**Linki WoWHead/OpenWoW**:

1. http://www.wowhead.com/quest=12139/let-the-fires-come
2. http://www.wowhead.com/npc=23973/masked-orphan-matron
3. http://www.wowhead.com/npc=23543/shade-of-the-horseman

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
http://i.imgur.com/6g43Jok.jpg

**Comment by NoobSunwell** [comment]
ID Bossa?

**Comment by kovaq** [comment]
2:15 na filmiku kolezanka zfailowala event, ogien wypala miasto, ale gaszenie przebiega normalnie. Szczerze probowalem rowniez go zrobic, ale ja tu widze, ze ten ogien to conajmniej w 5 osob nalezy zrobic, bo sie rozchodzi bardzo szybko. 
http://wotlk.openwow.com/npc=23543 powinno byc to.
