### ISSUE TITLE
[QUEST] Show Gnomercy

### ISSUE THREAD

**Issue by nirvaaa** [NoobSunwell/Sunwell-BugTracker#226]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: http://wotlk.openwow.com/quest=9537

**Obecne działanie**: Idzie wzdłuż plaży i rzuca granty

<a href='https://postimg.org/image/yck92aezf/' target='_blank'><img src='https://s17.postimg.org/5zorbtt9b/Wo_WScrn_Shot_101816_170047.jpg' border='0' alt='WoWScrnShot_101816_170047'/><br /><a target='_blank' href='https://postimage.org/app.php'>how to take screenshots</a><br /><br />

**Oczekiwane działanie**: Powinien bić gracza i czasem rzucić granat

**Co należy zrobić, aby odtworzyć ten błąd**: Zacząć q, porozmawiać z npc, po czym stanie się agrysywny.

1. http://www.wowhead.com/npc=17243/engineer-spark-overgrind#screenshots - npc
2. http://wotlk.openwow.com/spell=7978 - ability throw dynamite

**Comment by NoobSunwell** [comment]
U mnie działa jak powinno. Sprawdź po update.
