### ISSUE TITLE
Fel Soldier - agresywny wojak!

### ISSUE THREAD

**Issue by Kougraa** [NoobSunwell/Sunwell-BugTracker#227]
**Opis**: Nieprzyjaźni żołnierze atakują wszystko i wszystkich!
https://youtu.be/mfpMTC2nsps

**Co należy zrobić, aby odtworzyć ten błąd**: 

1. Udać się przed portal w Hellfire Peninsula.
2. 
3. 

**Linki WoWHead/OpenWoW**:

1. http://www.wowhead.com/npc=18944/fel-soldier
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
http://i.imgur.com/NqnVNDi.jpg

**Comment by NoobSunwell** [comment]
Event powinien działać znacznie lepiej po update.
