### ISSUE TITLE
[Quest] Grulloc Has Two Skulls

### ISSUE THREAD

**Issue by Kougraa** [NoobSunwell/Sunwell-BugTracker#229]
**Opis**: Quest dla 5-ciu osób, oczywiście do wykonania. Jednak qitem może być pobrany jedynie przez jedną osobę z grupy.

**Oczekiwane działanie**: Qitem powinien być możliwy do podniesienia przez wszystkie osoby z grupy.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Przynajmniej 2 graczy musi wziąć qest.
2. Wspólnie odnaleźć i zabić Grulocca.
3. Próbować podnieść quest item po wcześniejszym podniesieniu przez innego gracza.

**Linki WoWHead/OpenWoW**:

1. http://www.wowhead.com/quest=10995/grulloc-has-two-skulls
2. http://www.wowhead.com/item=32379/grullocs-dragon-skull
3. http://wotlk.openwow.com/npc=20216

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
http://i.imgur.com/sSzy5zA.jpg

**Comment by NoobSunwell** [comment]
Będzie naprawione po update.
