### ISSUE TITLE
MoveMaps - Devouring Ectoplasm - 3638

### ISSUE THREAD

**Issue by Xanador** [NoobSunwell/Sunwell-BugTracker#23]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: 
Mob nie potrafi przebiec przez płytką wodę. Przez co wszystkie klasy muszą bić go w ręcz.

**Obecne działanie**:
Mob nie reaguje na ataki dystansowe.

**Oczekiwane działanie**:
Mob powinien ruszyć w kierunku atakującego.

**Co należy zrobić, aby odtworzyć ten błąd**:
1. Wejść do Wailing Caverns .
2. Znaleźć Coord  51.54 ( po prostu proszę iść przed siebie )
3. W końcu traficie na moba o nazwie Devouring Ectoplasm, stojącego przy ścianei po prawej stronie ( patrząc od strony,jakbyście biegli do wejścia do instancji ).
4. Spróbować go zabić z daleka. Nie możliwe ( chyba że jednym spelem zrobisz overkill. )

Dowód: https://www.youtube.com/watch?v=r5GzEVPdXYw

**Comment by NoobSunwell** [comment]
Brakuje ID NPC

**Comment by Xanador** [comment]
Jest w tytule, ale racja, powinno być odrobinę czytelniej, więc: http://wotlk.openwow.com/npc=3638

**Comment by NoobSunwell** [comment]
Po aktualizacji powinno być ok.
