### ISSUE TITLE
[Quest] Maggoc's Treasure Chest

### ISSUE THREAD

**Issue by Kougraa** [NoobSunwell/Sunwell-BugTracker#230]
**Opis**: Quest dla 5-ciu osób, oczywiście do wykonania. Jednak qitem może być pobrany jedynie przez jedną osobę z grupy.

**Oczekiwane działanie**: Qitem powinien być możliwy do podniesienia przez wszystkie osoby z grupy.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Przynajmniej 2 graczy musi wziąć qest.
2. Wspólnie odnaleźć i zabić Maggoca.
3. Próbować podnieść quest item z moba po wcześniejszym podniesieniu przez innego gracza.

**Linki WoWHead/OpenWoW**:

1. http://www.wowhead.com/quest=10996/maggocs-treasure-chest
2. http://www.wowhead.com/item=32380/maggocs-treasure-chest
3. http://wotlk.openwow.com/npc=20600

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
http://i.imgur.com/aFtuwJ8.jpg

**Comment by NoobSunwell** [comment]
Będzie naprawione po update.
