### ISSUE TITLE
[quest] stopping the spread

### ISSUE THREAD

**Issue by turboszczur** [NoobSunwell/Sunwell-BugTracker#232]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Trupy nie wiedzą że są martwe i mają hp.

**Obecne działanie**: Trupy które palimy mają normalne hp jakby żyły.

**Oczekiwane działanie**: Powinny mieć 0 hp i być trupami.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Wziąść i zrobić questa
2. 
3. 

**Linki WoWHead/OpenWoW**:

1. http://wotlk.openwow.com/npc=18240
2. http://wotlk.openwow.com/quest=9874
3. https://www.youtube.com/watch?v=slfnAwharIA

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

http://imgur.com/a/ZkYQG

**Comment by turboszczur** [comment]
Te trupy które są pod wodą nie zaliczają nam (te ze screenów, bo inne spod wody zaliczają).

**Comment by turboszczur** [comment]
Z tym nie zaliczaniem to kwestia odległości, możemy itemu użyć z większej odległości i nie zalicza a jak podejdziemy blisko to zalicza wtedy.

**Comment by NoobSunwell** [comment]
Z zaliczaniem na zasięg - taki jest po prostu item - szuka w obszarze, nie patrzy na target.

Co do śmierci - będzie naprawione po update.
