### ISSUE TITLE
[Mob] Commander Jordan

### ISSUE THREAD

**Issue by kovaq** [NoobSunwell/Sunwell-BugTracker#235]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Znalazlem blizniaki. http://screenshooter.net/102844212/hvrthxe

**Obecne działanie**: Podwojony mob.

**Oczekiwane działanie**: Powinien byc 1.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Odwiedzic baraki w Nowym Hearthglen.
2. 
3. 

**Linki WoWHead/OpenWoW**:

1. http://wotlk.openwow.com/npc=27237
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
http://screenshooter.net/102844212/kmsaion

**Comment by NoobSunwell** [comment]
Będzie naprawione po update.
