### ISSUE TITLE
[NPC] Forsaken Prisoner

### ISSUE THREAD

**Issue by kovaq** [NoobSunwell/Sunwell-BugTracker#237]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Wydaje mi sie, ale martwy ziomek powinien lezec. Szczegolnie ze "fabularnie" jest torturowany, co by sugerowalo raczej pozycje przywiazanego do stolu. Dodatkowo panowie pullneli sie na alianckiego kolego i bili go jako dead.

Kojarze taki fakt w Scarlet Monastery - Cementary Quarter jest boss przy ktorym lezy model undeada na stole, moze warto z niego skorzystac?

**Obecne działanie**: Trupy stoja i moga bic innych.

**Oczekiwane działanie**: Powinny lezec jako martwe - z animacja przypietych do stolu.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Zejsc do podziemi barakow w Nowym hearthglen.
2. 
3. 

**Linki WoWHead/OpenWoW**:

1. http://wotlk.openwow.com/npc=27400
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
http://screenshooter.net/102844212/ircxwqf

**Comment by NoobSunwell** [comment]
Będzie naprawione po update.
