### ISSUE TITLE
[Quest] Reclusive Runemaster

### ISSUE THREAD

**Issue by kovaq** [NoobSunwell/Sunwell-BugTracker#238]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Po pokonaniu moba (zbija sie go podajze do 25% hp) dostaje on banke dzialajaca jak stun i zaczyna glosic kwestie. Tutaj banka dziala tylko jako root i zdziwilem sie niemilosiernie jak mi wyplacil liscia w cricie za pol zycia.
http://screenshooter.net/102844212/hotcoes

**Obecne działanie**: Mob bije pomimo banki, ktora powinna go stunowac, nie rootowac.

**Oczekiwane działanie**: Mob nie powinien sieknac mnie z kopyta bedac juz w dialogu, na stunie (ktory jest rootem)

**Co należy zrobić, aby odtworzyć ten błąd**:

1. wziac q, dojsc na miejsce
2. pokonac dregmara
3. podejsc gdy jest w bance i wyglasza kwestie.

**Linki WoWHead/OpenWoW**:

1. http://wotlk.openwow.com/quest=12150
2. http://wotlk.openwow.com/npc=27003
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
http://screenshooter.net/102844212/kfrqofc

**Comment by NoobSunwell** [comment]
Będzie naprawione po update.
