### ISSUE TITLE
Fire (ognisko)

### ISSUE THREAD

**Issue by Valleige** [NoobSunwell/Sunwell-BugTracker#24]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Wiem, że jest to blachy bug, ale skoro interesują was nawet te najmniejsze to prosze. Otóż ognisko zadaje dmg dość daleko od ognia co widać na zdjęciu: http://imgur.com/YSwior2.

**Obecne działanie**: Zbyt duży obszar w jakim jest zadawany dmg.

**Oczekiwane działanie**: Zmniejszenie tego obszaru.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Ja sprawdzałem to na ognisku w Coldridge Valley, ale myślę, że na pierwszym lepszym tak samo to działa.
2. 
3. 

Thoridan/Valleige

**Comment by NoobSunwell** [comment]
Jakiś dowód na to, że powinien być mniejszy zasięg?

**Comment by nirvaaa** [comment]
https://s11.postimg.org/qxbfw3jcj/image.jpg

**Comment by Mithras2801** [comment]
http://www.wowhead.com/spell=818/cooking-fire
http://wowwiki.wikia.com/wiki/Cooking_Fire

**Comment by NoobSunwell** [comment]
Zachowanie jest poprawne. Wyjaśnienie:

http://wotlk.openwow.com/spell=7897/flames - ten spell jest odpowiedzialny za zadawanie DMG. Radius = 2y - to znaczy, że w taki zasięgu od obiektu mogą być zadawane obrażenia.

![image](https://cloud.githubusercontent.com/assets/22621466/19412318/8a1825fe-9313-11e6-8507-de8ae9c38bb9.png)

Na screenie widać moją postać i mobka - dzieli nas odległość 5y. Ognisko jest w środku (liczę tu punkt środkowy ogniska). Odległość na której jestem jest maksymalną.
