### ISSUE TITLE
[Quest] The Plume of Alystros

### ISSUE THREAD

**Issue by kovaq** [NoobSunwell/Sunwell-BugTracker#240]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Po uzyciu skytalon molts (q item) ptak ladnie budzi sie do zycia, z niespotykana przezemnie wczesniej animacja, lecz niestety nie aggruje sie na nas, przez co niektore klasy moga miec problem ze sciagnieciem go. (mi sie udalo na pixel znalezc range dla throwna)

**Obecne działanie**: Po przebudzieniu Alystros nie aggruje sie na przeciwnika.

**Oczekiwane działanie**: Zaraz po przebudzeniu Alystros powinien na nas zleciec.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Wziac Q, przejsc do lokacji Emerald Dragonshrine.
2. Uzyc q itemu by obudzic Alystrosa.
3. Obserwowac jego zachowanie.

**Linki WoWHead/OpenWoW**:

1. http://wotlk.openwow.com/quest=12456
2. http://wotlk.openwow.com/item=37881
3. http://wotlk.openwow.com/npc=27249

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
http://screenshooter.net/102844212/dbhffpc

**Comment by NoobSunwell** [comment]
Dziwne, bo gdzie bym nie stał na ziemi koło niego, to zawsze do mnie zleci po użyciu QItema.
