### ISSUE TITLE
[Quest] Sarathstra, Scrouge of the North.

### ISSUE THREAD

**Issue by kovaq** [NoobSunwell/Sunwell-BugTracker#241]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Do momentu zlotu wszystko wygladalo plynnie i przyjemnie. Niestety Smoczyca nie zleciala do konca na ziemie, co uniemozliwilo nam normalne jej bicie. Jezeli normalnym mozna nazwac nasze party ;p
Generalnie smok ani chwili nie spedzil na ziemi, tak jakby mial pod soba wieczny podest, probowalem go wprowadzic na palisade, samemu na nia wejsc by byc wyzej etc, potem agro przebil Aezyn i znalazl miejsce gdzie wgl mozna bylo ja bic, jak na klipie.

**Obecne działanie**: Sarathstra nie laduje na ziemi.

**Oczekiwane działanie**: Powinna zrownac sie z tekstura by dalo sie ja normalnie "encounterowac"

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Wziac q od Rokhana, zagadac z nim by zwabil Sarathstre.
2. Sarathstra zleci, ale nie tak jak trzeba, to trzeba widziec samemu.
3. 

**Linki WoWHead/OpenWoW**:

1. http://wotlk.openwow.com/quest=12097
2. http://wotlk.openwow.com/npc=26858
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
http://screenshooter.net/102844212/vaurqsf

**Comment by kovaq** [comment]
https://youtu.be/IHu9mzk1zvA oczywiscie zapomnialem...

**Comment by NoobSunwell** [comment]
Będzie naprawione po update.
