### ISSUE TITLE
[QUEST] Convocation at Zol'Heb

### ISSUE THREAD

**Issue by Aezyn** [NoobSunwell/Sunwell-BugTracker#242]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Po użyciu quest itema "z nieba" nie spada mob, który powinien się zrezpawnić.

**Obecne działanie**: Po użyciu quest itema w wyznaczonym do tego miejscu, a konkretnie Convocation Summonig Circle w Zul' Drak nie pojawia się mob "Prophet of Akali".

**Oczekiwane działanie**: Po użyciu quest itema z nieba powinien spadać meteoryt z którego wyłania się Prophet of Akali (w linkach dodałem link z youtube jak powinien wyglądać quest).

**Co należy zrobić, aby odtworzyć ten błąd**: 

1. Wziąć quest od NPC Har'koa w Zim'Torga.
2. Udać się w miejsce zwanym Convocation Summonig Circle w Zul'Drak.
3. Użyć quest itemu.

**Linki WoWHead/OpenWoW**:

1. http://www.wowhead.com/quest=12730/convocation-at-zolheb
2. http://www.wowhead.com/item=39566/prophet-of-akali-convocation
3. http://www.wowhead.com/npc=29028/prophet-of-akali
4. https://www.youtube.com/watch?v=iEGiWE9TerE

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
http://imgur.com/a/hoDnV

**Comment by NoobSunwell** [comment]
Będzie naprawione po update.
