### ISSUE TITLE
[Quest] Wrangle more aether rays!

### ISSUE THREAD

**Issue by Kougraa** [NoobSunwell/Sunwell-BugTracker#243]
**Opis**:  Moby po złapaniu nie zgadzają się na podążanie za graczem.
https://youtu.be/tHJ5lkBidVk

**Obecne działanie**: Moby, które należą do questa - w chwili złapania nie podążają za graczem.

**Oczekiwane działanie**: Złapane moby powinny podążać za graczem w chwili wykonywania questa.
https://www.youtube.com/watch?v=09xivkQeDBw

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Wziąć questa od npc w Blade Edge Mountains.
2. Znaleźć moby do questa.
3. Złapać je przy pomocy qitemu.

**Linki WoWHead/OpenWoW**:

1. http://www.wowhead.com/quest=11066/wrangle-more-aether-rays
2. http://www.wowhead.com/npc=23343/wrangled-aether-ray
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
http://i.imgur.com/kIoUiIN.jpg

**Comment by NoobSunwell** [comment]
Będzie naprawione po update.
