### ISSUE TITLE
QUEST:  Cleansing Witch Hill

### ISSUE THREAD

**Issue by Xanador** [NoobSunwell/Sunwell-BugTracker#244]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: 
Problem z mobem

**Obecne działanie**: 
Używamy quest itemu, przywołujemy moba do zabicia, jednak nie możemy go z w żaden sposób zranić.

**Oczekiwane działanie**: TU WPISZ JAK TO POWINNO WYGLĄDAĆ
Po użyciu http://wotlk.openwow.com/item=33113 , prawidłowo przywołuje nam http://wotlk.openwow.com/npc=23864 . Powinniśmy móc atakować go z auto ataków, zaklęć i takich tam. 

**Co należy zrobić, aby odtworzyć ten błąd**:
1. Wykonać :http://wotlk.openwow.com/quest=11180
2. Wykonać :http://wotlk.openwow.com/quest=11181
3. Spróbować wykonać :http://wotlk.openwow.com/quest=11183 ( zbugowany quest )

**Linki WoWHead/OpenWoW**:
1. QUEST: http://wotlk.openwow.com/quest=11183
2. MOB DO QUESTA: http://wotlk.openwow.com/npc=23864 
3. Q ITEM: http://wotlk.openwow.com/item=33113
4. NPC Z QUESTEM: http://wotlk.openwow.com/npc=23843
**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
http://imgur.com/a/ISGX7

Jak to działa tak ogółem: https://www.youtube.com/watch?v=-SVc5-ueX20

**Comment by NoobSunwell** [comment]
Będzie naprawione po update.
