### ISSUE TITLE
[quest] what book ? i dont see any book

### ISSUE THREAD

**Issue by turboszczur** [NoobSunwell/Sunwell-BugTracker#245]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Nie można atakować npców do questa.

**Obecne działanie**: Jak próbojemy zaatakować npce do questa pisze you cannot attack that target.
**Oczekiwane działanie**: Powinno móc się ich zaatakować.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Wziąśći zrobić questa.
2. 
3. 

**Linki WoWHead/OpenWoW**:

1. http://wotlk.openwow.com/quest=10231
2. http://wotlk.openwow.com/npc=19720
3. http://wotlk.openwow.com/npc=19725
4. http://wotlk.openwow.com/npc=19726

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

http://imgur.com/a/iTdsV

**Comment by NoobSunwell** [comment]
Będzie naprawione po update.
