### ISSUE TITLE
[quest] a necessary distraction

### ISSUE THREAD

**Issue by turboszczur** [NoobSunwell/Sunwell-BugTracker#247]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Demon nas atakuje a q item nie działa.

**Obecne działanie**: Demon nas atakuje, a q item nie chce zadziałać.

**Oczekiwane działanie**: Demon powinien być uwięziony a po użyciu q itema powinno go uwolnić. Nie powinien nas atakować dopóki nie zostanie uwolniony.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Wziąć i próbować zrobić questa
2. 
3. 

**Linki WoWHead/OpenWoW**:

1. http://www.wowhead.com/quest=10688/a-necessary-distraction#videos
2. http://wotlk.openwow.com/item=30811
3. https://www.youtube.com/watch?v=1pTminRkW68
4. http://wotlk.openwow.com/npc=21892

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

http://imgur.com/a/gVhdB

**Comment by NoobSunwell** [comment]
Będzie naprawione po update.

**Comment by turboszczur** [comment]
Zanim użyłem q itema (nie miałem go jeszcze) npc sunfury warlock zaatakowali zbiorowo demona. Zrobił się także jakiś dziwny pull (10-15 mobków ale nie zdążyłem tego nagrać). Demon powinien być w tej dziwnej formie i nie powinni go wtedy atakować jeszcze.



http://imgur.com/a/mSB6R

https://www.youtube.com/watch?v=QAxaZ0IQOD0&feature=youtu.be

http://wotlk.openwow.com/npc=21503

**Comment by NoobSunwell** [comment]
Powinno być lepiej po update - zapomniałem o fladze do braku możliwości atakowania przy resecie NPC.
