### ISSUE TITLE
[NPC] Xink's Shredder

### ISSUE THREAD

**Issue by ShatteredGlassx** [NoobSunwell/Sunwell-BugTracker#248]
Obecne działanie: 1. Jeżeli użyjemy quest item, który odpala Xink's Shredder'a, ale do niego nie wsiądziemy, to nie znika po 2min.
2. Jezeli nikogo nie mamy na targecie, to skill Twisting Blade zadaje nam DMG, naszej postaci, a nie Shredderowi.

Oczekiwane działanie: 1. Po 2min Xink's Shredder powinien zniknąć.
2. Skill Twisting Blade nie powinien nas bić.

Co należy zrobić, aby odtworzyć ten błąd:

1. Wziąć quest Lumber Hack
2. Pójść w wyznaczone miejsce do zrobienia questa
3.1 Użyć quest item i poczekać 2min
3.2 Użyć skilla pod "1"
**Linki WoWHead/OpenWoW**:

1. http://wotlk.openwow.com/spell=47938
2. http://wotlk.openwow.com/npc=27061
3. http://wotlk.openwow.com/item=36734
4. http://wotlk.openwow.com/quest=12050

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
4822 659 162 571

**Comment by NoobSunwell** [comment]
Jakiś dowód co do zanikania po 2 minutach?

**Comment by NoobSunwell** [comment]
Pierwsza umiejętność będzie naprawiona po update. Co do despawnu - wstaw jakiś dowód na to - to otworzę i naprawię.

**Comment by ShatteredGlassx** [comment]
Nic nie znalazłem, ale wydaje mi się, że nie powinien tam stać wieczność, bo ludzie mogliby tym spamować. Z reguły jest też tak, że quest item znika po skończeniu się cooldownu na quest itemie, quest item do tego questa ma 2min, więc wydaje mi się, że powinien zniknąć po 2min.

**Comment by NoobSunwell** [comment]
Z reguły jest tak, że trwa tyle, ile jest wpisane w spellu summonującym. A ten ma wpisane 10 minut do despawnu (nawet gdy nie używany).
