### ISSUE TITLE
[Gameplay] ressurection

### ISSUE THREAD

**Issue by Bainit123** [NoobSunwell/Sunwell-BugTracker#25]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Po zginięciu nie wskrzesiłem się u spirit healera do którego rzuciło mnie po śmierci tylko podbiegłem do innego, po ressnięciu się teleportowało mnie do spirit healera przy którym wylądowałem przy śmierci.
**Obecne działanie**: Zginąłem, rzuciło mnie do spirit healera w Shadowglen, po wszkrzeszeniu się u spirit healera w Darnassus przerzuciło mnie do Shadowglen

**Oczekiwane działanie**: Powinno wskrzesić u spirit healera u którego się ressam, czyli w tym przypadku w Darnassus

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Umrzeć
2. Podbiec do innego spirit healera i wskrzesić się u niego
3. Profit

**Comment by NoobSunwell** [comment]
To nie błąd. Tak działa ta mechanika. Polecam zapoznać się przedtem z wowhead/wowwiki.

![image](https://cloud.githubusercontent.com/assets/22621466/19291271/7dc370c6-9014-11e6-8c26-e7380ea233c0.png)
