### ISSUE TITLE
[Quest] Fresh Remounts.

### ISSUE THREAD

**Issue by kovaq** [NoobSunwell/Sunwell-BugTracker#250]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: W quescie lapiemy marchewke na kijku z jezdzca, przejmujemy jego konia, po czym wracamy do venomspite. na koniu mamy 2 mozliwosci przycisku. 1. ktory powoduje oddanie konia do quest givera, oraz strzala zejscia z mounta. Konia mozna oddac 3 razy tego samego.
http://screenshooter.net/102844212/ddkhgqi

**Obecne działanie**: Na jednym koniu robimy 3 sztuki do questa.

**Oczekiwane działanie**: 1 kon = 1punkt i nawrotka do New Hearthglen.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. bierzemy q, jedziemy do new hearthglen
2. zabijamy jezdzca na koniu, zabieramy jego marchewke na kijku i przejmujemy konia
3. prowadzimy konia do venomspite i oddajemy. (poki co 3 razy)

**Linki WoWHead/OpenWoW**:

1. http://wotlk.openwow.com/quest=12214
2. http://wotlk.openwow.com/npc=27213
3. http://wotlk.openwow.com/spell=48297

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
http://screenshooter.net/102844212/qytquyg

**Comment by NoobSunwell** [comment]
Będzie naprawione po update.

**Comment by Kougraa** [comment]
@NoobSunwell 
Mogłabym jeszcze dodać, że po zabiciu jeźdźca, koń nie powinien nas atakować.
Jak to wygląda: https://youtu.be/VvDGlxux6oM
Jak powinno wyglądać: https://youtu.be/Ry6p5JZl-XM?t=11s

Co do questa - sprawdziłam. Zalicza jak należy: https://youtu.be/3zhWGOeJC_M
