### ISSUE TITLE
[Quest] Worm Wrangler

### ISSUE THREAD

**Issue by ShatteredGlassx** [NoobSunwell/Sunwell-BugTracker#251]
Obecne działanie: Sturdy Crates można użyć od razu wchodząc do jaskini, nie musimy targetować Ice Heart Jormungar Spawn, a jak go targetujemy i używamy quest item'a, to Ice Jormungar nie znika.

Oczekiwane działanie: Sturdy Crates powinniśmy móc użyć TYLKO na Ice Heart Jormungar Spawn, a po użyciu quest itema, Ice Heart Jormungar Spawn powinien zniknąć.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Wziąć quest Worm Wrangler
2. Użyć Strudy Crates w wyznaczonym miejscu, ale nie na Ice Hearth Jormungar Spawn

**Linki WoWHead/OpenWoW**:

1. http://wotlk.openwow.com/item=36771
2. http://wotlk.openwow.com/quest=12078
3. http://wotlk.openwow.com/npc=26359

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
5117 430 197 571

**Comment by NoobSunwell** [comment]
Będzie naprawione po update.
