### ISSUE TITLE
[NPC] Quartermaster Bartlett

### ISSUE THREAD

**Issue by kovaq** [NoobSunwell/Sunwell-BugTracker#253]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Pomimo kowadla nie mozna sie u niego naprawiac. Jest to o tyle wazne, ze jest to najblizszy repair vendor od naxxa, w dodatku powiazany z cmentarzem w tym miejscu. Jezeli jego zabraknie, horda bedzie naprawiac sie dopiero w wyrmest temple lub conquest hold, co daje jakies 3 minuty straty, o ile mowimy o szybszym mouncie. (aliancki odpowiednik stoi pod samym naxxem w Wintergarde Keep) Takze nie mowimy o samym npc, jego towarach czy usludze, ale o kwestii faworyzacji alliance nad horda w wyscigu o first kill kel'thuzada. Takze to wazne.
http://screenshooter.net/102844212/lqhkris (questy u pana mam zrobione, oba.)

**Obecne działanie**: Pan Bartlett nie oferuje uslug kowalskich, pomimo, ze ma znaczek kowadla.

**Oczekiwane działanie**: Powinien byc on normalnym sprzedawca-kowalem.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Zawitac w Venomspite
2. Zagadac do Pana Bartletta.
3. (opcjonalnie) Wykonac oba questy, by miec pewnosc, ze to nie one sa wymogiem by odblokowac sklep.

**Linki WoWHead/OpenWoW**:

1. http://wotlk.openwow.com/npc=27267
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
http://screenshooter.net/102844212/lqhkris

**Comment by NoobSunwell** [comment]
Będzie naprawione po update.
