### ISSUE TITLE
[Quest] Fire Upon the Waters.

### ISSUE THREAD

**Issue by kovaq** [NoobSunwell/Sunwell-BugTracker#254]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: W zadaniu trzeba podpalic zagle statku specjalnym molotowem, by zajac marynarzy i spokojnie przejsc do kapitana pod pokladem. Problem w tym, ze palenie zagli jest mocno ograniczone.

**Obecne działanie**: Zagiel palimy tylko od strony pokazanej na skrinie.
http://screenshooter.net/102844212/acqdyht
By tu sie dostac nalezy najpierw wybic marynarzy ktorych chcemy tym paleniem zajac, wiec zadanie mija sie z celem. (co zreszta widac ile ich wytluklem znaim wgl na stealth moglem przejsc)

**Oczekiwane działanie**: Zagiel powinien palic sie po dowolnym rzucie, ktory dotyka tekstury zagla.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Wziac q, podejsc do statku
2.  Rzucic molotowa, by podpalic zagiel.
3. Obserwowac brak skutkow, poki nie podejdzie sie wedlug skrina.

**Linki WoWHead/OpenWoW**:

1. http://wotlk.openwow.com/quest=12243
2. http://wotlk.openwow.com/item=37304
3. http://wotlk.openwow.com/spell=48455

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
http://screenshooter.net/102844212/acqdyht

**Comment by NoobSunwell** [comment]
Hitbox żagla będzie znacznie poprawiony po update.
