### ISSUE TITLE
[Quest] A Fall From Grace.

### ISSUE THREAD

**Issue by kovaq** [NoobSunwell/Sunwell-BugTracker#255]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Biskup Landgren oferuje nam prywatna rozmowe, kazac nam poczekac na niego przed kosciolem, a gdy to zrobimy, prowadzi nas w odpowiednie miejsce na owa rozmowe. Niestety inne moby uznaja, ze juz nie uczestnicza w interakcji do questa i odpuszczaja sobie "bycie zielonym"
http://screenshooter.net/102844212/ptaaaxt

**Obecne działanie**: Moby aggruja sie na eskortowany cel do questa, chociaz sami powinni byc friendly.

**Oczekiwane działanie**: Moby powinny byc zielone, poniewaz trwa jeszcze "raven priest disguise"

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Wykonac czesci zadania, do momentu wyjscia przed kosciol.
2. Prawdopodobnie moby nie beda juz zielone, oprocz biskupa Landgrena, ktory prowadzi nas w "odpowiednie miejsce na prywatna rozmowe"
3. Wykonac dzialajacy quest w asyscie mobow, ktore nas leja i leja...

**Linki WoWHead/OpenWoW**:

1. http://wotlk.openwow.com/quest=12274
2. http://wotlk.openwow.com/npc=28558
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
http://screenshooter.net/102844212/vnoitxn

**Comment by NoobSunwell** [comment]
https://youtu.be/iCAnVB33RqU?t=1m49s
