### ISSUE TITLE
[NPC] Mosh'Ogg Witch Doctor

### ISSUE THREAD

**Issue by Kokaina** [NoobSunwell/Sunwell-BugTracker#257]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: W SV jest quest na zabicie paru ogrów, w tym właśnie tytułowego 5x NPC1. Quest działa poprawnie, dostajemy credity za ich zabijanie. NPC ten używa dwóch spelli, jeden z nich działa poprawnie. Drugi natomiast to totem, który powinien spowalniać czas między atakami pobliskich graczy. NPC poprawnie stawia ten totem, aczkolwiek sam totem nie narzuca debuffa na graczy ze spowolnieniem, przez co jest bezużyteczny.

**Obecne działanie**: NPC1 używa SPELL1, który stawia na ziemi totem NPC2, totem ten nie narzuca na pobliskich graczy debuffa ze spowolnieniem SPELL2

**Oczekiwane działanie**: Totem (NPC2) powinien narzucać na pobliskich graczy debuff (SPELL2)

**Co należy zrobić, aby odtworzyć ten błąd**: 

1. Zacząć bić NPC1
2. Poczekać aż NPC1 postawi totem NPC2
3. Zauważyć, że totem NPC2 nic nie robi

**Linki WoWHead/OpenWoW**:

1. ID NPC1: 1144 (http://www.wowhead.com/npc=1144/moshogg-witch-doctor)
2. ID TOTEMU (NPC2): 2667 (http://www.wowhead.com/npc=2667/ward-of-laze)
3. SPELL1, który stawia totem: 3827 (http://www.wowhead.com/spell=3827/ward-of-laze)
4. SPELL2, 20yardowy debuff, którego nie ma: 3826 (http://www.wowhead.com/spell=3826/ward-of-laze-effect)
5. Screen z brakiem debuffa: https://s16.postimg.org/ii2n7h3w5/Wo_WScrn_Shot_101916_131450.jpg

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
https://s12.postimg.org/a22paz731/Wo_WScrn_Shot_101916_130703.jpg

**Comment by NoobSunwell** [comment]
Będzie naprawione po update.
