### ISSUE TITLE
[Autoattack] wyświetlanie

### ISSUE THREAD

**Issue by nirvaaa** [NoobSunwell/Sunwell-BugTracker#258]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Ilość obrażeń jest wyświetlana w niewłaściwym momencie.

**Obecne działanie**: Po szybkim przerwaniu uderzenia melee zadane obrażenia nie są wyświetlane. Zostają one wyświetlone wraz z kolejnym atakiem.

**Oczekiwane działanie**: Po każdym uderzeniu powinny być wyświetlone obrażenia.

**Co należy zrobić, aby odtworzyć ten błąd**: Uderzyć moba melee, następnie szybko użyć innej umiejętności, np casta, po czym znowu uderzyć melee.

1. <a href='https://postimg.org/image/424k3rfzl/' target='_blank'><img src='https://s16.postimg.org/kd4o02shh/Wo_WScrn_Shot_101916_133228.jpg' border='0' alt='WoWScrnShot_101916_133228'/><br /><a target='_blank' href='https://postimage.org/app.php'>how to screen capture</a><br /><br />
2. <a href='https://postimg.org/image/baqnplio3/' target='_blank'><img src='https://s13.postimg.org/71lxnffev/Wo_WScrn_Shot_101916_133509.jpg' border='0' alt='WoWScrnShot_101916_133509'/><br /><a target='_blank' href='https://postimage.org/app.php'>windows 7 screenshot</a><br /><br />

**Comment by NoobSunwell** [comment]
Niestety na tych screenach nic nie widać. Tym bardziej, że to błąd klienta, bo obrażenia są faktycznie zadawane. Wystarczy spojrzeć na combat log.
