### ISSUE TITLE
[QUEST] Some make lemonade, some make liquor

### ISSUE THREAD

**Issue by Aezyn** [NoobSunwell/Sunwell-BugTracker#259]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Wszystko opisane niżej. 

**Obecne działanie**: Użycie jednej liany daje nieskończone, losowe owoce (można na jednej wykonać cały quest).
**Oczekiwane działanie**: Użycie jednej liany powinno dawać jeden losowy owoc.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Wziąć quest od NPC Grimbooze Thunderbrew w Nesingwary Base Camp.
2. Znaleźć jakąś lianę (Sturdy Vine).

**Linki WoWHead/OpenWoW**:

1. http://www.wowhead.com/quest=12634/some-make-lemonade-some-make-liquor
2. http://www.wowhead.com/object=190622/sturdy-vine
3. http://www.wowhead.com/npc=239/grimbooze-thunderbrew

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
http://imgur.com/a/Lq0Fq

**Comment by NoobSunwell** [comment]
Będzie naprawione po update.
