### ISSUE TITLE
[NPC/Gameplay] krótkie rozmowy

### ISSUE THREAD

**Issue by nirvaaa** [NoobSunwell/Sunwell-BugTracker#26]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Podczas biegu i zaczęcia rozmowy z npc poruszam się w pozycji "do rozmowy".

**Obecne działanie**: lecę zamiast biec i gestykulować

**Oczekiwane działanie**: Powienienem biec i gestykulować

**Co należy zrobić, aby odtworzyć ten błąd**: 

1. Należy kliknąć rozmowę z npc podczas biegu.
- Wiele razy próbowałem ale nie wiem od czego to zależy - czasem się zdarza.
https://s16.postimg.org/8djqlr885/image.jpg
https://s14.postimg.org/os45rp075/image.jpg

**Comment by NoobSunwell** [comment]
Poproszę o jakieś nagranie, bo na zdjęciach nic nie da się za bardzo wywnioskować.
