### ISSUE TITLE
QUEST: Weapons of Spirits

### ISSUE THREAD

**Issue by Xanador** [NoobSunwell/Sunwell-BugTracker#260]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: https://www.youtube.com/watch?v=DN7JDXHXSlw

**Obecne działanie**: 
Po akceptacji questa od razu można go oddać

**Oczekiwane działanie**: 
Po akceptacji questa powinniśmy poczekać, aż http://wotlk.openwow.com/npc=8115 zacznie i skończy robić "bronie", tak jak to jest na filmiku pokazane.

**Co należy zrobić, aby odtworzyć ten błąd**:
1. http://wotlk.openwow.com/npc=8115 Wykonać wszystkie jego questy, aż do ostatniego.
2. Wziąc http://wotlk.openwow.com/quest=3129.
3. Można od razu oddać.

**Linki WoWHead/OpenWoW**:
1. QUEST: http://wotlk.openwow.com/quest=3129
2. NPC Z QUESTEM: http://wotlk.openwow.com/npc=8115
3. Co powinien robić https://www.youtube.com/watch?v=DN7JDXHXSlw

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
http://imgur.com/a/Isncl

**Comment by NoobSunwell** [comment]
Będzie naprawione po update.
