### ISSUE TITLE
[NPC] Drakkari Warrior

### ISSUE THREAD

**Issue by ShatteredGlassx** [NoobSunwell/Sunwell-BugTracker#262]
Obecne działanie: W momencie, gdy chcemy zaatakować Drakkari Warrior'a, wyskakuje nam napisz "Invalid Target", nie możemy go atakować, on może atakować nas.

Oczekiwane działanie: Nie powinno być napisu "Invalid Target", oraz powinniśmy móc atakować tego NPC.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Podejść do Drakkari Warrior
2. Użyć bijącego skill'a 
3. 

**Linki WoWHead/OpenWoW**:

1. http://wotlk.openwow.com/npc=26425
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
3353 -1710 86 571

**Comment by NoobSunwell** [comment]
Będzie naprawione po update.
