### ISSUE TITLE
[NPC] Flanis Swiftwing (visual)

### ISSUE THREAD

**Issue by Kougraa** [NoobSunwell/Sunwell-BugTracker#264]
**Opis**: https://youtu.be/ch1roVYWceg

**Obecne działanie**: Mob w konfrontacji z graczem nie raczy nawet wstać.

**Oczekiwane działanie**: NPC powinien stać.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Odnaleźć NPC w Shadowmoon Valley.
2. Zaatakować go AOE (gdyż sam nie atakuje).
3. Poruszać się.

**Linki WoWHead/OpenWoW**:

1. http://www.wowhead.com/npc=21727/flanis-swiftwing
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
http://imgur.com/5RSY9qK

**Comment by NoobSunwell** [comment]
Dropu nie ma, na SS na screenie na wowhead też marty - domyślam się, że wyłączyć mu combat?

**Comment by Kougraa** [comment]
Wydaje mi się, że tak będzie najrozsądniej.

**Comment by NoobSunwell** [comment]
Będzie naprawione po update.
