### ISSUE TITLE
Atakujące kule bez nazwy.

### ISSUE THREAD

**Issue by Kougraa** [NoobSunwell/Sunwell-BugTracker#265]
**Opis**: https://youtu.be/YzupQSdkK7Y

**Obecne działanie**: Kule **BEZ NAZWY** atakują, zadają obrażenia. 

@ Edit
**Oczekiwane działanie**: Po przejściu przez zieloną kule powinna zniknąć.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Pójść w miejsce w którym znajdują się kule.
2. 
3. 

**Linki WoWHead/OpenWoW**:

1. http://www.wowhead.com/npc=21080/dormant-infernal
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
http://imgur.com/6UxUO9N

**Comment by Bainit123** [comment]
http://www.wowhead.com/npc=21080/dormant-infernal#screenshots
Możesz zobaczyć w combat logu od kogo otrzymujesz obrażenia, miałem ten sam bug.
Oczekiwane działanie: Po przejściu przez zieloną kulkę powinna zniknąć i zespawnić infernala:
http://www.wowhead.com/npc=19759/newly-crafted-infernal

**Comment by NoobSunwell** [comment]
Patrząc po filmikach na YT - infernale spawnują się, gdy znajdujesz się w zasiegu aggro tych kul.

Będzie naprawione po update.
