### ISSUE TITLE
[NPC] Razuun nie atakuje gracza.

### ISSUE THREAD

**Issue by Kougraa** [NoobSunwell/Sunwell-BugTracker#266]
**Opis**: https://youtu.be/MDzrm6EcKkE

**Obecne działanie**: Tak jak wyżej na filmie. Bos pomimo ataku przez gracza nie ma zamiaru podjecia walki na odległość. Aby było ciekawiej, mimo ataku przez gracza X _(gracza, który trzyma aggro)_, bos atakuje gracza Y _(gracza, który stoi bliżej)_.

**Oczekiwane działanie**: Bos w chwili ataku przez gracza powinien podążać za nim. 
**Co należy zrobić, aby odtworzyć ten błąd**:

1. Odnaleźć Warbringer'a Razuun'a.
2. Zaatakować i oddalać się od bosa.
3. 

**Linki WoWHead/OpenWoW**:

1. http://wotlk.openwow.com/npc=21287
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
http://imgur.com/lNQ6J1D

**Comment by NoobSunwell** [comment]
Będzie naprawione po update.
