### ISSUE TITLE
[QUEST] Divination: Gorefiends Cloak

### ISSUE THREAD

**Issue by Kougraa** [NoobSunwell/Sunwell-BugTracker#267]
**Opis**: https://youtu.be/KU-yla7zng4

**Obecne działanie**: Po zalozeniu [Spectrecles], ktore lacza nas ze swiatem duchow, powinnismy zabic Clericof Karabora, z ktorego dropi qitem. Mimo wszystko nie ma mozliwosci zaatakowania owego moba.

**Oczekiwane działanie**: Gracz powinien mieć możliwość zaatakowania Karabora.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Założyć okulary [Spectrecles].
2. Odnaleźć Clericof'a Karabor'a.
3. Próbować go zabić.

**Linki WoWHead/OpenWoW**:

1. http://www.wowhead.com/quest=10635/divination-gorefiends-cloak
2. http://wotlk.openwow.com/npc=21815
3. _[okulary]_ http://www.wowhead.com/item=30719/spectrecles
4. _[qitem z moba]_ http://www.wowhead.com/item=30799/gorefiends-cloak

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
http://imgur.com/slr4Cxh

**Comment by NoobSunwell** [comment]
Będzie naprawione po update.
