### ISSUE TITLE
[Quest] Kindness - Shadowmoon Valley

### ISSUE THREAD

**Issue by Kougraa** [NoobSunwell/Sunwell-BugTracker#268]
**Opis**: https://youtu.be/-KHFRQBD7Q0
**Obecne działanie**: Smoki po nakarmieniu przez gracza powinny odlecieć, one jednak pozostają na ziemi. 
*BTW, nie wiem w czym tkwi problem, ale aby w końcu zleciał smok do mojego przyzwoitego pokarmu, musiałam użyć zebranego qitemu z 5 razy. Natomiast znajomemu, który wraz ze mną robił questa - zaliczało instantowo, przy każdym użyciu itemu. 
Może było za słone? :(
http://imgur.com/HIsn5ix

@Edit. Po DC servera - jemu też przestało zaliczać.

**Oczekiwane działanie**: Tymczasem w chwili zakończenia posiłku przez smoka, on powinien wzlecieć w przestworza (tj. tutaj https://youtu.be/ZO48Tgy-GT8?t=3m55s ).

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Wziąć quest. 
2. Zebrać qitemy. 
3. Użyć qitemu.

**Linki WoWHead/OpenWoW**:

1. http://www.wowhead.com/quest=10804/kindness
2. http://wotlk.openwow.com/npc=21648
3. [qitem] http://www.wowhead.com/item=31372/rocknail-flayer-carcass

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
http://imgur.com/UzlvLaG

**Comment by NoobSunwell** [comment]
Ileż razy ten quest mnie denerwował na kazdym serwerze z właśnie tego powodu... Zajmę się nim jutro.

**Comment by Kougraa** [comment]
W końcu musiał ktoś zauważyć :D Mogę życzyć powodzenia ^^

**Comment by NoobSunwell** [comment]
Zwiększyłem zasięg poszukiwania pokarmu przez smoki.

NPC też będą wracały w powietrze po zjedzeniu posiłku.

Będzie po update.
