### ISSUE TITLE
[NPC] Deathguard Molder

### ISSUE THREAD

**Issue by kovaq** [NoobSunwell/Sunwell-BugTracker#269]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Kolejne blizniaki.
http://screenshooter.net/102844212/adqdnvh

**Obecne działanie**: Stoja 2.

**Oczekiwane działanie**: Powinien stac 1.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Zawitac w Venomspite, obaj stoja na glownym placu.
2. 
3. 

**Linki WoWHead/OpenWoW**:

1. http://wotlk.openwow.com/npc=27320
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
http://screenshooter.net/102844212/adqdnvh

**Comment by NoobSunwell** [comment]
Będzie naprawione po update.
