### ISSUE TITLE
Lazy Peon

### ISSUE THREAD

**Issue by Malmous** [NoobSunwell/Sunwell-BugTracker#27]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:  Jeden z peonów chodzi po drzewie NPC ID:10556 kordy:41.29 58.79

**Obecne działanie**: Peon chodzi po drzewie i wszędzie dookoła(nie przeszkadza to w zrobieniu questa gdyż po pewnym czasie idzie spać na miejsce) https://postimg.org/image/w3wq7j7vt/

**Oczekiwane działanie**: Peon powinien rąbać drewno stojąc w miejscu

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Jeśli śpi uderzyć go pałką otrzymaną w queście "Lazy Peons"
2. 
3.

**Comment by NoobSunwell** [comment]
Brak ID NPC, brak koordynatów. Proszę uzupełnić zgłoszenie.
