### ISSUE TITLE
[NPC] Forsaken Blight Spreader.

### ISSUE THREAD

**Issue by kovaq** [NoobSunwell/Sunwell-BugTracker#270]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: http://screenshooter.net/102844212/bpgkymx
Wszystkie maszyny tu stojace (do zadania) maja 1hp.

**Obecne działanie**: Maszyny maja 1hp.

**Oczekiwane działanie**: Powinny miec nieco wiecej.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Zawitac w venomspite.
2. Przejsc do wschodniego wyjscia (wedlug mapy)
3. Odkliknac maszyne i spojrzec na hp.

**Linki WoWHead/OpenWoW**:

1. http://wotlk.openwow.com/npc=26523
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
http://screenshooter.net/102844212/bpgkymx

**Comment by NoobSunwell** [comment]
Będzie naprawione po update.
