### ISSUE TITLE
[Mob] Burning Depths Necromancer.

### ISSUE THREAD

**Issue by kovaq** [NoobSunwell/Sunwell-BugTracker#271]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: http://screenshooter.net/102844212/xkqjyky Mobek stal i nic nie robil podczas walki z innym mobem, ruzcilem sie na niego by nie tracic czasu ale patrze, ze on lewy jakis, wiec cofnalem sie i ogarnalem o co chodzi. Stoi i nic nie robi.

**Obecne działanie**: Mob stoi i nic nie robi.

**Oczekiwane działanie**: Powinien przynajmniej bic z lapy.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Wejsc do Obsiadian Dragonshrine.
2. Znalezc danego moba.
3. Wywolac combat w range.

**Linki WoWHead/OpenWoW**:

1. http://wotlk.openwow.com/npc=27358
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
http://screenshooter.net/102844212/xkqjyky

**Comment by NoobSunwell** [comment]
Będzie naprawione po update.
