### ISSUE TITLE
[Mob] Azure Dragon.

### ISSUE THREAD

**Issue by kovaq** [NoobSunwell/Sunwell-BugTracker#272]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: http://screenshooter.net/102844212/vcndtbo Po uzyciu funkcji lotu z parteru na szczyt wiezy zalt tabowalem gre, by zaczac pisac wczeniejsze podanie. Gdy wrocilem na gre zobaczylem ,ze jestem martwy. Wedlug skrina zahaczyl mnie jakis smok, zabijajac mnie u samej Alexstraszy. (zaraz kolo quartermastera wyrmest accord).

**Obecne działanie**: Smok zahacza agrem o wieze.

**Oczekiwane działanie**: Smok nie powinien miec zasiegu by sie zagrowac na graczy na platformie.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Dotrzec do lokacji Wyrmest Temple
2. Wleciec na gore.
3.  Czekac az Azure Dragon osiagnie pozycje, z ktorej sie pula.

**Linki WoWHead/OpenWoW**:

1. http://wotlk.openwow.com/npc=27608
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
http://screenshooter.net/102844212/qqycfkr

**Comment by NoobSunwell** [comment]
Będzie naprawione po update.
