### ISSUE TITLE
[QUEST] Finding the Phylactery

### ISSUE THREAD

**Issue by Bizancjum** [NoobSunwell/Sunwell-BugTracker#273]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Miejsca-Transborea
   Kategoria-Quest
   Blokowanie questa/spam mobów**:

**Obecne działanie**: Można w nieskończoność przyzywać moby klikając w przedmiot (frozen phylactery) questowy, co może zablokować questa.

**Oczekiwane działanie**: Gracz nie powinien mieć możliwości przyzywać tak dużo mobów.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Posiadać questa  [71] [Finding the Phylactery](Part 1)[A 11956] i gdy dotrzemy do momentu w którym trzeba iść do małego jeziorka trzeba tam na dnie kliknąć w frozen phylactery kilka razy, a po chwili moby zaczną się masowo pojawiać.
2. 
3. 

**Linki WoWHead/OpenWoW**:

1. http://www.wowhead.com/object=188141/frozen-phylactery
2. http://www.wowhead.com/quest=11956/finding-the-phylactery
3. https://zapodaj.net/03456e1598f93.jpg.html

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
Widoczne na screanie ptk.3

**Comment by NoobSunwell** [comment]
Będzie naprawione po update.
