### ISSUE TITLE
[Quest] A Lesson Learned. (visual)

### ISSUE THREAD

**Issue by Kougraa** [NoobSunwell/Sunwell-BugTracker#274]
**Opis**: https://youtu.be/0Xc7ZPHCKA8

**Obecne działanie**: Otóż zniszczone jajka świecą się nadal.

**Oczekiwane działanie**: Zniszczone jajko powinno przestać się świecić.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Wziąć quest.
2. Odnaleźć jajko.
3. Zniszczyć jajko.

**Linki WoWHead/OpenWoW**:

1. http://www.wowhead.com/quest=10515/a-lesson-learned
2. http://www.wowhead.com/object=184684/ravenous-flayer-egg
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
http://imgur.com/ErOMGeJ

**Comment by NoobSunwell** [comment]
Będzie naprawione po update (jajko zniknie po 3 sekundach - tak jak mnie więcej na filmikach).
