### ISSUE TITLE
[NPC] Grizzly Bear

### ISSUE THREAD

**Issue by ShatteredGlassx** [NoobSunwell/Sunwell-BugTracker#275]
Opis:  Nie wiem czy to problem z MMapami, czy po prostu z tym mobkiem, ale wydaje mi się że to problem z tym NPC, bo nie spotkałem podobnego problemu z innymi NPC w wodzie.

Obecne działanie: Większość Grizzly zachowuje się bardzo dziwnie: https://zapodaj.net/91bd379a3fd9e.jpg.html

Oczekiwane działanie: NPC Nie powinien robić takich przerw, albo znaleźć inną drogę.

Co należy zrobić, aby odtworzyć ten błąd:

1. Uderzyć Grizzly, który znajduje się między dwoma "wyspami"
2. 
3. 

**Linki WoWHead/OpenWoW**:

1. http://wotlk.openwow.com/npc=27131
2. 
3. 

Lokalizacja z koordynatów GPS (X, Y, Z, Map):
3596 -2618 128 571

**Comment by NoobSunwell** [comment]
To nie MMapy - mobki chodzą sobie po prostu w randomowych kierunkach na określoną maksymalną odległość. To, że złapał taką, a nie inną drogę to normalne. Te przerwy 5 sekundowe to odstępy pomiędzy kolejnymi losowaniami nowych punktów.

TL;DR: Te mobki chodzą jak chcą i kiedy chcą, i jest to w pełni ok :)
