### ISSUE TITLE
[Quest] Dissension Amongst the Ranks

### ISSUE THREAD

**Issue by Kougraa** [NoobSunwell/Sunwell-BugTracker#276]
**Opis**: Quest polega na tym, aby zabić 5 Crazed Colossus, będąc przebranym za Illidari Blood Elf. 
http://imgur.com/JBAEXrI

**Obecne działanie**: Problem w tym, że gdy gracz się piebierze oraz zabije odpowiednie do tego questa moby, to nie w każdym przypadku je zalicza. Utrudnieniem jest także to, że jeśli quest będą miały dwie osoby - zaliczać będzie także losowemu graczowi.. Quest jest na czas, a w miejscu wyznaczonym do niego jest 5 mobów. Jeśli nie zaliczy wszystkich pięciu, gracz jest zmuszony do oczekiwania na resp mobów, gdzie nie jest w 100% pewne, że przy drugim podejściu wykona całkowicie quest.

**Oczekiwane działanie**: Zabite moby powinny być przy każdym zabiciu zaliczone do questa, pamiętając o zaliczeniach do questa graczom w grupie.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Użyć flary, aby móc wziąć quest od NPC.
2.  Założyć tabard, który nas zmieni w Illidari Blood Elf'a
3. Zabić Colosussusy.

**Linki WoWHead/OpenWoW**:

1. [Quest] http://www.wowhead.com/quest=10769/dissension-amongst-the-ranks
2. [Crazed Colossus] http://wotlk.openwow.com/npc=19823
3. [Qitem-Tabard] http://www.wowhead.com/item=31279/enchanted-illidari-tabard
4. [Qitem-Flara] http://www.wowhead.com/item=31108/korkron-flare-gun

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
http://imgur.com/cckIwkA

**Comment by NoobSunwell** [comment]
Będzie naprawione po update.
