### ISSUE TITLE
[Quest] Imbuing the Headpiece - Gul'dan.

### ISSUE THREAD

**Issue by Kougraa** [NoobSunwell/Sunwell-BugTracker#277]
**Opis**: W quescie "Imbuing the Headpiece", gracz ma za zadanie napełnić energią "Unfinished Headpiece" używając qitemu w okręgu na którym stoi Gul'dan. 
http://imgur.com/QCsBs8h
https://youtu.be/g-f5oXcjwH4

**Obecne działanie**: Quest zalicza poprawnie, jednak Gul'dan staje się agresywny i atakuje gracza.
Natomiast gracz w żaden sposób nie może go zaatakować.

**Oczekiwane działanie**: Gul'dan nie powinien atakować gracza.
https://www.youtube.com/watch?v=qNDx428JHgY

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Wziąć quest od NPC.
2. Udać się w miejsce gdzie znajduje się Gul'dan
3. Użyć quest itemu o nazwie "Unfinished Headpiece"

**Linki WoWHead/OpenWoW**:

1. [Quest] http://www.wowhead.com/quest=10782/imbuing-the-headpiece
2. [NPC] http://www.wowhead.com/npc=17008/guldan
3. [Quest item] http://www.wowhead.com/item=31360/unfinished-headpiece

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
http://imgur.com/jBFyYwP

**Comment by NoobSunwell** [comment]
Będzie naprawione po update.
