### ISSUE TITLE
[Quest] Ally of the Netherwing - i combat.

### ISSUE THREAD

**Issue by Kougraa** [NoobSunwell/Sunwell-BugTracker#278]
**Opis**: Po zabiciu "Zuluhed the Whacked" gracz ma za zadanie podnieść z jego ciała klucz i uwolnić smoka "Netherwing", który zlecił to zadanie. Gdy smok jest uwolniony, następnym zadaniem gracza jest wskoczenie na grzbiet i lot w wyznaczone miejsce. Problem w tym, że gdy gracz zaakceptuje quest, a będzie miał combat podczas tego questa, nie jest to możliwe i do skończenia zadania wymagane jest anulowanie i zrobienie go od nowa, tym razem biorąc pod uwagę czy jest się w combacie, czy też nie.
https://youtu.be/nq1i7P10_zM

**Oczekiwane działanie**: TU WPISZ JAK TO POWINNO WYGLĄDAĆ

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Wziąć quest od NPC - Smoka
2. Zabić Zuluhed the Whacked, a następnie uwolnić smoka.
3. Oddać questa i podczas brania nastepnego nabić combat na mobach w okolicy

**Linki WoWHead/OpenWoW**:

1.[Quest] http://www.wowhead.com/quest=10870/ally-of-the-netherwing
2.[NPC-Smok] http://wotlk.openwow.com/npc=22112
3.[Mob] http://www.wowhead.com/quest=10866/zuluhed-the-whacked

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
http://imgur.com/jK9DF2G

**Comment by NoobSunwell** [comment]
Będzie naprawione po update.
