### ISSUE TITLE
[Quest] What Illidan Wants, Illidan Gets... - Guardy.

### ISSUE THREAD

**Issue by Kougraa** [NoobSunwell/Sunwell-BugTracker#279]
**Opis**: "What Illidan Wants, Illidan Gets..." Kolejny quest gdzie gracz ma za zadanie przebrać się przy pomocy "Blood Elf Disguise", ale tym razem nie w celu zabicia, a dostarczeniu informacji do "Grand Commander Ruusk". 

**Obecne działanie**: Wszystko pięknie, moby nie są agresywne, aż do czasu. Gdy już gracz znajdzie NPC, któremu ma dostarczyć informacje, to okazuje się, że jest chroniony przez dwóch guardów (Shadowmoon Retainer), którzy bez wahania zaatakuja, uniemożliwiając wykonanie questa.

**Oczekiwane działanie**: Gracz powinien móc spokojnie podejść w swoim przebraniu, nie budząc żadnych podejrzeń u wyż.wym. guardów i przekazać informacje danemu NPC.
https://youtu.be/0aD_cPslb84?t=2m14s

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Wziąć quest od NPC.
2. Przebrać się za pomocą qitemu.
3. Odnaleźć Commandera i próbować przekazać mu informację.

Jedyne możliwe wykonanie questa:
https://youtu.be/Kv-jsCGLyCw

**Linki WoWHead/OpenWoW**:

1. [Quest] http://www.wowhead.com/quest=10577/what-illidan-wants-illidan-gets
2. [Quest item] http://www.wowhead.com/item=30639/blood-elf-disguise
3. [Guardy] http://wotlk.openwow.com/npc=22102

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
http://imgur.com/jkbaA0u

**Comment by NoobSunwell** [comment]
Tych 2 hostile guardów w ogóle nie powinno tam być. Będzie naprawione po update.
