### ISSUE TITLE
[QUEST] Pyrewood Ambush ID: 452

### ISSUE THREAD

**Issue by ThePuppetMaster** [NoobSunwell/Sunwell-BugTracker#28]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:
NPC ID: 2058
Quest ID: 452
NPC zleca nam questa, polegającego na obronie przed kilkoma falami mobów, które spawnują się w dzwiach pomieszczenia, każda grupa po określonym czasie.

**Obecne działanie**:
Grupy mobów spawnujące się w dzwiach pomieszczenia. Agrują się na gracza o ile nie jest w stealthcie, NPC nie dołącza do walki. Moby z pierwszego spawnu nie zagrowały się w ogóle w 2 próbach, z 2 spawnu zagrował się tylko jeden.

**Oczekiwane działanie**:
Jeżeli gracz nie wykona akcji i znajduje się dalej od mobów niż NPC, powinny zagrować się na NPC. NPC powinien dołączyć do walki.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Zaakceptować questa
2. Ustawić się z tyłu pomieszczenia, w lewym kącie za NPC i nie dokonywać żadnej akcji.
3. Czekać na reakcje mobów

**Comment by NoobSunwell** [comment]
Będzie poprawione po aktualizacji.
