### ISSUE TITLE
[NPC] Grom'tor, Son of Oronok - i jego bezinteresowność graczem.

### ISSUE THREAD

**Issue by Kougraa** [NoobSunwell/Sunwell-BugTracker#280]
**Opis**: https://youtu.be/WL8HAAlTvE4

**Obecne działanie**: Grom'tor. Son of Oronok - NPC rusza się podczas oddawania questa.

**Oczekiwane działanie**: Jak powinno być: Grom'tor. Son of Oronok nie powinien ruszać się podczas oddawania questa.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Kliknąć ppm na NPC.
2. 
3. 

**Linki WoWHead/OpenWoW**:

1. [NPC] http://www.wowhead.com/quest=10521/gromtor-son-of-oronok
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
http://imgur.com/YZK8AYA

**Comment by NoobSunwell** [comment]
Brak ID NPC

**Comment by NoobSunwell** [comment]
Nvm, i tak będzie naprawione po update.
