### ISSUE TITLE
[Moby] Agresywne Peony i brak DMG.

### ISSUE THREAD

**Issue by Kougraa** [NoobSunwell/Sunwell-BugTracker#281]
**Opis**: https://youtu.be/KB8viV4zPrM

**Obecne działanie**: Peony agruja się na graczu nie zadając DMG.

**Oczekiwane działanie**: W zależności od rodzaju Peona. Jedne powinny atakować - drugie nie.
Dragonmaw Peon powinien atakować gracza, a on jedynie za nim biega. 
Moby wszystkie sa agresywne. Powinny atakować gracza. 
[Overmine flayer na filmie także stoi w bezruchu]

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Udać się do Shadowmoon Valley w miejsce w których są Peony.
2. Podejść jak najbliżej.
3. 

**Linki WoWHead/OpenWoW**:

1. http://www.wowhead.com/npc=22252/dragonmaw-peon
2. http://www.wowhead.com/npc=23264/overmine-flayer
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
http://imgur.com/MHzaqJC

**Comment by NoobSunwell** [comment]
Peony będą walczyć po update - co do Flayera - pojedynczy przypadek, gdzie nie mógł dosięgnąć gracza.
