### ISSUE TITLE
Quest [A Strange Red Key]

### ISSUE THREAD

**Issue by Lilianka88** [NoobSunwell/Sunwell-BugTracker#282]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:  Questy mający na celu odnalezienie uwięzionej night elfki i oddanie jej kluczyka do klatki, w której jest przetrzymywana.

**Obecne działanie**: Eflka agruje się na każdego moba, którego zaatakujemy, badź on zaatakuje nas. Niby nic dziwnego, gdyby nie fakt, że rzecz dzieje się zanim oddamy jej ten klucz (czyt. ukończymy quest).

**Oczekiwane działanie**: Ww. NPC powinien grzecznie czekać w klatce, do momentu aż oddamy q i weźmiemy kolejny q, tym razem na eskortowanie elfki. Skoro biega po jaskini to po co jej klucz? :P

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Znaleźć się w Felwood i wydropić kluczyk http://wotlk.openwow.com/item=13140
2. Otworzyć bag z kluczami i akceptować q
3. Udać się do jaskinii i zaatakować moby znajdujące się blisko klatki Captured Arko'narin, zanim oczywiście oddamy q.

**Linki WoWHead/OpenWoW**:

1. http://wotlk.openwow.com/quest=5202
2. https://www.youtube.com/watch?v=fjCXB7V5rHY
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
http://i.imgur.com/uA8tJPz.jpg
http://i.imgur.com/EKvkaBr.jpg

**Comment by NoobSunwell** [comment]
Brak ID NPC

**Comment by NoobSunwell** [comment]
Będzie naprawione po update.

**Comment by Lilianka88** [comment]
Tak myslalam, ze o czyms zapomnialam ;) Dodalam id w trzecim linku (openwow.com)
