### ISSUE TITLE
[quest] scratches

### ISSUE THREAD

**Issue by turboszczur** [NoobSunwell/Sunwell-BugTracker#283]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Nie można użyć q itema i mieć peta jednocześnie.

**Obecne działanie**: Ptasior się nie pojawi jak mamy peta, a jak mamy ptasiora to nie możemy wezwać peta.

**Oczekiwane działanie**: Ptasior i pet nie powinni negować się wzajemnie.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Wziąć i zrobić questa jako hunter
2. 
3. 

**Linki WoWHead/OpenWoW**:

1. http://www.wowhead.com/quest=10556/scratches
2. http://wotlk.openwow.com/item=30530
3. http://wotlk.openwow.com/npc=21468
4. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

http://imgur.com/a/1ccsn

**Comment by turboszczur** [comment]
Generalnie wystarczy że dobiegniemy z buffem do tej driady i nam zaliczy questa, a powinno chyba zaliczyć dopiero jak przyjdziemy z tym ptakiem, z tego co czytam w komentarzach na wowhedzie.

http://wotlk.openwow.com/npc=21469

**Comment by NoobSunwell** [comment]
Summon będzie możliwy równolegle z petem.

Będzie też patrzyła na obecność ptaka obok gracza.
