### ISSUE TITLE
[quest] picking up some power conventers

### ISSUE THREAD

**Issue by turboszczur** [NoobSunwell/Sunwell-BugTracker#284]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Obiekt power conventer nie znika po użyciu.

**Obecne działanie**: Obiekt nie znika i możemy zrobić całego questa przy 1 obiekcie.

**Oczekiwane działanie**: Powinien znikać po użyciu.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Wziąć i zrobić questa.
2. 
3. 

**Linki WoWHead/OpenWoW**:

1. https://www.youtube.com/watch?v=c9709tHOTu4
2. http://wotlk.openwow.com/object=184906
3. http://wotlk.openwow.com/quest=10584

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

http://imgur.com/a/oBMBg

**Comment by NoobSunwell** [comment]
Będzie naprawione po update.
