### ISSUE TITLE
[npc] Wyrm from Beyond

### ISSUE THREAD

**Issue by turboszczur** [NoobSunwell/Sunwell-BugTracker#285]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Latający wąż stawia opór.

**Obecne działanie**: Npca nie można atakować.
**Oczekiwane działanie**: Npca powinno móc się zabić.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Udać się na miejsce wskazane w kordach.
2. 
3. 

**Linki WoWHead/OpenWoW**:

1. http://www.wowhead.com/npc=21796/wyrm-from-beyond#comments
2. https://www.youtube.com/watch?v=DYe08NuPhq8&feature=youtu.be
3. http://www.wowhead.com/quest=10594/gauging-the-resonant-frequency#go-to-comment-27888

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

http://imgur.com/a/vKKE7

**Comment by NoobSunwell** [comment]
Będzie naprawione po update.
