### ISSUE TITLE
[quest] What Came First, the Drake or the Egg?

### ISSUE THREAD

**Issue by turboszczur** [NoobSunwell/Sunwell-BugTracker#286]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Jajca nie znikają.

**Obecne działanie**: Jaja nie znikają po użyciu q itema przez co można całego q zrobić przy jednym jajcu.

**Oczekiwane działanie**: Jaja powinny znikać po użyciu q itema.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Wziąć i zrobić q.
2. 
3. 

**Linki WoWHead/OpenWoW**:

1. https://www.youtube.com/watch?v=QnAe430YROY
2. http://wotlk.openwow.com/quest=10609
3. http://wotlk.openwow.com/object=184867
4, http://wotlk.openwow.com/item=30742

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

http://imgur.com/a/1vY2z

**Comment by NoobSunwell** [comment]
Będzie naprawione po update.
