### ISSUE TITLE
[NPC] Flamebringer 

### ISSUE THREAD

**Issue by ShatteredGlassx** [NoobSunwell/Sunwell-BugTracker#287]
Obecne działanie: Po rozmowie z Flamebringer, NPC spawnuje jednego Flamebringer, ale można to powtarzać nieograniczoną ilość razy, a zespawnowane NPC nie znikają.
Tak to wygląda po minucie: https://zapodaj.net/9b489ac23cce1.jpg.html, po 5min dalej nie znikły.

Oczekiwane działanie: Po rozmowie z Flamebringer, NPC powinien spawnować jednego Flamebringer, a po kolejnej rozmowie z nim powinien spawnować kolejnego, jednak poprzedni powinien zniknąć.

Co należy zrobić, aby odtworzyć ten błąd:

1. Wziąć quest  [The Thane of Voldrune]
2. Kilkakrotnie porozmawiać z Flamebringer

**Linki WoWHead/OpenWoW**:

1. http://wotlk.openwow.com/quest=12255
2. http://wotlk.openwow.com/npc=27292
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
2817 -2505 59 571

**Comment by ShatteredGlassx** [comment]
Nowy bug związany z tym NPC:

Obecne działanie: Skill Wing Buffet nie ma Cooldownu

Oczekiwane działanie: Skill Wing Buffet powinien mieć 10s CD, tak jak tutaj:
https://www.youtube.com/watch?v=5G1P44KFTPE
czy tutaj:
https://www.youtube.com/watch?v=L_V8m20WhCQ

Co należy zrobić, aby odtworzyć ten błąd:
1. Wziąć quest [The Thane of Voldrune]
2. Użyć skill'a Wing Buff na Thane Torvald Eriksson

Linki WoWHead/OpenWoW:
1. http://wotlk.openwow.com/quest=12255
2. http://wotlk.openwow.com/npc=27292
3. http://wotlk.openwow.com/npc=27377

Lokalizacja z koordynatów GPS (X, Y, Z, Map):
2817 -2505 59 571

**Comment by NoobSunwell** [comment]
Smok + skill będzie naprawiony po update.
