### ISSUE TITLE
[Lokacja] Coldwind Heights.

### ISSUE THREAD

**Issue by kovaq** [NoobSunwell/Sunwell-BugTracker#288]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Wchodzac do gniazda harpi spodziewalem sie czegos wiecej, szczegolnie po quescie na zabicie 15 sztuk w/w stworzen. Zastalem 4 + matke w domu.
http://screenshooter.net/102844212/kwbtrvd

**Obecne działanie**: Jest zdecydowanie za malo harpii

**Oczekiwane działanie**: "Zaludniona" lokacja.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Zawitac w danej lokacji w Dragonblight.
2. 
3. 

**Linki WoWHead/OpenWoW**:

1. http://wotlk.openwow.com/npc=26575
2. http://wotlk.openwow.com/npc=26892
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
http://screenshooter.net/102844212/kwbtrvd

**Comment by NoobSunwell** [comment]
Będzie naprawione po update.
