### ISSUE TITLE
[NPC] Grizzly Bear vol.2

### ISSUE THREAD

**Issue by ShatteredGlassx** [NoobSunwell/Sunwell-BugTracker#289]
Opis: Sprawdziłem działanie tych NPC, ale tym razem nie w wodzie i nagrałem dwa filmiki - wydaje mi się, że nie jest to jednak normalne zachowanie.

Obecne działanie: 
https://www.youtube.com/watch?v=E8DblWL1NAs&feature=youtu.be
https://youtu.be/yc41ei0IxU4
https://youtu.be/E8DblWL1NAs
Jakość nie jest najlepsza.

Oczekiwane działanie: NPC powinien do mnie po prostu przyjść, a nie robić ruchy w prawo, lewo, albo w ogóle się nie ruszać.

Co należy zrobić, aby odtworzyć ten błąd:

1. Uderzyć Grizzly, który znajduje obok LoS'a

Linki WoWHead/OpenWoW:

1. http://wotlk.openwow.com/npc=27131

Lokalizacja z koordynatów GPS (X, Y, Z, Map):
3391 -3284 227 571

**Comment by NoobSunwell** [comment]
Faktycznie, po zaagrowaniu nie chodzili jak należy. Po update będą miśki naprawione.
