### ISSUE TITLE
[Mob] Rot Hide Plague Weaver

### ISSUE THREAD

**Issue by kovaq** [NoobSunwell/Sunwell-BugTracker#29]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: http://wotlk.openwow.com/npc=1940
https://youtu.be/0vycXxPpt5E

**Obecne działanie**: Gnoll gubi droge, oraz nie castuje niczego innego oprocz Plague Cloud (disease)

**Oczekiwane działanie**: Albo powinien bic, albo dobiegac do przeciwnika i chociaz z kija go potraktowac.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Pozwole sobie odeslac do filmiku, gdyz jest to skomplikowane. ( https://youtu.be/0vycXxPpt5E )
2. 
3.

**Comment by NoobSunwell** [comment]
Na filmiku jak i w grze widzę, że castuje poprawne spelle.

Movement będzie naprawiony po update.
