### ISSUE TITLE
[npc] Nexus-Prince Razaan

### ISSUE THREAD

**Issue by turboszczur** [NoobSunwell/Sunwell-BugTracker#290]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Rozmnożył się

**Obecne działanie**: Podwójny spawn tego npca. Stało się to podczas questa trapping the light fantastic.

**Oczekiwane działanie**: Powinien być 1.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Spawnuje się gdy zabijamy mobki w miejscu pokazanym w kordach. Quest nie jest chyba wymagany.
2. 
3. 

**Linki WoWHead/OpenWoW**:

1. http://www.wowhead.com/npc=21057/nexus-prince-razaan#comments
2. http://www.wowhead.com/quest=10674/trapping-the-light-fantastic
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

http://imgur.com/a/ox2BH

**Comment by NoobSunwell** [comment]
Był spawnowany przez specjalny event - dodałem wymuszenie despawnu istniejącego + despawn jeżeli przez 5 minut nikt go nie zaatakuje.
