### ISSUE TITLE
[Quest] Wolfsbane Root

### ISSUE THREAD

**Issue by ShatteredGlassx** [NoobSunwell/Sunwell-BugTracker#291]
Obecne działanie:  Wolfsbane Root respawnuje się co 1-2s.

Oczekiwane działanie:  Wolfsbane Root powinien respawnować się jak każdy normalny objekt, czyli 5min.

Co należy zrobić, aby odtworzyć ten błąd:

1. Wziąć quest  Wolfsbane Root
2. Udać się w wyznaczone miejsce
3. Uderzyć Wolfsbane Root, a następnie poczekać 1-2s.

**Linki WoWHead/OpenWoW**:

1. Quest - http://wotlk.openwow.com/quest=12307
2. Obiest - http://wotlk.openwow.com/object=189313
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
4367 -2628 254 571

**Comment by NoobSunwell** [comment]
Będzie naprawione po update.
