### ISSUE TITLE
[NPC] Kodian Conversation Credit

### ISSUE THREAD

**Issue by ShatteredGlassx** [NoobSunwell/Sunwell-BugTracker#292]
Obecne działanie: Gracze mogą "zobaczyć" Kodian Conversation Credit

Oczekiwane działanie: Gracze nie powinni widzieć Kodian Conversation Credit

Co należy zrobić, aby odtworzyć ten błąd:

1. Pójść w miejsce GPS
2. Włączyć Nameplate'y
3. 

**Linki WoWHead/OpenWoW**:

1.  http://wotlk.openwow.com/npc=27321
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
3327 -4615 233 571
https://zapodaj.net/9a67654959403.jpg.html

**Comment by NoobSunwell** [comment]
Będzie naprawione po update.
