### ISSUE TITLE
[quest] whispers of the raven god

### ISSUE THREAD

**Issue by turboszczur** [NoobSunwell/Sunwell-BugTracker#293]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Nie dostajemy buffa by rozumieć język ptasiorów.

**Obecne działanie**: Po zabiciu ptasiorów nie otrzymujemy buffa by rozumieć ich język.

**Oczekiwane działanie**: Przy zabijaniu ptasiorów powinniśmy dostać buffa aby rozumieć ich język.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Wziąć i zrobić questa.
2. 
3. 

**Linki WoWHead/OpenWoW**:

1. https://www.youtube.com/watch?v=0nz-dRGf2wE
2. http://www.wowhead.com/quest=10607/whispers-of-the-raven-god
3. http://wotlk.openwow.com/npc=19988
4. http://wotlk.openwow.com/?search=grishna+  (humanoidy)

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

http://imgur.com/a/8Mxru

**Comment by NoobSunwell** [comment]
![image](https://cloud.githubusercontent.com/assets/22621466/19569335/a85605e6-96f5-11e6-81ad-8518f25e7308.png)

Quest działa. Szansa na zdobycie buffa wynosi około 35%.

**Comment by turboszczur** [comment]
No to miałem wyjątkowego pecha, ze 15 zabiłem i nie padł wtedy. Zara obczaję ponownie.

**Comment by turboszczur** [comment]
Mój błąd wybacz.
