### ISSUE TITLE
[NPC] Tur Ragepaw

### ISSUE THREAD

**Issue by ShatteredGlassx** [NoobSunwell/Sunwell-BugTracker#294]
Opis:  Podczas robienia questa Ursoc, the Bear God, prosimy Tur Ragepaw o pomoc. Mamy do wyboru jego pomoc jako: Boomkin, Drzewo i Feral. Wybrałem Boomkina, nie wiem jak z resztą, ale pewnie też nie działają.

Obecne działanie: Tur Ragepaw zmienia się w Boomkina, ale gdy podchodzimy do bicia Ursoc'a, zmienia się w swoją pierwotną formę.

Oczekiwane działanie: Tur Ragepaw powinien zostać do końca bicia bossa w formie Boomkina.

Co należy zrobić, aby odtworzyć ten błąd:

1. Wziąć quest Ursoc, the Bear God
2. Zagadać z Tur Ragepaw 
3. 

Linki WoWHead/OpenWoW:

1. http://wotlk.openwow.com/npc=27328
2. http://wotlk.openwow.com/quest=12249
3. http://wotlk.openwow.com/npc=26633

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
4674 -3859 327 571

**Comment by NoobSunwell** [comment]
Niestety nie mogę tego błędu potwierdzić na żadnej z form - testowane po 2 razy na każdej - jedynie w moonkinie na chwilę zamienił się w fulborga aby się wyhealować - po czym wrócił do formy moonkina.

**Comment by NoobSunwell** [comment]
Bardziej mnie zaskoczył czeski tekst moonkina: "Urychlim konec tohoto besneni" :) Będzie naprawiony po update.
