### ISSUE TITLE
[QUEST] Medical supplies

### ISSUE THREAD

**Issue by nirvaaa** [NoobSunwell/Sunwell-BugTracker#295]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: http://wotlk.openwow.com/quest=9703

**Obecne działanie**: Q item nie jest wyświetlany przy npc go dropiącym.
<a href='https://postimg.org/image/jmxre5551/' target='_blank'><img src='https://s18.postimg.org/g3btoc2fd/Wo_WScrn_Shot_102016_173641.jpg' border='0' alt='WoWScrnShot_102016_173641'/><br /><a target='_blank' href='https://postimage.org/app.php'>screengrab</a><br /><br />

**Oczekiwane działanie**: Npc mający szansę dropu powinni być onzacznie.

**Co należy zrobić, aby odtworzyć ten błąd**: Zacząć q, najechać kursorem na podanego npc.

1. http://wotlk.openwow.com/item=24236#dropped-by - Q item.
2. http://www.wowhead.com/item=24236/medical-supplies#dropped-by - Q item wowhead (inny drop rate)
3. http://wotlk.openwow.com/npc=17606 - npc

**Linki WoWHead/OpenWoW**:

1. 
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by NoobSunwell** [comment]
Będzie naprawione po update - przypominam o cache.
