### ISSUE TITLE
[NPC] Broken-down Sgredder

### ISSUE THREAD

**Issue by ShatteredGlassx** [NoobSunwell/Sunwell-BugTracker#296]
Obecne działanie: Niektóre Broken-down Sgredder mają 1 HP.

**Oczekiwane działanie**: Wszystkie Broken-down Sgredder powinny mieć pełne życie.

Co należy zrobić, aby odtworzyć ten błąd

1. Wziąć quest Shredder Repair
2. Pójść w wyznaczone miejsce
3. 

**Linki WoWHead/OpenWoW**:

1. http://wotlk.openwow.com/quest=12244
2. http://wotlk.openwow.com/npc=27354
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
4156 -2964 283 571
https://zapodaj.net/b1195ef1953ef.jpg.html
https://zapodaj.net/01f3be5b892b2.jpg.html

**Comment by ShatteredGlassx** [comment]
Wsiadłem do jednego Shreddera z 1HP, który natychmiastowo umarł od Guarda, poczekałem 5min, Shredder się respawnął, ale nadal miał 1HP.

**Comment by NoobSunwell** [comment]
Będzie naprawione po update.
