### ISSUE TITLE
[Quest] Anatoly Will Talk

### ISSUE THREAD

**Issue by ShatteredGlassx** [NoobSunwell/Sunwell-BugTracker#298]
Obecne działanie: Po użyciu quest itema na Tatjanie, wsiadamy na konia, który prowadzi do małej wioski, jednak po dotarciu do celu, Tatjana zaczyna bić, jest Invalid target, ale po około minucie znika.

Oczekiwane działanie: Tatjana powinna zgubić z nas swój target i zostać tam gdzie ją zrzuciliśmy.

Co należy zrobić, aby odtworzyć ten błąd:

1. Wziąć quest Anatoly Will Talk
2. Użyć quest item na Tatjanie

**Linki WoWHead/OpenWoW**:

1. http://wotlk.openwow.com/npc=27627
2. http://wotlk.openwow.com/quest=12330
3. http://wotlk.openwow.com/item=37665

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
4070 -4130 211 571

**Comment by NoobSunwell** [comment]
Powinno być ok po update.
