### ISSUE TITLE
[SPELL] Mounts

### ISSUE THREAD

**Issue by Kokaina** [NoobSunwell/Sunwell-BugTracker#299]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Obecnie nawet w pełnym zanurzeniu w wodzie możemy wejść na mounta. Nie powinniśmy móc wejść na mounta ani będąc w wodzie "pływając", ani będąc całkowicie zanurzonym. Powinniśmy móc na niego wejść gdy postać jest na lądzie bądź w płytkiej wodzie, gdzie może jeszcze chodzić lecz nie pływać. Dopiero od cata można czynić takie cuda. Załączam dowód pod linkiem:
https://s11.postimg.org/syapp20gz/Wo_WScrn_Shot_102016_191601.jpg

**Obecne działanie**: Możemy wejść na mounta będąc wodzie.

**Oczekiwane działanie**: Powinniśmy nie móc tego robić.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Wejść na mounta będąc zanurzonym.
2. 
3. 

**Linki WoWHead/OpenWoW**:

1. 
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
Niepotrzebne.

**Comment by NoobSunwell** [comment]
![image](https://cloud.githubusercontent.com/assets/22621466/19571062/e5dc4fb8-96fc-11e6-9d38-77ab6ee9c5ee.png)

**Comment by NoobSunwell** [comment]
PS: Nie od cata tylko od tego patcha - w Cata nawet nie ma takich zmian.

**Comment by Kokaina** [comment]
Ja mówię o wejścu na mounta a nie o samym pływaniu. Na wotlku nie wejdziesz na mounta będąc w wodzie. To co wkleiłeś jest prawdą, że można pływać na mouncie w wodzie ale trzeba na niego ówcześnie wejść na lądzie.

W cata możesz wejśc na mounta w wodzie będąc na powierzchni, teraz nie powinieneś móc.

**Comment by NoobSunwell** [comment]
Będę w takim razie prosił o jakiś dowód na to.
