### ISSUE TITLE
[QUEST] Bounty on Garrick Padfoot 

### ISSUE THREAD

**Issue by Hehedzki** [NoobSunwell/Sunwell-BugTracker#3]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Mobek do questa jest neutral, a powinien byc unfriendly

**Obecne działanie**: Mobek do questa jest neutral

**Oczekiwane działanie**: Mobek powinien byc unfriendly i atakowac kazdego gracza w poblizu: https://www.youtube.com/watch?v=HviG0miDzaE

**Co należy zrobić, aby odtworzyć ten błąd**:

1.  Zmienic status mobka z neutral na unfriendly

**Comment by NoobSunwell** [comment]
Film jest z dnia: 04.07.2008 - to oznacza patch 2.4.3. W patchu 3.3.x wszystkie hostile moby zostały zmienione na neutrale, jak i większość elit z TBC w normalne NPC.

Kwestia do obgadania, czy chcemy przywracać frakcje wszystkich stworzeń do stanu sprzed 3.3.x.

**Comment by NoobSunwell** [comment]
Wontfix na chwilę obecną.
