### ISSUE TITLE
[Mob] Thule Ravenclaw

### ISSUE THREAD

**Issue by kovaq** [NoobSunwell/Sunwell-BugTracker#30]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: https://youtu.be/qpS-HhmWRHc
http://wotlk.openwow.com/npc=1947
Zaznacze ,ze chwile czesniej zrobilismy go po q item, po czym nie minela minuta a on juz stal. Idealnie do filmiku.

**Obecne działanie**: Jak na locka, niezle biega i castuje. 

**Oczekiwane działanie**: Przy cascie zarowno Immolate'a jak i Hex of Ravenclaw (jego jakis tam unikatowy spell) pan Thule powinien stac w miejscu. Jak widac na filmiku celowo przerywalem droge casta, by moc sie obronic, jednakze, on nic sobie z tego nie robil.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Pozwole sobie na odeslanie do filmiku. ( https://youtu.be/qpS-HhmWRHc )
2. 
3.

**Comment by NoobSunwell** [comment]
Po aktualizacji moby nie będą castowac spelli w ruchu (chyba, że sam spell na to pozwala).
