### ISSUE TITLE
[Quest] Slim Pickings

### ISSUE THREAD

**Issue by kovaq** [NoobSunwell/Sunwell-BugTracker#300]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: 
http://screenshooter.net/102844212/hemeghx

**Obecne działanie**: Q item mozna podnosic w nieskonczonosc, gdzie jedyny ogranicznik to miejsce w bagu.

**Oczekiwane działanie**: Przedmiot powinien byc unikalny.

**Co należy zrobić, aby odtworzyć ten błąd**:

1.  Wziac q
2. Pobiec do jaskini.
3. Odkliknac na cialo, by podniesc q item.

**Linki WoWHead/OpenWoW**:

1. http://wotlk.openwow.com/quest=12075
2. http://wotlk.openwow.com/item=36765
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
http://screenshooter.net/102844212/pepmgki

**Comment by NoobSunwell** [comment]
Będzie naprawione po update.
