### ISSUE TITLE
[Quest] Strained Supplies

### ISSUE THREAD

**Issue by Kougraa** [NoobSunwell/Sunwell-BugTracker#301]
**Opis**: Brak przynależności pająka do questa.

**Obecne działanie**: Gracz nie widzi, że pająk należy do questa.

**Oczekiwane działanie**: Najeżdżając kursorem na pająka, gracz powinien widzieć, że z pająka dropi item, który jest potrzebny do questa.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Wziąć quest od NPC.
2. Znaleźć pająka.
3. 

**Linki WoWHead/OpenWoW**:

1. [Quest] http://www.wowhead.com/quest=10017/strained-supplies
2. [Qitem] http://www.wowhead.com/item=25802/dreadfang-venom-sac
3. [NPC] http://www.wowhead.com/npc=18597/shanir

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
http://imgur.com/FnsovOv

**Bardzo słaby drop qitemu.** , czy może mój nie fart?

**Comment by NoobSunwell** [comment]
Brak ID NPC.

**Comment by Kougraa** [comment]
Poprawione.

**Comment by NoobSunwell** [comment]
W dalszym ciągu brak NPC, na którym powinna być informacja w tooltipie.

**Comment by NoobSunwell** [comment]
Będzie po update. Na szczescie to tylko 2 NPC.
