### ISSUE TITLE
[QUEST]  Matis the Cruel

### ISSUE THREAD

**Issue by nirvaaa** [NoobSunwell/Sunwell-BugTracker#302]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: http://wotlk.openwow.com/quest=9711

**Obecne działanie**: Matis nie atakuje gracza (chociaż wcześniej, gdy podchodziłem do tego q, zaatakował mnie - nie potrafię powiedzieć na czym polega ta losowość).
<a href='https://postimg.org/image/7givmcl9p/' target='_blank'><img src='https://s22.postimg.org/andf5z5pt/Wo_WScrn_Shot_102016_194144.jpg' border='0' alt='WoWScrnShot_102016_194144'/><br /><a target='_blank' href='https://postimage.org/'>image hosting no registration</a><br /><br />
**Oczekiwane działanie**: Matis powinien atakować gracza.

**Co należy zrobić, aby odtworzyć ten błąd**: Pobrać quest, zaatakować Matisa.

1. http://wotlk.openwow.com/npc=17664 - Matis
2. 
3. 

**Linki WoWHead/OpenWoW**:

1. 
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by NoobSunwell** [comment]
Czy zgubił on combat po jakimś czasie? Czy stał tak cały czas?

**Comment by NoobSunwell** [comment]
Dodałem mu wyłączenie movementu podobne jak u miśków. Powinno pomóc.
