### ISSUE TITLE
NPC nie można zaatakować. " Claw "

### ISSUE THREAD

**Issue by Xanador** [NoobSunwell/Sunwell-BugTracker#303]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: 
Nie można zaatakować moba

**Obecne działanie**: 
Nie możemy zaatakować tego moba http://wotlk.openwow.com/npc=17827 . Jedyna rzecz zadająca obrażenia to Thronsy od Druida.

**Oczekiwane działanie**:
Powinniśmy móc zaatakowac moba każdym zakęciem i atakiem.

**Co należy zrobić, aby odtworzyć ten błąd**:
1. Wejść do http://www.wowhead.com/zone=3716/the-underbog
2. Znaleźć bossa, http://wotlk.openwow.com/npc=17826
3. Przy bossie będzie zbugowany mob: http://wotlk.openwow.com/npc=17827
4. Bez odbioru.

**Linki WoWHead/OpenWoW**:
1. INSTANCJA: http://www.wowhead.com/zone=3716/the-underbog
2. ZBUGOWANY MOB: http://wotlk.openwow.com/npc=17827
3. THRONSY: wotlk.openwow.com/spell=26992

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
Kolega podrzuci GPS.
https://www.youtube.com/watch?v=Vq_kyhCh0oU&feature=youtu.be

**Comment by Ben1o** [comment]
![aaaaaaaaa](https://cloud.githubusercontent.com/assets/22753220/19572701/b16340dc-9703-11e6-905f-0bbdd448e479.jpg)

**Comment by NoobSunwell** [comment]
Będzie naprawione po update.
