### ISSUE TITLE
[quest bombing run

### ISSUE THREAD

**Issue by turboszczur** [NoobSunwell/Sunwell-BugTracker#304]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Działo spaceruje za nami. W niektórych miejscach 2 typy dział są blisko siebie ( nie wiem czy tak ma być)

**Obecne działanie**: Legion Fel Cannon mark II spaceruje za nami po ziemi. W niektórych miejscach są 2 typy dział nałożone na siebie.

**Oczekiwane działanie**: W/w działo nie powinno łazić za nami. Nie jestem pewien co do 2 dział koło siebie ale nie powinny nakładać się na siebie.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Wziąć i zrobić questa.
2. 
3. 

**Linki WoWHead/OpenWoW**:

1. http://wotlk.openwow.com/npc=22451
2. https://www.youtube.com/watch?v=Dz83BH23xNQ
3. http://wotlk.openwow.com/npc=23082
4. http://wotlk.openwow.com/quest=11102
**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

http://imgur.com/a/BfYBW

**Comment by NoobSunwell** [comment]
Będzie naprawione po update.
