### ISSUE TITLE
[Quest] Who Are They?

### ISSUE THREAD

**Issue by Kougraa** [NoobSunwell/Sunwell-BugTracker#305]
**Opis**: https://youtu.be/qQ4EzTFWnUA

**Obecne działanie**: Podczas Disguise w quescie "Who Are They?", gdzie gracz musi porozmawiać z kilkoma npc. Shadowy Hunter, pomimo naszego przebrania atakuje gracza i uniemożliwia ukończenie questa.

**Oczekiwane działanie**: https://www.youtube.com/watch?v=UexSPsQMTl0
W chwili, gdy jesteśmy przebrani - nic nas nie powinno atakować na obszarze Grangol'var Village.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Wziąć quest od NPC.
2. Porozmawiać z NPC od Questa, aby zamienić sie w Orca.
3. Odnaleźć NPC, z ktorymi ma za zadanie porozmawiać.

**Linki WoWHead/OpenWoW**:

1. [Quest] http://www.wowhead.com/quest=10040/who-are-they
2. [NPC] http://wotlk.openwow.com/npc=18718

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
http://imgur.com/6VlaCz7

-> To nie wina peta. Ladarius robiąc questa solo mial podobny problem.

**Comment by NoobSunwell** [comment]
To wina tego jednego NPC - będzie naprawiony po update.

**Comment by turboszczur** [comment]
Przeczytaj komentarza z wowheada, shadowy hunter ma cię wykrywać. Na filimkach jest tak samo.

**Comment by NoobSunwell** [comment]
Ok, w takim razie revert na zmianę.
