### ISSUE TITLE
[Quest] A Bear of an Appetite

### ISSUE THREAD

**Issue by ShatteredGlassx** [NoobSunwell/Sunwell-BugTracker#306]
Obecne działanie: Ławica nie znika po użyciu na nią quest itema, można zaliczyć na jednej cały quest.

Oczekiwane działanie: Ławica powinna zniknąć po użyciu quest itema.

Co należy zrobić, aby odtworzyć ten błąd:

1. Wziąć quest  [A Bear of an Appetite]
2. Pójść w wyznaczone miejsce 
3. Znaleźć ławicę "School of Northern Salmon"
4. Użyć quest itemu

Linki WoWHead/OpenWoW:

1. http://wotlk.openwow.com/quest=12279
2. http://wotlk.openwow.com/item=37542
3. http://wotlk.openwow.com/object=189290

Lokalizacja z koordynatów GPS (X, Y, Z, Map):
4298 -5106 0 571

**Comment by NoobSunwell** [comment]
Będzie naprawione po update.
