### ISSUE TITLE
[NPC] Tecahuna

### ISSUE THREAD

**Issue by ShatteredGlassx** [NoobSunwell/Sunwell-BugTracker#308]
Obecne działanie: Skill Tecahuna Venom Spit bije po 40 - 200.

Oczekiwane działanie: Nie jestem pewien ile powinna bić, znalazłem coś takiego: 
https://www.wow-freakz.com/npc_finder.php?npc=26865&name=tecahuna
Patrząc po filmiku można też stwierdzić, że bije znacznie więcej niz 40-200 (Harisson ma 70k HP)
Wydaje mi się, że DMG Harissona też nie jest poprany.
https://www.youtube.com/watch?v=p-Hdtt0Nu9M

Co należy zrobić, aby odtworzyć ten błąd:

1. Wziąć quest http://wotlk.openwow.com/quest=12082
2. Iść za Harissonem i czekać na Spawn Tecahun'y
3. 

**Linki WoWHead/OpenWoW**:

1. http://wotlk.openwow.com/npc=26865
2. http://wotlk.openwow.com/spell=47629
3. http://wotlk.openwow.com/quest=12082
4. http://wotlk.openwow.com/npc=26814

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
4894 -4751 27 571

**Comment by NoobSunwell** [comment]
Spell powinien bić więcej po update. Co do Harrisona - nie ma jak sprawdzić, zdaje się, że i tak trochę obrażeń zadaje.
