### ISSUE TITLE
[quest] It's a Fel Reaver, But with Heart

### ISSUE THREAD

**Issue by turboszczur** [NoobSunwell/Sunwell-BugTracker#309]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Brak addów (chyba zaxxis ambusher)

**Obecne działanie**: Gdy zaatakujemy robota nic się nie pojawia i możemy go zabić bez przeszkód.

**Oczekiwane działanie**: Powinny pojawić się addy po zaatakowaniu robota.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Wziąć i zrobić questa.
2. 
3. 

**Linki WoWHead/OpenWoW**:

1. http://www.wowhead.com/quest=10309/its-a-fel-reaver-but-with-heart#videos
2. http://wotlk.openwow.com/npc=20287
3. https://www.youtube.com/watch?v=lrEJT7JNeSk

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

http://imgur.com/a/fekpB

**Comment by NoobSunwell** [comment]
Będzie naprawione po update.
