### ISSUE TITLE
[OBJECT] Gwiazdki przy obiektach do questów

### ISSUE THREAD

**Issue by turboszczur** [NoobSunwell/Sunwell-BugTracker#31]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:

**Obecne działanie**: Gwiazdki przy niektórych obiektach do questów unoszą się o wiele wyżej niż powinny oraz są zbyt duże.

**Oczekiwane działanie**: Gwiazdki powinny być bardziej subtelne, wielkościowo odpowiednie do obiektu.

**Co należy zrobić, aby odtworzyć ten błąd**: Zrobić questy w tym przypadku "Iveryon antidote" oraz "Seek redemption" ( nie umiem znaleźć id od następnego zgłoszenia postaram się żeby już były). Jeszcze gwiazdki przy jajkach pająków w jaskini w lokacji startowej nocnych elfów też są zbyt duże lecz nie zrobiłem screena gdyż byłem zafrasowany czymś innym.

Na screenach 1 i 3 gwiazdki zbyt duże a na screenie 2 gwiazdki poprawne.

http://imgur.com/a/tozMZ

**Comment by NoobSunwell** [comment]
Rozmiar tych gwiazdek nie jest w żaden sposób zależny od serwera.
