### ISSUE TITLE
[NPC] Crippler

### ISSUE THREAD

**Issue by Kougraa** [NoobSunwell/Sunwell-BugTracker#310]
**Opis**:  https://youtu.be/0EvL2f_-nPE

**Obecne działanie**: Crippler pomimo combatu - stoi w miejscu.

**Oczekiwane działanie**: NPC powinien podążać za graczem w chwili combatu.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Odnaleźć NPC. 
2. Zaatakować.
3. 

**Linki WoWHead/OpenWoW**:

1. http://wotlk.openwow.com/npc=18689
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
http://imgur.com/Pf6lYL6

**Comment by NoobSunwell** [comment]
Będzie naprawione po update.
