### ISSUE TITLE
[NPC] Refugee i niechęć do stania.

### ISSUE THREAD

**Issue by Kougraa** [NoobSunwell/Sunwell-BugTracker#312]
**Opis**: Maghar Refugee i Orc Refugee nie mają ochoty stać.
http://imgur.com/8lCV5zL

Przy okazji wrzucam film na którym są widoczne latające Dwarfy.
https://youtu.be/VLMioqjmIV8

**Obecne działanie**: NPC leżą plackiem na ziemi.

**Oczekiwane działanie**: Na wszystkich przejrzanych screenach - NPC stoją, więc powinny stać.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Przybyć do Shatt
2. Odnaleźć NPC.
3. 

**Linki WoWHead/OpenWoW**:

1. http://wotlk.openwow.com/npc=19144
2. http://wotlk.openwow.com/npc=19150
3. http://wotlk.openwow.com/npc=19077

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
http://imgur.com/Mr36Zf5

**Comment by NoobSunwell** [comment]
Będzie naprawione po update.
