### ISSUE TITLE
[Quest] Missing Friends.

### ISSUE THREAD

**Issue by Kougraa** [NoobSunwell/Sunwell-BugTracker#314]
**Opis**: W quescie "Missing Friends" gracz ma za zadanie wydropić klucz z mobów i uwolnić 12 dzieci z klatek.

**Obecne działanie**: Wykonując quest w party - zalicza uwolnienie dzieci tylko jednemu graczowi.

**Oczekiwane działanie**: Wypuszczenie dzieci z klatek powinno być zaliczone obu graczom.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Wziąć quest wraz z przyjacielem.
2. Odnaleźć klucz poprzez zabijanie mobów [Skithian'ów].
3. Otworzyć klatkę z dziećmi w pobliżu przyjaciela z grupy.

**Linki WoWHead/OpenWoW**:

1. [Quest] http://www.wowhead.com/quest=10852/missing-friends
2. [Dzieci] http://www.wowhead.com/npc=22314/captive-child
3. [Klucz] http://www.wowhead.com/item=31655/veil-skith-prison-key
4. [Moby] http://wotlk.openwow.com/npc=18452
                http://wotlk.openwow.com/npc=18453

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
http://imgur.com/w9IKGb3

-> Co do dzieci, jest za mało. 
Powinno być po 2 dzieci na jedna klatke na ziemi oraz po 4 dzieci na jedna klatke na drzewach. My natomiast mamy po 1 dziecku na ziemi i po 2 dzieci na drzewach, co daje nam wynik 6 wypuszczonych npc zaliczonych dla jednego gracza przy jednym podejściu. My mamy za zadnie wypuszczenia 12 dzieci. W takim wypadku musimy do questa podchodzić po raz 2. 
(nie wspominając już o przyjacielu z grupy).

**Comment by NoobSunwell** [comment]
Skąd informacja, że powinno zaliczać dla party?

**Comment by NoobSunwell** [comment]
Spawnów będzie 4x więcej po update. Respawn ich również będzie mniejszy (w klatkach dzieci będą siedziały poupychane po 2 do 4).

**Comment by Kougraa** [comment]
To moje osobiste spostrzeżenie. Questy wykonuje zwykle wyłącznie z osobą w party. Takie typu questy [zebrać-uwolnić] były zaliczane obu osobom.
