### ISSUE TITLE
[quest] dr boom!

### ISSUE THREAD

**Issue by turboszczur** [NoobSunwell/Sunwell-BugTracker#315]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Atakuje ze zbytniego dystansu a bomby go nie zabijają.

**Obecne działanie**: Dr boom atakuje ze zbyt dużej odległości. Bomby które powinny go zabić nie zadają mu obrażeń.
**Oczekiwane działanie**: Powinien mieć mniejszy zasięg  oraz bomby powinny mu zadawać obrażenia. 

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Wziąć i zrobić questa.
2. 
3. 

**Linki WoWHead/OpenWoW**:

1. https://www.youtube.com/watch?v=dD2FdUHrwaw
2. http://wotlk.openwow.com/quest=10221
3. http://wotlk.openwow.com/item=29429
4. http://wotlk.openwow.com/npc=20284
5. https://www.youtube.com/watch?v=dXC2eVaHjSo&feature=youtu.be

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

http://imgur.com/a/UmCja

**Comment by NoobSunwell** [comment]
Będzie naprawione po update.
