### ISSUE TITLE
[quest] shutting Down Manaforge B'naar

### ISSUE THREAD

**Issue by turboszczur** [NoobSunwell/Sunwell-BugTracker#316]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Konsola jest chyba zła za wyłączenie bo bije nas z melee i robi combata.

**Obecne działanie**: Obiekt konsola atakuje z nas melee jak ją wyłączymy tworząc combata i zadaje obrażenia.

**Oczekiwane działanie**: Nie powinniśmy być atakowani przez konsole i mieć przez nią combata.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Wziąć i zrobić questa.
2. 
3. 

**Linki WoWHead/OpenWoW**:

1. https://www.youtube.com/watch?v=LkcvDAt1lU0
2. http://wotlk.openwow.com/object=183770
3. http://wotlk.openwow.com/quest=10329

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

http://imgur.com/a/HX12l

**Comment by NoobSunwell** [comment]
Ta, i jeszcze 2 inne konsole będą naprawione po update.
