### ISSUE TITLE
[QUEST] Post-Wrathgate phasing

### ISSUE THREAD

**Issue by NoobSunwell** [NoobSunwell/Sunwell-BugTracker#317]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: http://forum.sunwell.pl/viewtopic.php?p=8358#p8358
Wpis tylko po to, aby nie zapomnieć o nim wspomnieć przy changelogu.

**Obecne działanie**: n/d
**Oczekiwane działanie**: n/d

**Co należy zrobić, aby odtworzyć ten błąd**:

1. 
2. 
3. 

**Linki WoWHead/OpenWoW**:

1. 
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by NoobSunwell** [comment]
Będzie naprawione po update.

**Comment by kovaq** [comment]
Robilismy dzis postacie na testowanie classic dungeonow. Tp do dala po lvl, wracam do orgri i znowu fazowanie. Na pewno to powinno odpalac sie przy wejsciu do north, a nie po ktoryms quescie z chaina?
http://screenshooter.net/103008095/yrjeyqr
