### ISSUE TITLE
[quest] bloodgem crystals

### ISSUE THREAD

**Issue by turboszczur** [NoobSunwell/Sunwell-BugTracker#318]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Przerywa nam casta itemu.

**Obecne działanie**: Gdy używamy q itemu  to przerywa nam casta i nie można zrobić questa a item sam znika.

**Oczekiwane działanie**: Po użyciu itemu powinniśmy channelować przez chwilę. Open wow błędnie pokazuje że q tylko dla hordy.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Wziąć i zrobić questa.
2. 
3. 

**Linki WoWHead/OpenWoW**:

1. http://wotlk.openwow.com/quest=10204
2. http://wotlk.openwow.com/item=28452
3. https://www.youtube.com/watch?v=Ns0efjMi-7M
4. https://www.youtube.com/watch?v=PluPJP6Qiak&feature=youtu.be

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

http://imgur.com/a/T0jTX

**Comment by NoobSunwell** [comment]
Będzie naprawione po update.
