### ISSUE TITLE
[Profka]Journeyman

### ISSUE THREAD

**Issue by nirvaaa** [NoobSunwell/Sunwell-BugTracker#32]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Skasowany do tej pory wbity skill po nauczeniu się wyższego poziomy profki.

**Obecne działanie**: Kasowanie skilla.

**Oczekiwane działanie**: Trwanie skilla.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Wyskillować profkę do 50 pkt.
2. Nauczyć się od trenera wyższego poziomu.
3. 
https://s12.postimg.org/c4wxv2y6l/herba.jpg

**Comment by NoobSunwell** [comment]
https://github.com/NoobSunwell/Sunwell-BugTracker/issues/14
