### ISSUE TITLE
[Quest] Mr. Floppy's Perilous Adventure

### ISSUE THREAD

**Issue by ShatteredGlassx** [NoobSunwell/Sunwell-BugTracker#320]
Obecne działanie: 1. Hungry Wolf nie bije - https://zapodaj.net/d2ee6114936df.jpg.html (brak targetu)
2. Ravenous worg przez 5s jest friendly, potem podchodzi do Mr. Floppy (jest już enemy), jednak nie ma scenki, chwilę później ucieka, chociaż został zaatakowany (https://zapodaj.net/6cd3e64452aa2.jpg.html)
Oczekiwane działanie: 1. Hungry Worg powinien nas bić: https://www.youtube.com/watch?v=FnHXYNYKMjA 1:13
2. Ravenous worg powinien być od razu Enemy, ale nie powinniśmy go od razu bić, tak jak tutaj: https://www.youtube.com/watch?v=FnHXYNYKMjA 2:48, oraz powinna być scenka tak jak na filmiku, później Ravenous worg powinien być możliwy do zaatakowania i powinien nas bić.

Co należy zrobić, aby odtworzyć ten błąd:

1. Wziąć quest Mr. Floppy's Perilous Adventure
2. Czekać na wilki :D
3. 

**Linki WoWHead/OpenWoW**:

1. http://www.wowhead.com/npc=26590/ravenous-worg
2. http://wotlk.openwow.com/npc=26586
3. http://wotlk.openwow.com/quest=12027
4. http://wotlk.openwow.com/npc=26589

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
4336 -3688 262 571
https://zapodaj.net/d8ae117e4d8ae.jpg.html

**Comment by NoobSunwell** [comment]
Będzie naprawione po update (łącznie ze scenką).
