### ISSUE TITLE
[Quest] The Fallen Exarch

### ISSUE THREAD

**Issue by Kougraa** [NoobSunwell/Sunwell-BugTracker#321]
**Opis**: Po użyciu Auchenai Coffin pojawia się Reanimated Exarch - npc do zaliczenia questa - którego nie można atakować.

**Obecne działanie**: Brak możliwości ataku npc.
https://youtu.be/DFWDlrhzinE

**Oczekiwane działanie**: https://youtu.be/ay40u0SqpqE?t=36s

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Wziąć quest.
2. Użyć Auchenai Coffin.
3. Próbować uderzyć npc.

**Linki WoWHead/OpenWoW**:

1. [Quest] http://www.wowhead.com/quest=10915/the-fallen-exarch
2. [NPC] http://www.wowhead.com/npc=22452/reanimated-exarch
3. [Objekt] http://www.wowhead.com/object=184999/auchenai-coffin

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
http://imgur.com/6qICnM7

**Comment by NoobSunwell** [comment]
Będzie naprawione po update.
