### ISSUE TITLE
[quest] shutting Down Manaforge Coruu

### ISSUE THREAD

**Issue by turboszczur** [NoobSunwell/Sunwell-BugTracker#322]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Konsola jest chyba zła za wyłączenie bo bije nas z melee i robi combata.

**Obecne działanie**: Obiekt konsola atakuje z nas melee jak ją wyłączymy tworząc combata i zadaje obrażenia.

**Oczekiwane działanie**: Nie powinniśmy być atakowani przez konsole i mieć przez nią combata.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Wziąć i zrobić questa.
2. 
3. 

**Linki WoWHead/OpenWoW**:

1. http://wotlk.openwow.com/object=183956
2. http://www.wowhead.com/quest=10330/shutting-down-manaforge-coruu
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

http://imgur.com/a/N8hvV

**Comment by NoobSunwell** [comment]
Ta, i jeszcze 2 inne konsole będą naprawione po update.
