### ISSUE TITLE
[Quest] We Have the Power

### ISSUE THREAD

**Issue by ShatteredGlassx** [NoobSunwell/Sunwell-BugTracker#323]
Opis: Zabiłem dwa razy Rune-Smith Durar, quest item padł za drugim. Zabiłem trzy razy Rune-Smith Kathorn, quest item padł za trzecim.

Obecne działanie: Rune-Smith Durar i Rune-Smith Kathorn nie zawsze dropią quest item.

Oczekiwane działanie: Oba NPC powinny mieć 100% dropu na quest item.

Co należy zrobić, aby odtworzyć ten błąd:

1. Wziąć quest  [We Have the Power]
2. Pójść w wyznaczone miejsca
3. Zabić Rune-Smith Durar i Rune-Smith Kathorn 

Linki WoWHead/OpenWoW:

1. http://wotlk.openwow.com/npc=26409 - NPC
2. http://wotlk.openwow.com/npc=26410 - NPC
3. http://wotlk.openwow.com/item=36858 - Quest item, napisane 100% DROP CHANCE
4. http://wotlk.openwow.com/item=36857 - Quest item, napisane 100% DROP CHANCE
5. http://wotlk.openwow.com/quest=12131 - Quest

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
3439 -5143 235 571
https://zapodaj.net/24c5adbe77b9f.jpg.html

**Comment by NoobSunwell** [comment]
Jeżeli content jest obecny na globie - to wowhead jest bardziej wiarygodny (tyczy się to TBC i WotLK):

http://www.wowhead.com/item=36857/durars-power-cell
http://www.wowhead.com/item=36858/kathorns-power-cell

Około 45%.

**Comment by NoobSunwell** [comment]
Z drugiej strony - spawny są pojedyncze - więc faktycznie 100% ma więcej sensu ;)
