### ISSUE TITLE
[Quest] Threat from Above

### ISSUE THREAD

**Issue by Kougraa** [NoobSunwell/Sunwell-BugTracker#324]
**Opis**: W queście "Threat from Above" trzeba zabić 20 Gordunni Ogre. 

**Obecne działanie**: Quest działa jak należy, jednak każdy ogr naliczany jest podwójnie, co skutkuje tym, że gracz musi zabić jedynie 10 tych ogrów.
https://youtu.be/UNI05r7mKTQ

**Oczekiwane działanie**: Ogry powinny być naliczane pojedynczo.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Wciąć questa od NPC w Shattarah.
2. Udać się w wyznaczone miejsce i zabić jednego z Gorduuni Ogre.

**Linki WoWHead/OpenWoW**:

1. http://www.wowhead.com/quest=11096/threat-from-above
2. http://wotlk.openwow.com/npc=22143

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
http://imgur.com/kt9ZtF4

**Comment by NoobSunwell** [comment]
Będzie naprawione po update.

**Comment by Kougraa** [comment]
Wrzuciłam linki Ogrów, które są wliczane do questa. Jest ich kilka rodzai.
