### ISSUE TITLE
[Quest] ... Or Maybe We Don't

### ISSUE THREAD

**Issue by Shatterx** [NoobSunwell/Sunwell-BugTracker#325]
Obecne działanie: Po zabiciu Lightning Sentry quest nie jest zaliczany / Brak wypowiedzi NPC, którego przyzywamy. Pewnie dlatego, że po zabiciu Lightning Sentry powinien się wypowiadać, ale lepiej sprawdzić, jak będziesz naprawiał.
Filmik jak to wygląda:
https://youtu.be/X6c7n2NV5CY

Oczekiwane działanie: Wszystko widać tutaj: https://www.youtube.com/watch?v=vez8QL_dnTY
Po zabiciu Lightning Sentry nasz NPC powinien napisać kilka słów, a potem zaliczyć nam quest.

Co należy zrobić, aby odtworzyć ten błąd:

1. Wziąć quest ... Or Maybe We Don't
2. Użyć quest itemu w miejscu GPS
3. Zabić Lightning Sentry

Linki WoWHead/OpenWoW:

1. http://wotlk.openwow.com/quest=12138
2. http://wotlk.openwow.com/item=36936
3. http://wotlk.openwow.com/npc=26407
4. http://wotlk.openwow.com/npc=27017

Lokalizacja z koordynatów GPS (X, Y, Z, Map):
3598 -4937 218 571
https://zapodaj.net/7d53fc063e200.jpg.html

**Comment by NoobSunwell** [comment]
Będzie naprawione po update.
