### ISSUE TITLE
[NPC] Image of Loken

### ISSUE THREAD

**Issue by ShatteredGlassx** [NoobSunwell/Sunwell-BugTracker#326]
Z góry napiszę, że nie jestem pewien co do tego NPC - może działa prawidłowo, ale na logike nie :D.

Obecne działanie: Image of Loken ma 83 LvL i można go bić, a nawet zabić:
https://www.youtube.com/watch?v=5gBvyOEsz1o&feature=youtu.be

Oczekiwane działanie: Starałem się znaleźć filmik w którym ludzie targetują tego NPC, aby zobaczyć jak wygląda to u nich. Zobaczyłem trzy filmiki i w każdym nikt nie targetował Imagine of Loken - może to jest prawidłowe działanie, że nie można go targetnąć. Sprawdziłem też Wowhead i Openwow, ale brak informacji, na openwow jest tylko napisane, że powinien mieć 1lvl.
Działanie na logike: Skoro zostałem przemieniony w sługę, to NPC powinien być friendly, tak jak reszta NPc, które znajdują się w tym pomieszczeniu.

Co należy zrobić, aby odtworzyć ten błąd:

1. Wziąć quest [Put on Your Best Face for Loken]
2. Użyć quest item w miejscu GPS
3. Wejść do zaznaczonego pomieszczenia i nacisnąć piedestał

Linki WoWHead/OpenWoW:

1. http://wotlk.openwow.com/quest=12185
2. http://wotlk.openwow.com/npc=27212
3. http://wotlk.openwow.com/item=37071

Lokalizacja z koordynatów GPS (X, Y, Z, Map):
3430 -5317 277 571
https://zapodaj.net/456e5a8b7fe71.jpg.html

**Comment by NoobSunwell** [comment]
Będzie naprawione po update.
