### ISSUE TITLE
Upper Blackrock Spire ( UBRS )- Dragonspire hall " event "

### ISSUE THREAD

**Issue by Xanador** [NoobSunwell/Sunwell-BugTracker#328]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: 
Można od razu przechodzić do dalszych komnat.

**Obecne działanie**: TU WPISZ NA CZYM POLEGA PROBLEM
Po wejściu do Blackrock Spire, przejściu po schodach do góry na trafiamy na ścieżkę w lewo i prawo. Prawa strona nas nie interesuje. Po lewej stronie, są otwarte drzwi. Powinniśmy wejść do pokoju o nazwie " Dragonspire hall ". Tam również są drzwi, tylko że te są ciągle otwarte, a powinny być zamknięte.

**Oczekiwane działanie**: TU WPISZ JAK TO POWINNO WYGLĄDAĆ
Po wejściu do Blackrock Spire ( http://www.wowhead.com/zone=1583/blackrock-spire ) wchodzimy do pokoju: Hall of Blackhand. Następnie trzymając się lewej strony, wchodzimy przez otwarte drzwi do pokoju o nazwie: " Dragonspire Hall ". Tam spotykamy pare http://wotlk.openwow.com/npc=9096 ( co akurat się zgadza ) i pare małych pokoi z 
1. http://wotlk.openwow.com/npc=9818
2. http://wotlk.openwow.com/npc=9819
3. http://wotlk.openwow.com/npc=9817 ( co akurat też się zgadza ).
Lecz dopiero po ubiciu wszystkich tych mobów, drzwi prowadzące do następnego pokoju ( Hall of Binding ) powinny zostać otwarte. ( SS 3 )

**Co należy zrobić, aby odtworzyć ten błąd**:
1. Wejść do Blackrock Spire.
2. Wejść do pokoju o nazwie "Hall of Blackhand"
3. Z " Hall of Blackhand" skręcić w lewo i udać się do pokoju o nazwie " Dragonspire Hall ".
4. Drzwi wyjściowe są ciągle otwarte. ( Błąd )

**Linki WoWHead/OpenWoW**:
1. Blackrock Spire ( isntancja ): http://www.wowhead.com/zone=1583/blackrock-spire
2. http://wotlk.openwow.com/npc=9818   NPC które trzeba zabić, aby drzwi się otworzyły.
3. http://wotlk.openwow.com/npc=9819   NPC które trzeba zabić, aby drzwi się otworzyły.
4. http://wotlk.openwow.com/npc=9817   NPC które trzeba zabić, aby drzwi się otworzyły.

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
http://imgur.com/a/JSrSd

**Comment by NoobSunwell** [comment]
Będzie naprawione po update.
