### ISSUE TITLE
Upper Blackrock Deep Walka z bossem Warchief Rend Blackhand (Blackrock Stadium Event).

### ISSUE THREAD

**Issue by Xanador** [NoobSunwell/Sunwell-BugTracker#329]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Według 
( PS. jeśli chcesz to załączyć, ścisz sobie głośniki, muzyka na z początku może CI ranić uszy xD )
https://www.youtube.com/watch?v=0KeVyOxlKG4 ( 2:22 zaczyna się event )

**Obecne działanie**: 
Brakuje spawnów mobów, które powinny nas atakować. Oraz drzwi nie zamykają się za nami ( SS1 ). Na razie jest tylko jeden prawidłowy spawn. Dodatkowo NPC prawidłowo ze sobą rozmawiają. 

**Oczekiwane działanie**: 
Po przejściu przez bramę( SS1 ) i wejściu do pokoju o nazwie " Blackrock Stadium " Nefarius( http://wotlk.openwow.com/npc=10162 Chociaż nie jestem do końca pewny czy to ten NPC, innego na open wowie nie ma ... :x ) prawidłowo zaczyna event. Trzeba zacznaczyć, że brama, która wypuszcza Moby ( SS2 ) otwiera się w odpowiednim momencie, tylko że nie wypuszcza niczego ( nie wliczając 1szej fali, tylko ona działa ). 
Dodatkowo, gdy przychodzi koniec eventu i http://wotlk.openwow.com/npc=17027 chce się z nami rozprawić w pojedynkę, prawidłowo biegnie od Nefariana do miejsca w którym powinien zniknąć, lecz nie pojawia się już w formie z http://wotlk.openwow.com/npc=10339 ( siedząc na nim ). Gdy się pojawi, dokładnie w miejscu w którym zniknął, powinien powoli wyjść z bramy i zacząć nas atakować. Najpierw powinno się ubić mounta, następnie po ubiciu mounta drugi NPC powinien natychmiast zejść i zacząć atakować.

**Co należy zrobić, aby odtworzyć ten błąd**:
1. Wejśc do Blackrock Spire.
2. Dojść do miejsca o nazwie " Blackrock Stadium ".
3. Brama po rozpoczęciu się eventu nie zamyka się za nami.( ss1 )
4. Pojawia się tylko 1szy spawn. mobów od Nefariana.
5. Już nic innego w tym miejscu nie znajdziemy. 

**Linki WoWHead/OpenWoW**:
1. http://wotlk.openwow.com/npc=17027 NPC który siedzi na mouncie 
2. http://wotlk.openwow.com/npc=10339 MOUNT
3. Nefarius http://wotlk.openwow.com/npc=10162 ( prawdopodobnie :X )

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
http://imgur.com/a/ovVeq

**Comment by NoobSunwell** [comment]
Encounter przepisany - będzie dostępny po update.

**Comment by Xanador** [comment]
Wkradł się małe dwa błędy.
Moim zdaniem wszstko jest okej oskryptowane, tylko moby wybiegające z bram powinny wybiegać w momencie ubcia poprzedniej grupy.
Dodatkowo, po ubiciu wszystkich grup, wychodzi sam http://wotlk.openwow.com/npc=10339 , bez http://wotlk.openwow.com/npc=17027. :)
