### ISSUE TITLE
[QUEST] Investigate the Alchemist Shop ID: 1960

### ISSUE THREAD

**Issue by ThePuppetMaster** [NoobSunwell/Sunwell-BugTracker#33]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:
Quest ID: 1960
Mob ID: 6492
Quest Item ID: 7308, 7247, 7292
Class quest - Mage. Nie możliwy do ukończenia z powodu nieużywalności itemu 7247 na mobach 6492 w celu uzyskania itemu 7292.

**Obecne działanie**:
Po użyciu AoE skilli w celu 'ujawnienia' mobów, będących w invisibility, kiedy zbijamy je do 1hp nie otrzymują efektu 'stun'. Jeżeli zostanie użyty item 7308, zamiast AoE, po zbiciu moba do 1 hp efekt pojawia się na mobie. W obu przypadkach item 7247 jest nieużywalny na mobach, przez co nie powstaje pod nimi odpowiedni object, z którego (w wyniku jego braku) nie można podnieść itemu 7292, będącego koniecznym do ukończenia zadania.

**Oczekiwane działanie**:
Niezależnie od tego, czy użyty został 7308 czy AoE dmg, 'ujawnione' moby powinny otrzymywać stuna po zbiciu hp do 1. Item 7247 powinien być używalny na mobach zbitych do 1 hp i w efekcie zestunowanych i generować w miejscu moba object, po którego kliknięciu powinniśmy otrzymać item 7292.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Użyć AoE lub itemu 7308 w odpowiednim miejscu.
2. Zbić moba do 1 hp.
3. Użyć itemu 7247 na mobie z 1 hp.

**Comment by NoobSunwell** [comment]
Będzie naprawione po update.

**Comment by ThePuppetMaster** [comment]
Proszę o ponowne otwarcie. Quest jest możliwy do ukończenia, jednak kilka sekund po zbiciu moba, object pod jego nogami pojawia się samoczynnie, a nie po użyciu itemu 7247, co więcej 7247 jest nieużywalny nadal.
