### ISSUE TITLE
[quest] shutting down manaforge ara

### ISSUE THREAD

**Issue by turboszczur** [NoobSunwell/Sunwell-BugTracker#331]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Nie da się ukończyć questa.

**Obecne działanie**: Gdy jest odliczanie do końca pojawiają się addy potem przestają i nam przerywa odliczanie.
**Oczekiwane działanie**: Addy powinny się pojawiać i odliczanie powinno dojść do końca w miarę jak nie pozwalamy im przerwać go.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Wziąć i zrobić q.
2. 
3. 

**Linki WoWHead/OpenWoW**:

1. http://wotlk.openwow.com/quest=10323
2. http://wotlk.openwow.com/npc=20438
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

http://imgur.com/a/25G4s

**Comment by NoobSunwell** [comment]
![image](https://cloud.githubusercontent.com/assets/22621466/19620585/f7fcae9c-9880-11e6-9506-a88434c53726.png)

Musiałeś dopuścić gdzieś mobka na dłużej.

**Comment by turboszczur** [comment]
A nie włażą one w tekstury ? Bo robiłem to z vadrenem 3 razy i nie pykło.

**Comment by NoobSunwell** [comment]
Nope, idą normalnie z jednych lub drugich drzwi.

**Comment by NoobSunwell** [comment]
Może być tak, że NPC jest zabijany jeszcze na serwerze przed updatem - naprawiałem 3 konsole, możliwe, że to była ta trzecia, co była podatna na zabijanie gracza bądź przez NPC.
