### ISSUE TITLE
[Quest] Weapons of Destruction

### ISSUE THREAD

**Issue by ShatteredGlassx** [NoobSunwell/Sunwell-BugTracker#332]
Dowody: https://www.youtube.com/watch?v=Ksf3r_Ox9UI
https://www.youtube.com/watch?v=TkGRpOpNVeg

Obecne działanie: Po kliknięciu na  Unstable Explosives nie znika

Oczekiwane działanie: Po kliknięciu na Unstable Explosives, bomba powinna zmiknąć.

Co należy zrobić, aby odtworzyć ten błąd:

1. Wziąć quest Weapons of Destruction
2. Kliknąć na Unstable Explosives 
3. 

Linki WoWHead/OpenWoW:

1. http://wotlk.openwow.com/object=190590
2. http://wotlk.openwow.com/quest=12660
3. 

Lokalizacja z koordynatów GPS (X, Y, Z, Map):
6055 4490 -61 571
https://zapodaj.net/817e6f719cbf6.jpg.html

**Comment by ShatteredGlassx** [comment]
PS. Po kliknięciu na Unstable Exlosives nie możemy kliknąć ponownie, ale po około minucie można - to chyba zbyt szybko.

**Comment by NoobSunwell** [comment]
Będzie naprawione po update.
