### ISSUE TITLE
[ITEM] Elixir of Detect Undead

### ISSUE THREAD

**Issue by Ben1o** [NoobSunwell/Sunwell-BugTracker#333]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:Efekt elixiru znika po 1-2 sekundach

**Obecne działanie**: Elixir po wypiciu odpala buffa, jednak po 1-2 sekundach buff znika.

**Oczekiwane działanie**: Elixir powinien utrzymywać się przez godzine

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Zrobić/kupić elixir
2. Wypić go
3. 

**Linki WoWHead/OpenWoW**:

1. http://db.vanillagaming.org/?item=9154
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
nie dotyczy

**Comment by NoobSunwell** [comment]
Będzie naprawione po update.
