### ISSUE TITLE
[skill] survival

### ISSUE THREAD

**Issue by turboszczur** [NoobSunwell/Sunwell-BugTracker#334]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Dostałem nowego skilla z bety.

**Obecne działanie**: Przy nauczeniu się cookingu dostałem także survival skill który pochodzi z bety.
**Oczekiwane działanie**: Nie powinien być osiągalny.
**Co należy zrobić, aby odtworzyć ten błąd**:

1. Nauczyć się cookingu.
2. 
3. 

**Linki WoWHead/OpenWoW**:

1. http://wow.gamepedia.com/Survival_Skills
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

https://postimg.org/gallery/18qduaxv0

**Comment by NoobSunwell** [comment]
Będzie naprawione po update.
