### ISSUE TITLE
[Quest] Returning The Favor

### ISSUE THREAD

**Issue by Kougraa** [NoobSunwell/Sunwell-BugTracker#335]
**Opis**: W queście Returning The Favor mamy za zadnie zabić Warmaul Ogry i postawić na nich baner. 
https://youtu.be/gwOGSvr71Ww

**Obecne działanie**: Po zabiciu Warmaul Ogrów - nie na każdym Ogrze mamy możliwość postawienia banera. Na początku była myśl - trzeba stanąć w odpowiednim miejscu, aby użyć banera. Jednak problem tkwi w czym innym.

**Oczekiwane działanie**: Po zabiciu gra gracz powinien mieć możliwość pozostawienia banera na każdym z Warmaul Ogrów.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Wziąć quest od NPC.
2. Iść w wyznaczone miejsce i zabić Warmaul Ogra.
3. Użyć qitemu.

**Linki WoWHead/OpenWoW**:

1. [Quest] http://www.wowhead.com/quest=9931/returning-the-favor
2. [Qitem] http://www.wowhead.com/item=25555/kilsorrow-banner
3. [Ogry] http://wotlk.openwow.com/npc=18064 , http://wotlk.openwow.com/npc=17138

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
http://imgur.com/3bV989L

**Comment by NoobSunwell** [comment]
Będzie naprawione po update.
