### ISSUE TITLE
[NPC] Zagubiony Corki

### ISSUE THREAD

**Issue by Kougraa** [NoobSunwell/Sunwell-BugTracker#336]
**Opis**: Zadziwiające, że ten NPC jest w tylu miejscach :D
NPC pomimo zamknięcia w klatce ma możliwość atakowania i podążania za graczem.

**Obecne działanie**: NPC znaleziony w 3 miejscach - dwa przypadki w klatkach z których mogą atakować gracza. Jeden przypadek w którym NPC stoi w miejscu - nie atakując.
https://youtu.be/acvbAWL9eDs
https://youtu.be/foTkhIldbBE
https://youtu.be/UoXqrqXdUkI

**Oczekiwane działanie**: NPC zamknięty w klatce-nie powienien z niej wychodzić oraz powinien być w miejscu dla niego przeznaczonym. 

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Odnaleźć NPC.
2. 
3. 

**Linki WoWHead/OpenWoW**:

1. http://www.wowhead.com/npc=18369/corki
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
http://imgur.com/i4jrDTM
http://imgur.com/6sIzmTq
http://imgur.com/lrh0wOw

**Comment by NoobSunwell** [comment]
http://www.wowhead.com/search?q=corki#npcs

To 3 różne NPC są.

**Comment by NoobSunwell** [comment]
Tak czy siak - ten NPC to idealna definicja łajzy. Łajza będzie naprawiona po update - nie będzie wychodzić z klatki. Wszystkie 3 wersje.
