### ISSUE TITLE
[NPC] Zawzięty Kurenai Captive.

### ISSUE THREAD

**Issue by Kougraa** [NoobSunwell/Sunwell-BugTracker#338]
**Opis**: Agresywny NPC i brak możliwości ataku.

**Obecne działanie**: Gracz nie ma możliwości ataku NPC.

**Oczekiwane działanie**: Gracz powinien mieć możliwość ataku NPC.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Odnaleźć NPC.
2. Próbować go zaatakować.
3. 

**Linki WoWHead/OpenWoW**:

1. http://wotlk.openwow.com/npc=18209
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
http://imgur.com/U1t5Mja

**Comment by NoobSunwell** [comment]
Będzie naprawione po update.
