### ISSUE TITLE
move/v mapy - "latajace" mobe

### ISSUE THREAD

**Issue by Rzuuf** [NoobSunwell/Sunwell-BugTracker#34]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: 1 moby nie chce wejsc na poziom wyzszy nawet o milimetr
oraz 2 moby wciaz maja niewidzialne schody, padaja w powietrzu - nie mozna ich lootowac

**Obecne działanie**: jak wyzej

**Oczekiwane działanie**: moby powinny pokonywac pagorki itp

**Co należy zrobić, aby odtworzyć ten błąd**:

1. sprobowac zaatakowac moba z ranged weapon/spella, znajdujac sie na pagorku lub w jaskini (kiedy mob jest poza jaskinia)
2.  zaatakowac moba (ktory ucieka na low hp) w poblizu innego moba ktory znajduje sie wyzej/na gorce itp a nastepnie obserwowac co sie dzieje kiedy mob ma low hp i ucieka
3. 

dowody: https://www.youtube.com/watch?v=zp264zMppbY&feature=youtu.be
https://youtu.be/y9r8F4Ny1dE
https://youtu.be/MtqxZc8VXHI

**Comment by vadren** [comment]
Dodaj ID mobków i coordy gdzie to występuje co ułatwi robotę devom.

**Comment by leman1991** [comment]
błąd nagminny, pojawia się praktycznie wszędzie gdzie są nierówności terenu

**Comment by vadren** [comment]
Ale tak czy siak trzeba by podać te coordy i ID mobka.

**Comment by nexx94** [comment]
Z lokacji The Sludge Fen w The Barrens
https://www.youtube.com/watch?v=ys-g4AGB3BY&feature=youtu.be

**Comment by vadren** [comment]
Coordy zdobędziesz chociażby TomTomem lub Carbonite'm.

**Comment by NoobSunwell** [comment]
Duplikat https://github.com/NoobSunwell/Sunwell-BugTracker/issues/19
