### ISSUE TITLE
QUEST - K3 - Clean Up

### ISSUE THREAD

**Issue by microjp** [NoobSunwell/Sunwell-BugTracker#340]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:w queście chodzi o to by pozbierać leżące na ziemi części statku

**Obecne działanie**: Części statku nie da się podnieść

**Oczekiwane działanie**: powinniśmy móc zebrać części i oddać questa po zebraniu 10 sztuk Charred Wreckage

**Co należy zrobić, aby odtworzyć ten błąd**:

1. wziąć questa
2. spróbować zebrać quest itemy
3. 

**Linki WoWHead/OpenWoW**:

1. http://www.wowhead.com/object=191530/charred-wreckage - obiekty
2. http://www.wowhead.com/item=40603/charred-wreckage - quest itemy
3. http://www.wowhead.com/quest=12818/clean-up - quest

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
http://imgur.com/a/Gg7IK

**Comment by microjp** [comment]
Coś się naprawiło i już działa teoretycznie

**Comment by NoobSunwell** [comment]
![image](https://cloud.githubusercontent.com/assets/22621466/19622086/059738da-98a2-11e6-9472-f9f4444d987f.png)

Czy nie jesteś przypadkiem w grupie rajdowej? Bo widzę napisz "Group 1".

**Comment by microjp** [comment]
hehe no właśnie dla tego napisałem komentarz :D
