### ISSUE TITLE
[quest] death's challenge

### ISSUE THREAD

**Issue by turboszczur** [NoobSunwell/Sunwell-BugTracker#341]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Nie mogę atakować innych dk podczas duela.

**Obecne działanie**: Nie można atakować npców podczas duela.

**Oczekiwane działanie**: Powinni być atakowalni.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Wziąć i zrobić questa.
2. 
3. 

**Linki WoWHead/OpenWoW**:

1. http://wotlk.openwow.com/quest=12733
2. http://wotlk.openwow.com/npc=28392
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

http://imgur.com/a/5Mv1n

**Comment by NoobSunwell** [comment]
Będzie naprawione po update.
