### ISSUE TITLE
[Rogue] Vanish.

### ISSUE THREAD

**Issue by kovaq** [NoobSunwell/Sunwell-BugTracker#344]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Zaznacze, ze jest to moje zdanie, ale jest ono subiektywne, jako ze to moja klasa.
Mianowicie, Vanish rogala powinien "zjadac" wszystko co w niego leci jako resist, jezeli zostal wycastowany po cascie innego spell,a np wratha, ice lance'a etc.
Jest to swego rodzaju trick stosowany przez rogali w pvp.
Tutaj on nie dziala.
https://youtu.be/lTth9VKhLQM
Dodatkowo znalazlem podobny temat, lecz tam zostal on odrzucony, podejrzewam, ze przez nieprawidlowe zgloszenie, aczkolwiek skomentowal to pewien czlowiek, ktorego slowa rozumiem jako potwierdzenie moich.
https://github.com/TrinityCore/TrinityCore/issues/16225
W tamtym temacie filmik pokazuje resist spella, ale wyjecie ze stealtha, ja pokazuje nie dosc ze wyjecie ze stealtha to jeszcze otrzymanie obrazen.

**Obecne działanie**: Vanish nie "polyka" spelli.

**Oczekiwane działanie**: Kazdy spell, ktory zaczal lot przed wycastowaniem vanisha, po jego wycastowaniu powinien zostac zresistowany i zachowac rogue'a w povanishowym efekcie "Improved Stealth".

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Czekac na cast przeciwnika.
2. W momencie rzucenia czaru uzyc vanisha.
3. Obserwowac.

**Linki WoWHead/OpenWoW**:

1. http://wotlk.openwow.com/spell=26888
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
nie dotyczy.

**Comment by nexx94** [comment]
https://www.youtube.com/watch?v=qvnoJeAT_yc
http://www.arenajunkies.com/topic/64325-rogue-how-to-vanish-serious-question/
Żadne twarde dowody to nie są, ale w przypadku za wczesnego vanisha death coil/inne lecące spelle wybijają ze stealth, trzeba by pewnie zobaczyć czy późniejszy vanish by coś dał, bo powinien umożliwić uniknięcie spella.

**Comment by kovaq** [comment]
https://youtu.be/3uWirkX0STE
Dziala, tylko margines poprawnosci jest strasznie zawezony. Ale mniej dobrych rogali bedzie przynajmniej :P
https://youtu.be/IqyURZQJOfk
Sprawdzony rowniez absorb podczas vanisha. Dziala jak nalezy.

i dodatkowo dorzucam gouge z talentami przedluzajacymi mozliwosc rozdzielenia walki (off combat)
https://youtu.be/BKR0rHdW7Hs rowniez dziala, oba schodza na styk.

Zamykam temat, skoro wszystko sie wyjasnilo.
