### ISSUE TITLE
[NPC] Maigra Keenfeather

### ISSUE THREAD

**Issue by kovaq** [NoobSunwell/Sunwell-BugTracker#347]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Brak Flying trainera w Valiance Keep. 
http://screenshooter.net/102844212/soevlpx

**Obecne działanie**: Brakuje Flying Trainera.

**Oczekiwane działanie**: Powinna stac zaraz za flymasterem, przy czerwonym i zielonym gryfie, na swoim, fioletowym.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Zawitac do Valiance Keep.
2. Podejsc do miejsca, gdzie powinna stac.
3. 

**Linki WoWHead/OpenWoW**:

1. http://www.wowhead.com/npc=35133/maigra-keenfeather
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
http://screenshooter.net/102844212/soevlpx

**Comment by nexx94** [comment]
Dodany w patchu 3.2.0.
http://forum.sunwell.pl/viewtopic.php?f=64&t=435
Administracja się wypowiedziała w sprawie dodawania flight masterów w hellfire, sądzę że w north będzie podobnie.
