### ISSUE TITLE
[MMAPS] Ghostlands mobs evading

### ISSUE THREAD

**Issue by ThePuppetMaster** [NoobSunwell/Sunwell-BugTracker#35]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:
W zależności od odległości od moba, moby potrafią evadeować od razu, lub po chwili cofać się i evadeować. Przypadki są bardzo liczne w rożnych miejscach w Ghostlands, generalnie mobów jest na tyle dużo, że ciężko wypisać wszystkie cordy. Zaobserwowane póki co w: Suncrown Village, wioska trolli obok Dawnstar Spire, beasty przy moście z Eversong do Ghostlands, ghule obok Thomber's Supplies, Sanctum of the Moon, An'daroth

**Obecne działanie**:
W zależności od odległości od moba, moby potrafią evadeowac od razu, lub po chwili cofać się i evadeować.

**Oczekiwane działanie**:
Moby powinny dobiec do gracza, zamiast evadeować.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Atakować moby w w/w miejscach z odległości większej niż melee range.

**Comment by NoobSunwell** [comment]
Poproszę o ID i koordynaty przykładowych mobków.

**Comment by nirvaaa** [comment]
Miałem to samo z mobkiem w loch modan

**Comment by ThePuppetMaster** [comment]
16347 - 50, 12
16313 - 59, 11 / 57, 12
16340 - 73, 11 / 75, 11
16330 - 35, 11
16322 - 33, 26
16304 - 34, 31

**Comment by NoobSunwell** [comment]
Duplikat https://github.com/NoobSunwell/Sunwell-BugTracker/issues/19
