### ISSUE TITLE
[NPC] Rotting Ancestor

### ISSUE THREAD

**Issue by vadren** [NoobSunwell/Sunwell-BugTracker#36]
**Opis**: NPC o ID 1530 w Tirisfal Glades w podziemiach na coordach 52.7 26.0 nie można zaatakować i tak samo ten gracza nie widzi.

**Obecne działanie**: NPC nie reaguje na nic, nawet przejście obok niego.

**Oczekiwane działanie**: NPC powinno dać się zaatakować + przy przejściu obok niego powinien nas zacząć atakować

**Co należy zrobić, aby odtworzyć ten błąd**:

1.  Wejść w podane wyżej podziemia na północy Tirisfal Glades.
2.  Podejść do NPC, który stoi od schodów na lewo (jeden NPC, a z prawej jest ich kilka).
3.  Spróbować go zaatakować, przejść obok niego.

**Comment by NoobSunwell** [comment]
Powinno być naprawione po restarcie.
