### ISSUE TITLE
[Instancja] Ahn'Kahet: The Old Kingdoms - watcher corpse

### ISSUE THREAD

**Issue by kovaq** [NoobSunwell/Sunwell-BugTracker#368]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Q item do daily, na zebranie i spalenie ciala watchera, ktory dropi z pierwszych mobow mozna dropic do woli, nawet jak juz sie ma. Zaznacze, ze item jest unique wiec i tak sie go nie podniesie, lecz spam blokuje skinning, dodatkowo jezeli ktos uzna, ze brakuje mu czasu to wywali stare cialo i wezmie nowe, ze swiezszym timerem, a nie o to chodzi w tym q.

**Obecne działanie**: Q item pojawia sie w kazdym zabitym mobku.

**Oczekiwane działanie**: Po zebraniu jednego, kazdy kolejny q item powinien pojawic sie dopiero, gdy timer poprzedniego sie skonczy i owy przedmiot zniknie.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Wejsc do Ahn'Kahet.
2. Zabic pierwsze moby z wejscia.
3. Zebrac q item.
4. Zabic kolejne moby i w loocie dalej widziec ten item.

**Linki WoWHead/OpenWoW**:

1. http://www.wowhead.com/item=43494/ahnkahar-watchers-corpse
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
Ahn'Kahet: The Old Kingdom

**Comment by NoobSunwell** [comment]
Loot jest generowany w chwili zabicia, nie otworzenia mobka - tak samo jest na globie. Więc jeżeli kilka NPC może dropić ten item - i zabijesz wszystkie, które je dropią - to każdy może mieć potem go w sobie, bo nie miałeś tego itemu podczas zabijania.

Właśnie robię questy na Legionie - taka sama sytuacja jest na worldzie - też blokuje skinning, też wkurwia :/

**Comment by kovaq** [comment]
Problem w tym, ze najpierw zabilismy jednego, potem wipe, zebralem item, a nastepnie zabilismy kolejne, w ktorych to cialo bylo.

Stad cale to zgloszenie. Bo ta duracja jakby przeszkadza w blokadzie respawnu q itemku.

Nie zglaszalbym tak banalnego problemu, jak to co zrozumiales z mojej wypowiedzi, bo to co mowisz zdarzylo mi się nie raz zarowno na wotlku, jak i rowniez na globie, na legionie i zdecydowanie nie o to mi chodzilo. ;)

**Comment by NoobSunwell** [comment]
Ok, powinno być naprawione po update.
