### ISSUE TITLE
QUEST: Learn to Ride 

### ISSUE THREAD

**Issue by Xanador** [NoobSunwell/Sunwell-BugTracker#37]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: 
Po wbiciu 20 poziomu, każdy gracz powinien otrzymać maila, w którym będzie napisane, że może nauczyć się jeździć konno ( To jest ) i w którym będzie quest, pozwalający dowiedzieć się, gdzie ma iść po mounty.

**Obecne działanie**: TU WPISZ NA CZYM POLEGA PROBLEM
Brakuje questa w mailu.

**Oczekiwane działanie**: TU WPISZ JAK TO POWINNO WYGLĄDAĆ
Powinniśmy otrzymać maila a w nim zadanie na jeżdżenie konno.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Wbić 20 poziom.
2. Przejść się do skrzynki.
3. Zobaczyć, że nie ma zadania.
4. Sprawdzone na Taurenie, ale wolałem opisać każdą rasę.

1: Quest Learn to Ride. Podpisy niżej.
1a:  http://wotlk.openwow.com/quest=14082
1b:   http://wotlk.openwow.com/quest=14085
1c:   http://wotlk.openwow.com/quest=14083
1d:   http://wotlk.openwow.com/quest=14084
1e:   http://wotlk.openwow.com/quest=14088
1f:   http://wotlk.openwow.com/quest=14079
1g:   http://wotlk.openwow.com/quest=14087
1h:   http://wotlk.openwow.com/quest=14086
1i:   http://wotlk.openwow.com/quest=14089
1j:   http://wotlk.openwow.com/quest=14081

2: Item który powinniśmy otrzymać w skrzynce po wbiciu 20lvl:Tutaj zaraz opiszę.
2a:   http://wotlk.openwow.com/item=46879
2b:   http://wotlk.openwow.com/item=46876
2c:   http://wotlk.openwow.com/item=46877
2d:   http://wotlk.openwow.com/item=46878
2e:   http://wotlk.openwow.com/item=46883
2f:   http://wotlk.openwow.com/item=46875
2g:   http://wotlk.openwow.com/item=46884
2h:   http://wotlk.openwow.com/item=46880
2i:   http://wotlk.openwow.com/item=46881
2j:    http://wotlk.openwow.com/item=46882

A= Dranei
B= Nonce Elfy
C= Krasnoludy
D= Gnomy
E= Trole
F= Ludzie
G= Taureny
H= Orkowie
I= Nieumarlacy
J= Krwawe Elfy

**Comment by NoobSunwell** [comment]
Quest dodany w patchu 3.2
