### ISSUE TITLE
[17604] Sunhawk Spy

### ISSUE THREAD

**Issue by Hehedzki** [NoobSunwell/Sunwell-BugTracker#38]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Mobki tracą aggro, jakby hamowała je niewidzialna ściana

**Obecne działanie**: Mobki tracą aggro, jakby hamowała je niewidzialna ściana. Problem dotyczy prawie wszystkich mobków z taką nazwą. https://www.youtube.com/watch?v=NerkhyqAcbE
**Oczekiwane działanie**: Mobki powinny zachowywać się normalnie i nie uciekać po przebiegnięciu 30yd

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Pullnąć te mobki na dłuższą odległość.
2. 
3.

**Comment by NoobSunwell** [comment]
Zgłoszenie niepoprawne - brak ID, koordynatów.

**Comment by NoobSunwell** [comment]
Duplikat https://github.com/NoobSunwell/Sunwell-BugTracker/issues/19
