### ISSUE TITLE
[Quest] Shadow Vault Decree

### ISSUE THREAD

**Issue by Bronchosol** [NoobSunwell/Sunwell-BugTracker#386]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Quest polegający na odczytaniu jakiegoś tam dekretu, po czym przystąpieniu do walki z Thane Ufrang the Mighty i pokonaniu go**:

**Obecne działanie**: Po spełnieniu warunków czyli wybiciu wszystkich innych dookoła (nie można być w combat), upewnieniu się, że Thane Ufrang the Mighty siedzi - klikam dekret aby go odczytać lecz pojawia się komunikat, że Thane Ufrang the Mighty musi być obecny i musi siedzieć przez co nie można wykonać questa, mimo spełnienia warunków.

**Oczekiwane działanie**: Odczytujemy dekret przed siedzącym Thane Ufrang the Mighty, coś tam gada i przystępujemy do walki. Po pokonaniu powinno zaliczyć questa ( Thane Ufrang the Mighty slain)

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Dojść do Shadow Vault
2. Stanąć przed Thane Ufrang the Mighty
3. Kliknąć na item Shadow Vault Decree

**Linki WoWHead/OpenWoW**:

1. http://www.wowhead.com/quest=12943/shadow-vault-decree
2. http://wotlk.openwow.com/quest=12943

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
http://imgur.com/WFFynlo

**Comment by nexx94** [comment]
Zrobiłem bez większych problemów, wystarczy stanąć nieco dalej od niego (na oko 15-20 yardów przed nim)

**Comment by Bronchosol** [comment]
Faktycznie, odległość musi być zdecydowanie dalsza niż na screenie. Hmm... dałbym sobie rękę uciąć, że wcześniej tak próbowałem. No cóż, temat nieaktualny.

**Comment by nexx94** [comment]
W takim razie możesz zamknąć zgłoszenie, masz tą opcję przy comment na dole.
Na wszelki wypadek:
https://imgur.com/a/ozNqn
