### ISSUE TITLE
Burst ilości many po złamaniu zasady 5 sekund

### ISSUE THREAD

**Issue by leman1991** [NoobSunwell/Sunwell-BugTracker#39]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Burst ilości many po złamaniu zasady 5 sekund

**Obecne działanie**: PRZYKŁAD:
 mp 30%, 5 sec i mana rośnie powoli do 50% (start cast) i burst mp do 70%
nie wiem czy tak jest na innych postaciach/poziomach itp ale u mnie bug powtarzalny zawsze
różni się ilość mp w tym "burście", zwykle między 10 a 20% max mp
Night elf priest lvl 3 Lemans

https://vid.me/KrcE - nagranie pokazujące buga

**Oczekiwane działanie**: Po złamaniu zasady 5 sekund nie powinna pojawiać się żadna dodatkowa ilość punktów mp.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Przy małej ilości many u postaci bez talentu/skilla pozwalającego na regenerację many w trakcie castowania zatrzymać cast na 5 sekund - mana powoli zaczyna rosnąć w stałym tempie
2. Zapamiętać ile masz many i wycastować cokolwiek - pojawia się kilka/kilkanaście % max mp więcej (efekt jakby przy starcie castowania użyto mp potiona)

**Comment by leman1991** [comment]
Podobna sytuacja, gdy zmieniasz target podczas regeneracji many w tych 5+ sekund poza castowaniem

**Comment by NoobSunwell** [comment]
Ten "burst" to błąd wizualny klienta. Postaci do lvl 15 otrzymują zwiększoną regenerację many - dodatkowy burst wynika również z zwiększonej regeneracji mp5 na tych levelach - który w kliencie jest odświeżany co X sekund.
