### ISSUE TITLE
[NPC]brak

### ISSUE THREAD

**Issue by angelikasol** [NoobSunwell/Sunwell-BugTracker#391]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:wg mnie brakuje npcow od wszystkich profesji 

**Obecne działanie**: brak npców

**Oczekiwane działanie**: powinni stać w niszach, w obydwu budyneczkach po lewej i prawej stronie od windy

**Co należy zrobić, aby odtworzyć ten błąd**:

1. polecieć tam i zobaczyć
2. 
3. 

**Linki WoWHead/OpenWoW**:

1. nie potrafię wszystkich npców zlokalizować na wowhedzie
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
https://zapodaj.net/df8106c7db27e.jpg.html
https://zapodaj.net/fcd9b4d421203.jpg.html

**Comment by nexx94** [comment]
A wybrałeś aldorów? Trzeba chyba dla nich zrobić chaina żeby NPC do nauki profek pojawili się w tym miejscu, wcześniej będą w neutralnej części miasta.

**Comment by angelikasol** [comment]
nie wybrałam bo nie zajmuje się sprawdzaniem tego przez przypadek tak wylądowalm a npce zawsze tam stali bez wzgledu na zrobionego chaina

**Comment by angelikasol** [comment]
wybiore aldorow i sprawdze to jutro

**Comment by NoobSunwell** [comment]
A czy te NPC nie były dodane w 3.1 lub później?

**Comment by angelikasol** [comment]
sprawdzilam, po zrobieniu q na wybor reputacji skyers/aldor nadal npcow brak, niewiem kiedy byly dodane to jest tbc zatem chyba powinny byc

**Comment by NoobSunwell** [comment]
http://www.wowhead.com/npc=33675/onodo - przykładowy - dodany w 3.1 - proszę sprawdzić przynajmniej następnym razem.
