### ISSUE TITLE
Brak informacji o dropie quest itemu z mobka / 3 questy

### ISSUE THREAD

**Issue by Vevee** [NoobSunwell/Sunwell-BugTracker#4]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:  Brak informacji o dropie quest itemu z mobka, dotyczy questow: 
http://wotlk.openwow.com/quest=33
http://wotlk.openwow.com/quest=6
http://wotlk.openwow.com/quest=18

**Obecne działanie**:   1   http://ifotos.pl/z/arehrss      2  http://ifotos.pl/z/arehrsq       3   http://ifotos.pl/z/arehrar

**Oczekiwane działanie**: Po najechaniu kursorem na target powinna pojawic sie informacja o dropie danego q itemu.

**Co należy zrobić, aby odtworzyć ten błąd**:  

1. Wziasc questa najechac kursorem na moba.

**Comment by vadren** [comment]
To samo quest Rite of Strength
http://wotlk.openwow.com/quest=757

https://zapodaj.net/images/2351b601cf173.jpg

**Comment by NoobSunwell** [comment]
Powinno działać po aktualizacji.

**Comment by NoobSunwell** [comment]
PS: Bym zapomniał - wymagane usunięcie Cache w tym przypadku.
