### ISSUE TITLE
[Mapa/agro]

### ISSUE THREAD

**Issue by nirvaaa** [NoobSunwell/Sunwell-BugTracker#40]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Miejsce, w którym z jakiegoś powodu mobu się resetują.

**Obecne działanie**: Zawieszenie się moba i reset.

**Oczekiwane działanie**: Normalne gonienie.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Pullnąć moba,
2. Wprowadzić go w podane miejsce. https://s21.postimg.org/u94gv9puv/image.jpg, https://s22.postimg.org/hmccvs57l/image.jpg
3. https://s12.postimg.org/5dl1k9ost/image.jpg

**Linki WoWHead/OpenWoW**:

1. 
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by NoobSunwell** [comment]
1. Duplikat.
2. Brak koordynatów.
3. Brak linków.
