### ISSUE TITLE
[QUEST] A favor for Evershine

### ISSUE THREAD

**Issue by Hoyoga** [NoobSunwell/Sunwell-BugTracker#41]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:Brak jakiejkolwiek reakcji na obrażenia

**Obecne działanie**: Po zaatakowaniu pewnego moba(nie każdego) nie reaguje, nie dostaje obrażeń oraz nie rusza się

**Oczekiwane działanie**: Po rzucieniu zaklęcia powininen zareagować i stracić daną liczbę zdrowia

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Zaatakować moba potrzebnego do questu
2. 
3. 

**Linki WoWHead/OpenWoW**:

1. http://www.wowhead.com/quest=319/a-favor-for-evershine
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
http://imgur.com/a/q2Fz6

**Comment by NoobSunwell** [comment]
Duplikat https://github.com/NoobSunwell/Sunwell-BugTracker/issues/19
