### ISSUE TITLE
[NPC] Gnarlpine Pathfinder

### ISSUE THREAD

**Issue by turboszczur** [NoobSunwell/Sunwell-BugTracker#42]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Mój pet oraz w/w osobnik stoczyli wspaniałą walkę w powietrzu.

**Obecne działanie**: Nie powinni chodzić w powietrzu

**Oczekiwane działanie**: Powinni łazić po ziemi jak każdy porządny obywatel

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Udać się w miejsce wskazane w screenie z koordynatami
2. Zaatakować w/w npca i pochodzić trochę z nim i z petem najlepiej
3. Podziwiać podniebne stacie

**Linki WoWHead/OpenWoW**:

1. http://wotlk.openwow.com/npc=2012
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

W screenshocie nr 2

 Screenshoty: http://imgur.com/a/Jd1KY

**Comment by NoobSunwell** [comment]
Nie byłem w stanie tego zweryfikować u siebie - to oznacza, że przypadek był jednorazowy, ewentualnie bedzie naprawione po aktualizacji. Na screenshotcie nr. 2 nie widać koordynatów z komendy GPS gdzie miał miejsce błąd (jest tylko na ss 1).
