### ISSUE TITLE
[Mmaps] Fargodeep Mine 

### ISSUE THREAD

**Issue by arecky** [NoobSunwell/Sunwell-BugTracker#43]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Może coś ze spawnem jest nie tak, ale - jak widać na załączonym obrazku - w centralnej części kopalni jest Kobold Tunneler, którego nie da się zaatakować, ponieważ albo jest 'Too far away' albo 'Target not in line of the sight'. Link do moba oraz screen poniżej.

**Obecne działanie**: Mob nie atakuje, nie można go zaatakować, jest poza zasięgiem lub poza dostępną ścieżką.

**Oczekiwane działanie**: Mob prawdopodobnie powinien stać na powierzchni kopalni, poziom wyżej, co sugerowałaby jego specyfika występowania.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Udać się do Fargodeep Mine.
2. 
3. 

**Linki WoWHead/OpenWoW**:

1. http://wotlk.openwow.com/npc=475
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
X: 40.79  Y: 81.02
![wowscrnshot_101216_155232](https://cloud.githubusercontent.com/assets/22777051/19312998/2f03a5e2-9095-11e6-8229-07dc25999429.jpg)

**Comment by vadren** [comment]
1. Obecne działanie:  Przy atakowaniu NPC o ID 1538 z kilku yardów nie można go zaatakować (Evade) wtedy kiedy chodzi po wzgórzu. Dopiero po podejściu zaczyna się combat.

Oczekiwane działanie: powinno dać się atakować NPC obojętnie od tego w jakim miejscu się znajduję (wzgórze - czysty teren)

Co należy zrobić, aby odtworzyć ten błąd:
Spróbować zaatakować NPC z niedużej odległości

Coordy
https://zapodaj.net/b7b78b6daa0e5.jpg.html

2. Obecne działanie: 
Przy atakowaniu NPC o ID 1537 z wzgórza naprzeciw (coordy na SS'ie) ten idzie w dziwny sposób przesuwając się minimalnie w lewo i prawo i nawet cofając ostatecznie dochodząc do celu.

Oczekiwane działanie: 
NPC powinien naturalnie zejść z wzgórza i podejść pod kolejne do gracza.

Co należy zrobić, aby odtworzyć ten błąd:
Zaatakować NPC z drugiego wzgórza (naprzeciw)

Coordy:
https://zapodaj.net/2a428831b4be7.jpg.html

**Comment by vadren** [comment]
III. Obecne działanie: 
Przy atakowaniu NPC o ID 1537 i 1538 przed wzgórzem na podanych coordach  ci podchodzą do gracza w locie i tak zostają

Oczekiwane działanie: 
NPC powinien stać na ziemii

Co należy zrobić, aby odtworzyć ten błąd:
Zaatakować NPC z podanego w coordach miejsca.

Coordy:
https://zapodaj.net/ec8dc847f561e.jpg.html

**Comment by vadren** [comment]
3255
IV. Obecne działanie: 
Przy atakowaniu NPC o ID 3255 tego nie da się zaatakować z pewnej odległości od podanych coordów. Dopiero przy bezpośrednim starciu można go zaatakować.

Oczekiwane działanie: 
NPC powinien dać się zaatakować.

Co należy zrobić, aby odtworzyć ten błąd:
Zaatakować NPC z niedalekiej od podanych coordów miejsca.

Coordy:
https://zapodaj.net/13bea0dc5e52f.jpg.html

**Comment by NoobSunwell** [comment]
Pierwszego postu nie mogę potwierdzić - u mnie wszystko było ok. Pozostałe - https://github.com/NoobSunwell/Sunwell-BugTracker/issues/19
