### ISSUE TITLE
[Achievement] Explore Mulgore zbugowana jedna z lokalizacji

### ISSUE THREAD

**Issue by Extrala** [NoobSunwell/Sunwell-BugTracker#44]
Opis:Brak możliwości zdobycia achevementu "Explore Mulgore"

Obecne działanie: Brak reakcji na exploracje jaskini do achevementu

Oczekiwane działanie: Przy głębszym wejściu do jaskini powinien się zaliczyć podpunkt z Explore Mulgore mianowicie -Palemane Rock

Co należy zrobić, aby odtworzyć ten błąd:

1. Odkryć wszystkie lokalizacje z Achievementu "Explore Mulgore" oraz zwiedzić całą jaskinie Palemane Rock

Linki WoWHead/OpenWoW**:
1. http://www.wowhead.com/achievement=736/explore-mulgore
2. http://www.wowhead.com/zone=818/palemane-rock

Lokalizacja z koordynatów GPS (X, Y, Z, Map): 
X:-2240.365234 Y:223.174240 Z:52.272392
https://postimg.org/image/5agfvzg1h/

**Comment by Extrala** [comment]
Bug odkryty oczywiście podczas expienia !

**Comment by NoobSunwell** [comment]
![image](https://cloud.githubusercontent.com/assets/22621466/19319816/f1ebeb00-90ae-11e6-8088-1113e1d44173.png)

Po teleportacji pod podane koordynaty zaliczyło mi eksplorację.

**Comment by NoobSunwell** [comment]
Możliwy był bug po stronie serwera - więc jeżeli innym tez nie działa - to zadziała po aktualizacji.
