### ISSUE TITLE
[Quest] The Woodland Protector part 2, złe wyświetlanie ID: 459

### ISSUE THREAD

**Issue by angelikasol** [NoobSunwell/Sunwell-BugTracker#45]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:

**Obecne działanie**: problem polega na nieprawidłowym wyświetlaniu, po najechaniu kursorem myszy na mobka wyświetla się nazwa questa

**Oczekiwane działanie**: powinna wyświetlac się nazwa q itemu jaki dropi z tego mobka: Fel Moss

**Co należy zrobić, aby odtworzyć ten błąd**:

1. nakierować kursorem na mobka
2. 
3. 

**Linki WoWHead/OpenWoW**: 

1. http://wotlk.openwow.com/npc=1989
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
https://zapodaj.net/406f2531b34a5.jpg.html

**Comment by NoobSunwell** [comment]
Brak ID questa, brak wyniku komendy GPS.

**Comment by NoobSunwell** [comment]
![image](https://cloud.githubusercontent.com/assets/22621466/19367891/98533c5c-919d-11e6-8282-3a26cd9714c8.png)
U mnie działa bez zarzutu - opróżnij cache. Jak dalej będzie to samo - zaczekaj do update i znów opróżnij.
