### ISSUE TITLE
[Quest] Shadow Vault Decree.

### ISSUE THREAD

**Issue by Kougraa** [NoobSunwell/Sunwell-BugTracker#458]
**Opis**: Gracz ma za zadanie odczytać dektet, po czym stoczyć walkę z Thane Ufrang the Mighty'm.
http://imgur.com/FawyJPc

**Obecne działanie**: Mimo, iż gracz stoi przed NPC, bez combatu, a bos jest w bezruchu - quest item nie działa.
https://youtu.be/XuALI12RxnE

**Oczekiwane działanie**: Gracz powinien mieć możliwość odczytania dektretu stojąc przed NPC. Qitem powinien działać.
https://youtu.be/zNPsDeTah7M

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Wziąć quest.
2. Odnaleźć NPC.
3. Próbować użyć qitemu stojąc przed NPC.

**Linki WoWHead/OpenWoW**:

1. [Quest] http://www.wowhead.com/quest=12943/shadow-vault-decree
2. [Qitem] http://www.wowhead.com/item=41776/shadow-vault-decree
3. [NPC] http://www.wowhead.com/npc=29919/thane-ufrang-the-mighty

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
http://imgur.com/TADin46

**Comment by nexx94** [comment]
https://github.com/NoobSunwell/Sunwell-BugTracker/issues/386

**Comment by Kougraa** [comment]
Rzeczywiście, można użyć qitemu kawałek dalej.
Zamknę, jednak według mnie odległość powinna być mniejsza.
