### ISSUE TITLE
[Mmap] zawieszenie ciała

### ISSUE THREAD

**Issue by nirvaaa** [NoobSunwell/Sunwell-BugTracker#46]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: ciało moba zawieszone w powietrzu

**Obecne działanie**: ciało leży powyżej terenu

**Oczekiwane działanie**: leżeć na terenie

**Co należy zrobić, aby odtworzyć ten błąd**: zabić moba w pokzanym miejscu

1. https://s13.postimg.org/wfby02vpz/image.jpg - zdjęcie z kordynatami
2. 
3. Mam pytanie czy wszystkie takie przypadki wypisywać z osobna?

**Linki WoWHead/OpenWoW**:

1. 
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by NoobSunwell** [comment]
Nie trzeba wypisywać osobno.

**Comment by nirvaaa** [comment]
To znaczy wszystkie takie bugi poprawione zostaną za jedną naprawą?

**Comment by NoobSunwell** [comment]
Wszystkie, które tyczą się nie opadania ciał z powietrza po śmierci.

Powinno działać po aktualizacji.
