### ISSUE TITLE
[NPC] Grellkin ID: 1989

### ISSUE THREAD

**Issue by angelikasol** [NoobSunwell/Sunwell-BugTracker#47]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:

**Obecne działanie**: nie daje się zabić, przyjmuje obrażenia ale zaraz mu się hp wraca na full

**Oczekiwane działanie**: powinien dać się zabić

**Co należy zrobić, aby odtworzyć ten błąd**:

1. próbować uderzyć moba jakimhttps://zapodaj.net/7622324014391.jpg.htmlkolwiek skilem
2. 
3. 

**Linki WoWHead/OpenWoW**:

1. http://wotlk.openwow.com/npc=1989
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
https://zapodaj.net/7622324014391.jpg.html

**Comment by NoobSunwell** [comment]
https://github.com/NoobSunwell/Sunwell-BugTracker/issues/19
