### ISSUE TITLE
[Quest] Basic Chemistry.

### ISSUE THREAD

**Issue by Kougraa** [NoobSunwell/Sunwell-BugTracker#476]
**Opis**: [Quest dla 5 osób] Quest "Basic chemistry" polega na dolaniu do kotła płynu mózgowo rdzeniowego.

**Obecne działanie**: Otóż po dodaniu płynu do kotła gracz musi uporać się z mobami, które z niego wychodzą. Dostaje kolejno informacje, że kocioł zaczyna wrzeć i coś wyłania się z kotła - jest to Plague Drenched Ghoul. Natępnie pojawia się informacja, że kocioł nadal się gotuje. [Do tego momentu wszystko jest tak jak powinno]. Wyłaniają się 2 moby - Rampaging Ghoul'e, po czym dostajemy informacje, że 'Plaga staje się niestabilna?'. Tak czy siak, nie można wykonać questa, gdyż w którymś momencie gracz nie dostaje informacji dotyczących sytuacji w kotle i wskazówek, aby wykonać quest. Po użyciu kolejny raz płynu - sytuacja się powtarza - gracz zabija 3 moby, po czym nic sie konkretnego nie dzieje. 
https://youtu.be/daDK1azzqdY

Pozwoliłam sobie nagrać jeszcze film, używając płynu po cd. Nic niestety nie dało. Za każdym razem po pojawieniu się Rampaging Ghouli quest jest przerywany. 
Quest jest niewykonalny.
https://youtu.be/XihUO1QbbMU

**Oczekiwane działanie**: Tak wiec całość wygląda tak:
https://youtu.be/HvO7ZRdkyhA
https://youtu.be/aefkQfpxQ4c
[Moby się różnią, ale nie wiem czy to ma jakieś konkretne znaczenie].
->W którymś momencie gracz powinien dostać informacje, że musi użyć płynu ponownie. 
Po czym kontynuować quest i po raz kolejny uporać się z mobami, które wychodzą z kotła. <-

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Wziąć quest od NPC.
2. Odnaleźć kocioł.
3. Dolać płynu do kotła.

**Linki WoWHead/OpenWoW**:

1. [Quest] http://www.wowhead.com/quest=13279/basic-chemistry
2. [Quest item] http://www.wowhead.com/item=44010/pustulant-spinal-fluid
3. [NPC] http://www.wowhead.com/npc=32176/plague-drenched-ghoul
4. http://www.wowhead.com/npc=32178/rampaging-ghoul

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
http://imgur.com/u1ivAOP

-> W chwili, gdy podejmujemy próbę wykonania questa w grupie. Informacje dot. sytuacji w kotle wyświetlają się tylko jednemu graczowi. Tak jakby quest był jednoosobowy. 
Nie wiem czy zaliczyłoby całej grupie, gdyby quest działał - ale przypuszczam, że również nie.

**Comment by nexx94** [comment]
Z komentarzy na wowheadzie wynika że tego questa podczas wotlk nie dało się wykonać solo. W cata zmieniono cd itemu na 30s z 90s, filmiki są z późniejszych okresów.

**Comment by Kougraa** [comment]
Tak, widziałam. Jednak próba wykonania questa w grupie kończyła się podobnie. Próbowałam przy pomocy Soulessa, Vadrena  i Aeriala.

**Comment by Kougraa** [comment]
https://youtu.be/h7cTrhZev0k
https://youtu.be/3DhPIrgUBRc

**Comment by Kougraa** [comment]
https://youtu.be/DY-bYM0hNec
Zamykam.
