### ISSUE TITLE
[NPC] Carnivous the Breaker

### ISSUE THREAD

**Issue by Bainit123** [NoobSunwell/Sunwell-BugTracker#49]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Mob ma bardzo mały aggro range, jeżeli zaatakuje się go z dalej niż ok. 10 yardów to ignoruje gracza. Lokalizacja moba to Darkshore: 40,5:56,5

**Obecne działanie**: Mob po zaatakowaniu od razu gubi aggro. [http://imgur.com/a/Szo6I](http://imgur.com/a/Szo6I) 

**Oczekiwane działanie**: Mob powinien biec normalnie do gracza po zaatakowaniu, niezależnie z jak daleka.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Podejść do moba na ok 15 yardów
2. Zaatakować go
3. Zdaje się że zależnie od której strony podejdzie się do moba ten range jest inny

**Linki WoWHead/OpenWoW**:

1. 
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by NoobSunwell** [comment]
Brak ID Wowhead/openwow.

**Comment by Bainit123** [comment]
[http://www.wowhead.com/npc=2186/carnivous-the-breaker](url)
ID 2186 (chyba)

**Comment by NoobSunwell** [comment]
https://github.com/NoobSunwell/Sunwell-BugTracker/issues/19
