### ISSUE TITLE
Target not in line sight: (Brambleblade Ravine w Mulgore)

### ISSUE THREAD

**Issue by Xanador** [NoobSunwell/Sunwell-BugTracker#5]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:Czasami cele, które powinniśmy swobodnie móc zaatakować, są ( jak to gra określa ) " target not in line sight ".

**Obecne działanie**:
Gdy stoję naprzeciw moba, powinienem móc castować w niego. Niestety w tym przypadku nie moglem, mimo, że nic między nami nie stało.

**Oczekiwane działanie**: 
Powinienem móc go normalnie zaatakować z zaklęć zasięgowych, gdyż nic nie stoi na przeszkodzie.

**Co należy zrobić, aby odtworzyć ten błąd**:
Niestety nie miałem addonów z cordami, tak bym podał dokładną lokację.
To jest trochę trudne, ale jeśli chodzi o tamtą lokacje to: Brambleblade Ravine w Mulgore:

1. Trzeba poczekać aż mob wejdzie na skałkę przy pochodni.
2. Spróbować go zaatakować z jakiejkolwiek broni/zaklęcia dalekosiężnego.
Koniec.

PS: SS:         http://imgur.com/a/HbIOt

**Comment by NoobSunwell** [comment]
Prosiłbym o ID moba z wowhead/openwow.

**Comment by Xanador** [comment]
NPC: http://wotlk.openwow.com/npc=2952
SPELL: http://wotlk.openwow.com/spell=403

**Comment by NoobSunwell** [comment]
Problem powinien być naprawiony po aktualizacji.
