### ISSUE TITLE
[STRONA] Panel użytkownika

### ISSUE THREAD

**Issue by TomkiPL** [NoobSunwell/Sunwell-BugTracker#50]
**Opis**: Błąd w dacie. Przy ostatnim logowaniu.

**Obecne działanie**: http://i.imgur.com/9vaTlqE.jpg

**Oczekiwane działanie**: Zmiana w dacie.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. 
2. 
3. 

**Linki WoWHead/OpenWoW**:

1. 
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by vadren** [comment]
Zapewne po oficjalnym starcie zadziała przy pierwszym logowaniu.

**Comment by NoobSunwell** [comment]
Strona nie jest jeszcze połączona z serwerem gry.
