### ISSUE TITLE
TALENT [Sniper Training]

### ISSUE THREAD

**Issue by Lilianka88** [NoobSunwell/Sunwell-BugTracker#508]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:  [Sniper Training]- talent w drzewku survival, zwiększający szanse na crita z Kill Shota, oraz w przypadku, gdy Kill Shot nie uśmiercił naszego oponenta, buffuje się nam dmg ze Steady Shota, Aimed Shota, Black Arrow i Explosive Shot o 6%

**Obecne działanie**: Buff z [Sniper Training] jest aktywny na nas cały czas, nieważne, czy jesteśmy w combacie i faktycznie nasz Kill Shot nie był śmiertelnym ciosem, czy tez biegamy sobie beztrosko po dalaranie nie wchodząc z kimkolwiek w jakiekolwiek potyczki PvP. Mało tego, ten buff w ogóle z nas nie schodzi, gdy czas jego trwania się kończy, on się automatycznie odświeża. 

**Oczekiwane działanie**: Buff [Sniper Training] (tj. zwiekszony dmg ze Steady Shota, Aimed Shota, Black Arrow i Explosive Shot) powinien odpalać się tylko w sytuacji, gdy po użyciu Kill Shota nasz przeciwnik nadal dziarsko biega po polu bitwy.
http://i.imgur.com/iUh1MWM.jpg - widać dokładny opis oczekiwanego działania talentu, oraz jego aktywność na mojej postaci w przypadku, gdy nawet nie jestem "w walce".
http://i.imgur.com/saDuPUZ.jpg - po najechaniu kursorem myszki na buffek można zobaczyć, że zwiększa on nam dmg z ww. skili, czyli coś, co powinno być aktywowane dopiero w przypadku wystrzelenia Kill Shota w target i nie uśmiercenia go.
Krótko mówiąc, tak zbugowany talent daje wielką przewagę hunterom survi, ponieważ ich bazowy dmg z Steady Shota, Aimed Shota, Black Arrow i Explosive Shot jest bezustannie zwiększany o 6%.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Zrobić huntera.
2. Dobic poziom odpowiedni do rozdania punktów talentu w drzewku survival w [Sniper Training]
3. Obserwować nasze bufki.

**Linki WoWHead/OpenWoW**:

1. http://wow.gamepedia.com/Mastery:_Sniper_Training - interesuje nas kwestia z patcha 3.1.0
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
jw.

**Comment by valcy** [comment]
uwaga tlumacz;
while standing still = gdy stoisz w miejscu
kill shot w tym talencie dostaje tylko crita, nie wplywa na odpalanie buffa

**Comment by Kougraa** [comment]
Również uważam, że tak powinno być.

**Comment by Lilianka88** [comment]
@valcy Ty tak naprawde to tlumaczysz? Nie mam wiecej pytan...

**Comment by valcy** [comment]
zamknijcie to serio xD
bo.sie odpale XDDD

**Comment by Lilianka88** [comment]
chcesz mi wmowic, ze hutner survi ma bezustannie zwiekszony dmg z Aimeda, Steady, Explosive i Black Arrow? Nice try

**Comment by valcy** [comment]
tak  to dziala od kiedy powstal ten talent

**Comment by Lilianka88** [comment]
Wiesz, idac Twoim tokiem myslenia, buff powinien sie dezaktywowac w momencie gdy biegam (przeciez nie stoje wtedy w miejscu), wlasnie sie zalogowalam, biegam i dalej mam go na sobie! Niemozliwe! BTW. Na globie dzialal inaczej, gralam na oficjalnym serwie podczas trwania WOTLK i pamietam, nawet popytalam sie znajomych z globa i 2 potwierdzilo moja teze, reszta nie pamieta...

**Comment by Lilianka88** [comment]
Wroci Noob i sam rozstrzygnie, ma wieksze kompetencje niz my oboje razem wzieci, ja obstaje przy swoim, bo pamietam jak to dzialalo. I tym pozytywnym akcentem koncze polemike.

**Comment by valcy** [comment]
buff odpala sie gdy przez 6s stoisz, nie znika w momencie gdy musisz sie ruszyc chyba ze jestes dobre 15s w ruchu
