### ISSUE TITLE
[NPC] Moonstalker runt blokuje ataki

### ISSUE THREAD

**Issue by turboszczur** [NoobSunwell/Sunwell-BugTracker#51]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: W/w kot zablokował spella od mojego peta.

**Obecne działanie**: Hm, kot jest koxem i blokuje spelle

**Oczekiwane działanie**: Kot nie powinien blokować

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Zaatakować tego npca 
2. Bić mało i powoli
3. Czekać na block

**Linki WoWHead/OpenWoW**:

1. http://wotlk.openwow.com/npc=2070
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
http://imgur.com/a/5IjPk

**Comment by NoobSunwell** [comment]
Niestety nie mogę znaleźć żadnych dowodów na to, że NPC konkretnego typu nie powinny blokować ataków (nie każdy NPC musi mieć tarczę aby blokować).

Bardzo bym prosił o podesłanie takiego, wtedy na pewno coś z tym zrobię.

**Comment by turboszczur** [comment]
No też trochę szukałem ale niestety nie znalazłem nic poza potwierdzeniem twych słów że npc nie potrzebują tarczy by blokować.

**Comment by NoobSunwell** [comment]
Brak dowodów - muszę zamknąć zgłoszenie.
