### ISSUE TITLE
Seal of Righteousness x2

### ISSUE THREAD

**Issue by microjp** [NoobSunwell/Sunwell-BugTracker#52]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: W spellbooku u paladyna widnieją dwa spelle o nazwie Seal of Righteousness z różnymi opisami. Jednakże opis w samym buffie nie zmienia się.

**Obecne działanie**: Nie powinny występować dwa takowe spelle

**Oczekiwane działanie**: Powinien być jeden

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Stworzyć postać w klasie Paladyn
2. 
3. 

**Linki WoWHead/OpenWoW**:

1. http://wowwiki.wikia.com/wiki/Seal_of_Righteousness_(old)
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
Screeny z gry:
http://imgur.com/a/FALZc
http://imgur.com/a/79F7l

**Comment by NoobSunwell** [comment]
Będzie naprawione po update.
