### ISSUE TITLE
<quest> Protect Kanati Greycloud

### ISSUE THREAD

**Issue by valcy** [NoobSunwell/Sunwell-BugTracker#53]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:Obrona npc przed falami centaurow.

**Obecne działanie**: NPC wychodzi 2 kroki przed siebie, krzyczy wychodza centaury ale stoja w miejscu a npc wraca i zalicza nam questa.

**Oczekiwane działanie**: Po odpaleniu questa powinnismy wraz z npc mierzyc sie z przeciwnikami ktorzy wychodza falami(po 3).

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Odpalic questa.
2. Patrzec.
3. 

**Linki WoWHead/OpenWoW**:

1. http://wotlk.openwow.com/quest=4966
2. http://wotlk.openwow.com/npc=10638
3. http://wotlk.openwow.com/npc=10720

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
http://i.imgur.com/DSY8m87.jpg

**Comment by NoobSunwell** [comment]
Będzie naprawione po update.
