### ISSUE TITLE
[Map/NPC] Rockjaw Skullthumper

### ISSUE THREAD

**Issue by ShatteredGlassx** [NoobSunwell/Sunwell-BugTracker#54]
Opis: Problem z mapami/LoS'em NPC.

Obecne działanie: Bliski śmierci mob, zaczyna latać, uniemożliwia to lootowanie.
dodatkowy screen: https://zapodaj.net/1c9ada08e0831.jpg.html
Oczekiwane działanie: Możliwość zlootowania go na ziemi.

Co należy zrobić, aby odtworzyć ten błąd:

1. Stanąć niedaleko krawędzi lub/i użyć Fear'a

Linki WoWHead/OpenWoW:
http://wotlk.openwow.com/npc=1115
http://wotlk.openwow.com/npc=1117

Lokalizacja z koordynatów GPS (X, Y, Z, Map):
https://zapodaj.net/f04865b218c0d.jpg.html
-5632 , -1689 , 362 , 0

Obstawiam, że jest to problem, ogólnie w jaskiniach, jak będę w innej, to sprawdzę.

**Comment by NoobSunwell** [comment]
https://github.com/NoobSunwell/Sunwell-BugTracker/issues/46
