### ISSUE TITLE
[quest] [790] Sarkoth, mały dmg

### ISSUE THREAD

**Issue by adorovsky** [NoobSunwell/Sunwell-BugTracker#6]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Skorpion Sarkoth nie używa swoich wszystkich spelli i bije za bardzo mały dmg.

**Obecne działanie**: Każdy atak ze strony skorpiona zadaje obrażenia równe "1" (trucizna zadaje obrażenia równe "2" - nie rzuca trucizny, która ma zadawać obrażenia równe "5"). Via: http://wotlk.openwow.com/npc=3281 , takie małe obrażenia skorpion zadaje postaci na 1 lvlu.

**Oczekiwane działanie**: używanie drugiego rodzaju trucizny, większy dmg w skali 1lvl (player) v 4lvl (sarkoth) 

**Co należy zrobić, aby odtworzyć ten błąd**:

1.  Wystarczy zaatakować moba i obserwować ilość otrzymywanych obrażeń
2. 
3.

**Comment by NoobSunwell** [comment]
Będzie poprawione po restarcie.
