### ISSUE TITLE
[QUEST] Spirit of the Wind

### ISSUE THREAD

**Issue by Kokaina** [NoobSunwell/Sunwell-BugTracker#60]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Zbieramy item Blood Shardy z różnych npc (dropią poprawnie), następnie oddajemy je do questgivera, który powinien w zamian za itemy rzucić nam buffa Spirit of the Wind, jednakże tak się nie dzieje

**Obecne działanie**: W momencie kiedy oddajemy itemy Blood Shard (10x) nie dostajemy buffa Spirit of the Wind od NPC

**Oczekiwane działanie**: Po zwróceniu itemu Blood Shard (10x) powinniśmy dostać buffa Spirit of the Wind

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Zebrać 10x Blood Shardy
2. Zwrócić je do questgivera
3. Zorientować się, że nie otrzymało się buffa :P

**Linki WoWHead/OpenWoW**:

1. Questgiver ID: 3430 (http://wotlk.openwow.com/npc=3430)
2. Quest ID: 889 (http://wotlk.openwow.com/quest=889)
3. Blood Shard ID: 5075 (http://wotlk.openwow.com/item=5075)
4. Spirit of the Wind buff ID: 16618 (http://wolk.openwow.com/spell=16618)

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
https://s9.postimg.org/gp0xjmjn3/Q_barrensy.jpg

**Comment by NoobSunwell** [comment]
Będzie naprawione po update.
