### ISSUE TITLE
[QUEST] Agamaggan's Strength

### ISSUE THREAD

**Issue by Kokaina** [NoobSunwell/Sunwell-BugTracker#61]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Zbieramy item Blood Shardy z różnych npc (dropią poprawnie), następnie oddajemy je do questgivera, który powinien w zamian za itemy rzucić nam buffa Agamaggan's Strength, jednakże tak się nie dzieje

**Obecne działanie**: W momencie kiedy oddajemy itemy Blood Shard (4x) nie dostajemy buffa Agamaggan's Strength od NPC

**Oczekiwane działanie**: Po zwróceniu itemu Blood Shard (4x) powinniśmy dostać buffa Agamaggan's Strength

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Zebrać 4x Blood Shardy
2. Zwrócić je do questgivera
3. Zorientować się, że nie otrzymało się buffa :P

**Linki WoWHead/OpenWoW**:

1. Questgiver ID: 3430 (http://wotlk.openwow.com/npc=3430)
2. Quest ID: 5042 (http://wotlk.openwow.com/quest=5042)
3. Blood Shard ID: 5075 (http://wotlk.openwow.com/item=5075)
4. Agamaggan's Strength buff ID: 16612 (http://wotlk.openwow.com/spell=16612)

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
https://s9.postimg.org/gp0xjmjn3/Q_barrensy.jpg

**Comment by NoobSunwell** [comment]
Będzie naprawione po update.
