### ISSUE TITLE
[Tekstury] Moby włażą pod tekstury i tam umierają

### ISSUE THREAD

**Issue by adorovsky** [NoobSunwell/Sunwell-BugTracker#64]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Włażące moby pod tekstury

**Obecne działanie**:  W trakcie walki, niektóre moby pod koniec swojego hp uciekają po kolegów, po czym wracają, we wskazanym na screenie miejscu moby wpadają pod schody gdy następuje ich powrót do walki.

**Oczekiwane działanie**: Nie powinny włazić pod tekstury schodów

**Co należy zrobić, aby odtworzyć ten błąd**:

1.  Bić się z mobkami we wskazanym miejscu stojąc na schodach i czekać na ich powrót po ucieczce przy ciężkich obrażeniach.
2. 
3. 

**Linki WoWHead/OpenWoW**:

1. 
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**: http://i63.tinypic.com/el8tie.png

**Comment by vadren** [comment]
Mmapy, a te maja byc poprawione.

**Comment by NoobSunwell** [comment]
https://github.com/NoobSunwell/Sunwell-BugTracker/issues/19
