### ISSUE TITLE
[Object] Mitrhill Deposit

### ISSUE THREAD

**Issue by adorovsky** [NoobSunwell/Sunwell-BugTracker#66]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Mitrhill Ore w nieodpowiedniej lokalizacji

**Obecne działanie**: W Durotarze - na wskazanym przez screen miejscu, pojawiają się skałki mitrhillu.

**Oczekiwane działanie**: Z całą pewnością nie powinno tych skał tam być.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Podejść we wskazane miejsce
2. 
3. 

**Linki WoWHead/OpenWoW**:

1. 
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**: http://i63.tinypic.com/2h49vz4.png

**Comment by Kokaina** [comment]
Ta skałka była tam od zawsze na sunwellu, zostawmy ją jako pomnik xP ale potwierdzam, że nie powinno jej tam być - odwieczne utrapienie tc2

**Comment by NoobSunwell** [comment]
Będzie poprawione po update.
