### ISSUE TITLE
NPC: Sagorne Creststrider  <Shaman Trainer>

### ISSUE THREAD

**Issue by Xanador** [NoobSunwell/Sunwell-BugTracker#67]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: 
NPC posiada niewidzialną opcję nauki zaklęć. ( SS 2 )

**Obecne działanie**: 
NPC posiada niewidzialną opcję nauki zaklęć. ( SS nr. 2) Brakuje mu opcji "Teach me the ways of the spirits ".( SS 1 )

**Oczekiwane działanie**:
Trener powinien mieć wszystkie trzy opcje do pogadania. SS( 1 )

**Co należy zrobić, aby odtworzyć ten błąd**:
1. Zagadać do trenera. ( http://wotlk.openwow.com/npc=13417 )
2. Spróbować nauczyć się u niego zaklęć ( SS-2 )
3. Niby można, ale jest opcja niewidoczna ( SS-3 )

**Linki WoWHead/OpenWoW**:

1. http://wotlk.openwow.com/npc=13417   Trener.
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
NIE POTRZEBNE.

**Comment by Xanador** [comment]
http://imgur.com/a/RJ8Ms 
Zapomniałem SS dać::::

**Comment by NoobSunwell** [comment]
Będzie naprawione po update.
