### ISSUE TITLE
[NPC] Wrathtail wave rider

### ISSUE THREAD

**Issue by turboszczur** [NoobSunwell/Sunwell-BugTracker#68]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Npc bije się w powietrzu w tym miejscu

**Obecne działanie**: Jaszczur nie wie co to grawitacja, kilka razy z nim pochodziłem dookoła i parę razy szwendał się w powietrzu

**Oczekiwane działanie**: Powinien chodzić po glebie.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Udać się na miejsce wskazane w kordach
2. Zaatakować go
3. Pochodzić dookoła z nim między wzniesieniami

**Linki WoWHead/OpenWoW**:

1. http://wotlk.openwow.com/npc=3713
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

http://imgur.com/a/8tup6

**Comment by turboszczur** [comment]
Pet huntera w tym miejscu też lubi podniebne spacery.

**Comment by NoobSunwell** [comment]
Powiązane z https://github.com/NoobSunwell/Sunwell-BugTracker/issues/19
