### ISSUE TITLE
[NPC] Pridewing consort

### ISSUE THREAD

**Issue by turboszczur** [NoobSunwell/Sunwell-BugTracker#69]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Uwiły se gniazdko na górze i nie chcą z niego zejść a my nie możemy tam wejsć, nawet pet.

**Obecne działanie**: Mobki są nieosiągalne, można do nich strzelać ale one nie umieją zejść a my nie mamy jak tam wejść.

**Oczekiwane działanie**: Myślę że powinny przynajmniej zleźć na dół

**Co należy zrobić, aby odtworzyć ten błąd**: 

1. Pójść tam i zaatakować moby ze screena.
2. 
3. 

**Linki WoWHead/OpenWoW**:

1. http://wotlk.openwow.com/npc=4014
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

http://imgur.com/a/vmBpn

**Comment by NoobSunwell** [comment]
Powiązane z https://github.com/NoobSunwell/Sunwell-BugTracker/issues/19
