### ISSUE TITLE
[Quest] Mage Summoner

### ISSUE THREAD

**Issue by turboszczur** [NoobSunwell/Sunwell-BugTracker#70]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Podwładni tego kolesia mają problemy z niesubordynacją a on sam zapomniał spella się nauczyć.

**Obecne działanie**: Sarilus Foulborne nie przywoluje elementali a powinien. Gdy straci nas z oczu (zginiemy albo wejdziemy w stealth) to wszystkie npce o nazwie Burning Blade Acolyte rzucają się na niego i rozpoczynają się igrzyska śmierci.

**Oczekiwane działanie**: Sarilus Foulborne powinien przyzywać elementale poprzez spella "Sarilus's Elementals". Jego addy nie powinny się buntować i go zabijać (albo on ich). Nie jestem pewien co do frostbolta czy Sarilus używa (a powinien).

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Wziąść questa z ashenvale (możliwe że jest to opcjonalne)
2. Udać się na dreadmist peak podany w koordynatach
3. Zaatakować Sarilusa a potem zniknąć albo zginąć

**Linki WoWHead/OpenWoW**:

1. http://wotlk.openwow.com/quest=1017 QUEST
2. http://wotlk.openwow.com/npc=3986 Sarilus Foulborne
3. http://wotlk.openwow.com/npc=3380 Burning blade acolyte
4. http://wotlk.openwow.com/spell=6490 Sarilus's Elementals

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

http://imgur.com/a/vmBpn

**Comment by NoobSunwell** [comment]
Będzie naprawione po update.
