### ISSUE TITLE
[Dungeon] Deadmines, door

### ISSUE THREAD

**Issue by ShatteredGlassx** [NoobSunwell/Sunwell-BugTracker#71]
Opis: Brak możliwości otworzenia drzwi, jeżeli raz zostaną zamknięte.

Obecne działanie: Po zabiciu pierwszego bossa w Deadmines, drzwi za nim się otwierają, jednak po ich  ręcznym zamknięciu nie jesteśmy w stanie ich ponownie otworzyć za pomocą dźwigni.

Oczekiwane działanie: Możliwość otworzenia drzwi za pomocą dźwigni.

Co należy zrobić, aby odtworzyć ten błąd: 

1. Zabij pierwszego bossa w Deadmines
2. Przejść przez drzwi
3. Zamknąć je
4. Użyć dźwigni, która znajduje się obok nich
Rezultat? Nic się nie dzieje.

Linki WoWHead/OpenWoW:
Pierwszy boss w Deadmines: http://wotlk.openwow.com/npc=644
Drzwi są zaraz za nim.

Lokalizacja z koordynatów GPS (X, Y, Z, Map):
X: -191
Y: -458
Z: 54
Map: 36

**Comment by NoobSunwell** [comment]
A czy to nie jest tak, że z tymi drzwiami nie powinno się dać po prostu ręcznie wdać w interakcję?

**Comment by NoobSunwell** [comment]
Będzie naprawione po update.
