### ISSUE TITLE
[Quest] Trial of the Sea Lion (Part 3 of 4) (horde)

### ISSUE THREAD

**Issue by onlajn** [NoobSunwell/Sunwell-BugTracker#72]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:  Quest druida. Brak skrzynki "Strange Lockbox", co za tym idzie, niemożność zdobycia Half Pendant of Aquatic Endurance.

**Obecne działanie**: Quest polega na zdobyciu dwu części: Half Pendant of Aquatic Agility oraz Half Pendant of Aquatic Endurance w celu złączenia ich w Pendant of the Sea Lion. Half Pendant of Aquatic Agility można zdobyć w Barrens (działa poprawnie), jednak nie można zdobyć Half Pendant of Aquatic Endurance w Silverpine Forest (w odpowiednim miejscu nie ma po prostu skrzyni). Miejsce przedstawiające brak skrzyni widoczne jest na screenie z gpsem.

**Oczekiwane działanie**: Dwa filmy z 2008 (więc WotLK), przedstawiające poprawne działanie:
https://www.youtube.com/watch?v=Kw8tzeN0I2I (od 1.22)
https://www.youtube.com/watch?v=VW6Rm7XVLEM (od 2.51)

Jak widać na filmach, w miejscu ~(30.0;29.0) powinna być skrzynia, której teraz brakuje. W skrzyni powinien znajdować się Half Pendant of Aquatic Endurance.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Należy udać się do Silverpine, dojść na plażę, znaleźć wrak statku i od wraku popłynąć na zachód.
2. Później należy zanurkować ~(30.0;29.0), znaleźć takie dwa podwodne pagórki, przypominające trochę wypięte pośladki (miejsce widoczne na screenie).
3. Wówczas widzimy, że skrzyni rzeczywiście nie ma.

**Linki WoWHead/OpenWoW**:

1. http://wotlk.openwow.com/quest=30 (sam quest)
2. http://wotlk.openwow.com/object=177844 (Strange Lockbox, którego właśnie brakuje)
3. http://wotlk.openwow.com/item=15882 (Half Pendant of Aquatic Endurance, który powinien być w powyższej skrzyni)

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
http://imgur.com/3CDqZD4

**Comment by NoobSunwell** [comment]
Będzie naprawione po update.
