### ISSUE TITLE
[70] [H] Let them eat crows - plaguehound

### ISSUE THREAD

**Issue by Rzuuf** [NoobSunwell/Sunwell-BugTracker#73]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:

**Obecne działanie**: quest (id: 11227) mozna wykonac, jednak pet ktorego przywolujemy nie dziala tak, jak powinien - stoi w miejscu i nic nie robi, nie chodzi za nami itd

**Oczekiwane działanie**: pet przywolany z klatki (id: 33221) powinien dzialac jak normalny pet, powinien za nami chodzic oraz atakowac naszych przeciwnikow. Do tego, jesli mamy swojego peta aktywnego to przywolanie questowego peta z klatki powinno anulowac naszego aktualnego peta

**Co należy zrobić, aby odtworzyć ten błąd**:

1. wziac quest
2. przywolac peta
3. obserwowac

**Linki WoWHead/OpenWoW**:

1. http://www.wowhead.com/quest=11227/let-them-eat-crow
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
X: 1857.880005 Y:-6183.430176 Z: 24.668100

**Comment by NoobSunwell** [comment]
Będzie naprawione po update.
