### ISSUE TITLE
Explore Westfall

### ISSUE THREAD

**Issue by Vevee** [NoobSunwell/Sunwell-BugTracker#74]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:  http://ifotos.pl/z/arwpqxa
                http://ifotos.pl/z/arwpqnn

**Obecne działanie**: Odkrywa mape, daje expa za zaliczone miejsca, nie zalicza do achievmenta.

**Oczekiwane działanie**: 
Powinno zaliaczac odkryte miejsca do achievmenta.

**Linki WoWHead/OpenWoW**:

1. http://wowwiki.wikia.com/wiki/Explore_Westfall

**Comment by NoobSunwell** [comment]
https://github.com/NoobSunwell/Sunwell-BugTracker/issues/44
