### ISSUE TITLE
[QUEST] The Escape  : ID [863]

### ISSUE THREAD

**Issue by Lamadwarf** [NoobSunwell/Sunwell-BugTracker#75]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Po combacie z mobami, NPC znika.

**Obecne działanie**: Po combacie z mobami obok Quest NPC wraca na miejsce gdzie zaczyna się quest. Po chwili znika. Po jakimś czasie NPC się respi ale trzeba zrobić abandon quest i zacząć od nowa.
Inny gracz powiedział mi że quest mu zadziałał bez problemu...Stało mi się tak dwa razy pod rząd. 

**Oczekiwane działanie**: NPC powinien trzymać się scieżki , po combacie wrócić do pierwotnego miejsca i kontynuować dalej.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Zaakceptować quest, pullnąć moby wokół.
2. Po combacie czekać chwile.
3. 

**Linki WoWHead/OpenWoW**:

1.   http://www.wowhead.com/quest=863/the-escape
2.  http://www.wowhead.com/npc=3439/wizzlecranks-shredder
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
  Koordynaty: 1112 . 3101 . 82

**Comment by NoobSunwell** [comment]
Błędne koordynaty (nie są z komendy .gps), brak linków do NPC.

**Comment by Lamadwarf** [comment]
Koordynaty: 1112 . 3101 . 82
Link do NPC :
 http://www.wowhead.com/npc=3439/wizzlecranks-shredder

**Comment by Lamadwarf** [comment]
Z-updatowane :+1:

**Comment by NoobSunwell** [comment]
Dziwne, ale mi również działa bez problemów. Przetestowałem 2 razy, łapiąc combat w każdym możliwym miejscu. Zamykam, ale jak komuś uda się ten błąd zarejestrować na filmiku - byłoby fajnie.
