### ISSUE TITLE
Brak informacji o dropie quest itemu z mobków 4 questy

### ISSUE THREAD

**Issue by Vevee** [NoobSunwell/Sunwell-BugTracker#76]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:  Brak informacji o dropie quest itemu z mobka, dotyczy questow:

http://wotlk.openwow.com/quest=38
http://wotlk.openwow.com/quest=60
http://wotlk.openwow.com/quest=47
http://wotlk.openwow.com/quest=22

Dodatkowo w questach 
Goretusk Liver Pie oraz Westfall Stew itemy ktore dropia z mobow nie sa quest itemami (quest da sie wykonac)

**Obecne działanie**:  
http://ifotos.pl/z/arwhhwa
http://ifotos.pl/z/arwhhsp
http://ifotos.pl/z/arwhhsr
http://ifotos.pl/z/arwhhse
http://ifotos.pl/z/arwhhsw
http://ifotos.pl/z/arwhhsq
http://ifotos.pl/z/arwhhap

**Oczekiwane działanie**: Po najechaniu kursorem na target powinna pojawic sie informacja o dropie danego q itemu.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Wziasc questa najechac kursorem na moba / item

**Comment by NoobSunwell** [comment]
Brak informacji (ID + linki) o NPC i itemach do konkretnych zadań.

**Comment by Vevee** [comment]
wszystkie potrzebne informacje zawiera openwow i linki do questow openwow ktore podalem.

**Comment by NoobSunwell** [comment]
Będzie naprawione po update. Należy usunąć cache po aktualizacji.
