### ISSUE TITLE
ZONE " Unknown " Ragefire Chasm

### ISSUE THREAD

**Issue by Xanador** [NoobSunwell/Sunwell-BugTracker#77]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: 
Gdy jesteśmy w "RFC" inni nie widzą gdzie my jesteśmy.

**Obecne działanie**: 
Gdy jesteśmy w "RFC" inni nie widzą gdzie my jesteśmy. SS1

**Oczekiwane działanie**: 
Każdy gracz powinien wiedzieć gdzie się znajduję.

**Co należy zrobić, aby odtworzyć ten błąd**:
1. Wejść do RFC.
2. Spojrzeć na liste "/who"

**Linki WoWHead/OpenWoW**:
1. http://www.wowhead.com/zone=2437 RFC

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
1. http://imgur.com/a/zAYBL

**Comment by NoobSunwell** [comment]
Czy to się tyczy tej jednej instancji?

**Comment by Xanador** [comment]
Na razie miałem przyjemność bycia w RFC tylko.

**Comment by NoobSunwell** [comment]
Będzie naprawione po update.

**Comment by Xanador** [comment]
Dodatkowo, zapomniałem dodać, że odradzam się zamiast w Durotarze to w The Barrens.

**Comment by NoobSunwell** [comment]
To też już nie powinno być problemem - nie wykrywało poprawnie strefy.
