### ISSUE TITLE
[QUEST] Crocolisk hunting - wyświetlanie q itemu

### ISSUE THREAD

**Issue by nirvaaa** [NoobSunwell/Sunwell-BugTracker#78]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Zebrać mięso i skórę z krokodyli

**Obecne działanie**: Nie wyświetla 1 rodzaju farmionego q itemu.

**Oczekiwane działanie**: Powinno wyświetlać, które moby dropią q item.

**Co należy zrobić, aby odtworzyć ten błąd**: Zacząć q i farmić podane moby.

1. https://s15.postimg.org/z4r3jcedn/Wo_WScrn_Shot_101316_230151.jpg - screen z gry
2. http://wotlk.openwow.com/quest=385 - quest crocolisk hunting
3. http://wotlk.openwow.com/item=2924 - nie wyświetlany q item
4. http://wotlk.openwow.com/npc=1693 , http://wotlk.openwow.com/npc=2476 - moby dropiące w Loch Modan

**Linki WoWHead/OpenWoW**:

1. 
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by NoobSunwell** [comment]
![image](https://cloud.githubusercontent.com/assets/22621466/19367274/b9002904-919a-11e6-9858-b4597af02c3c.png)
Będzie naprawione po update. Należy usunąć cache po aktualizacji.
