### ISSUE TITLE
Quest/Npc:  Relic of the Earthen Ring/Gotura Fourwinds

### ISSUE THREAD

**Issue by Xanador** [NoobSunwell/Sunwell-BugTracker#79]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Questa nie powinno być. Został dodany w 3.3.0
Jednakże jest to małe ułatwienie dla szamanów ( expiących ).
+ Nie ma jak tego questa oddać, ponieważ niema NPC.

**Obecne działanie**: 
Po wzięciu questa ( http://wotlk.openwow.com/quest=14100 ), nie mogę go oddać do NPC (  http://wotlk.openwow.com/npc=35068 ), ponieważ nie ma tego NPC w tym miejscu.

**Oczekiwane działanie**: 
Tutaj mam problem. Bo wg. Wowheada Quest powstał w 3.3.0. Tak więc nie powinno go być, prawda?
Z NPC jest podobny problem bo wg wowhead powstał w 3.2.0 

**Co należy zrobić, aby odtworzyć ten błąd**:
1. Być szamanem, wbić 30 poziom, podejść w OG do http://wotlk.openwow.com/npc=13417.
2. Akceptować quest http://wotlk.openwow.com/quest=14100 .
3. Nie można go oddać, ponieważ brakuje NPC http://wotlk.openwow.com/npc=35068

**Linki WoWHead/OpenWoW**: Opisane wyżej 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:Nie potrzebne.

**Comment by NoobSunwell** [comment]
Będzie naprawione po update (w sensie quest nie będzie dostępny do contentu 3.3.0)
