### ISSUE TITLE
Quest Lazy Peons

### ISSUE THREAD

**Issue by valcy** [NoobSunwell/Sunwell-BugTracker#8]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:Lazy Peons - dlugie oczzekiwanie na npc.

**Obecne działanie**: Peony za wolno zasypiaja albo w ogole nie spia.

**Oczekiwane działanie**: Peon powinien zasypiac szybciej.
**Co należy zrobić, aby odtworzyć ten błąd**:

1. Podejsc do peona i go uderzyc.
2. Czekac az zasnie.
3.

**Comment by NoobSunwell** [comment]
Jakiś dowód na to, co jaki czas peony powinny zasypiać?

**Comment by valcy** [comment]
postep zalicza, ale bylem 1sza osoba w lokacji do tego sam a peony wszystkie bez wyjatku staly, dopiero po dobrych 10-15min kilka zlapalem

**Comment by NoobSunwell** [comment]
Bardziej mi chodzi o dowód (timer z serwerów oficjalnych blizza w postaci video), gdzie jest pokazany czas pracy/snu Peona. Obecnie one w oznaczonych porach idą spać/pracować, w zależności od ich poprzedniego stanu.

Obecnie czas pracy/snu peona wynosi 5 min.

**Comment by valcy** [comment]
http://wowwiki.wikia.com/wiki/Quest:Lazy_Peons
tu jest wzmianka ze powinno to byc 1-2min
 They go from sleeping, to cutting wood, back to the wood pile, cutting wood, and then sleeping again. It takes a minute or two for them to cycle through their activities, so if you come across them actually working, just wait a bit for them to take a nap and then whack them.
na wowheadzie w komentarzach wspominaja tez o takim czasie

**Comment by NoobSunwell** [comment]
Po aktualizacji (nie mylić z restartem) timer zostanie zmieniony na losowy od 1 do 2 minut.
