### ISSUE TITLE
[NPC]Auto Atack + Team Fight + Area Protect + Boss Protect

### ISSUE THREAD

**Issue by Wilhelm1720** [NoobSunwell/Sunwell-BugTracker#81]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Obecnie testuję w Alliance Humanem w EF podstawy gry. Idąc do 5 lvl napotkałem się na bardzo poważny problem. A mianowicie NPC które są ustawione na DA - Defense Area (obrona terenu) tego nie robią. Pierwsze Q eksploracja jaskini i eliminacja kilku coboltów. Wchodzimy a tam nic... Nikt nas nie atakuje chodzimy zwiedzamy nic... Kolejny Q "Brotherhood of Thieves" npc z tej strefy powinny bronić jagód które chcemy zabrać  i rzecz jasna samych siebie... Lecz jak już mówiłem chodzimy zwiedzamy zaliczamy Q i zero reakcji... Podejrzewam na przykładzie tych 2 q i całej lokalizacji EF że to problem na skale globalną a nie jednego czy dwóch Q.

Dodatkowo gdy wejdziemy w walkę z takim NPC. Jego "kumple" nie reagują na naszą walkę... Mimo że powinni się na nas rzucić to tyczy się wszystkich NPC z Auto Atack, Area Deffense, Boss Protect i nie tylko. Czego ewidentnie brakuje.

**Obecne działanie**: Jak wyżej brak Auto Ataku na graczy wchodzących w rewir NPC. Który powinien być nastawiony na AA celów od 5 lvl większego od niego w dół.

**Oczekiwane działanie**: Npc z takich stref z opcją Auto Ataku w Defense Area powinny atakować graczy.

**Co należy zrobić, aby odtworzyć ten błąd**: 

1. Pójść na spawn graczy w Alliance Human wejśc do ogródka czy jaskini i samemu się przekonać.
2.  Sprawdzić inne lokalizacje tego typu w EF.
3. 

**Linki WoWHead/OpenWoW**:

1. http://wotlk.openwow.com/quest=18
2. http://wotlk.openwow.com/npc=38
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**: Nie posiadam dostepu do .gps i uważam to za zbędne w tym przypadku skoro to błąd globalny.

**Comment by NoobSunwell** [comment]
... Nie wiem kto przyjął Cię na testera bez bladego pojęcia o mechanikach panujących na wotlk w tym patchu.
