### ISSUE TITLE
[Character] Regeneracja zdrowia.

### ISSUE THREAD

**Issue by Wilhelm1720** [NoobSunwell/Sunwell-BugTracker#82]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Kolejny poważny błąd. To regeneracja zdrowia. Nie pamiętam dokładnie ale jak mnie pamięć nie myli to regeneracja zdrowia była % w skali LVL lub zależna od jakiegoś bonusu, u każdego. Ale tak czy siak zajmijmy się problemem. Wchodzimy (testuje warriorem humanem) w walkę z jakimś NPC. Pomijając fakt że o dziwo NPC nie może nas zabić... To dobijamy do 1-5% hp naszej postaci. Wykańczamy NPC, lub uciekamy mu. I w magiczny sposób w 1-5s mamy 100% hp. Bez jedzenia, bez mikstur bez talentów, na 1-5lvl postaci. Na bank jestem pewien że wbicie 5lvl bez jedzenia bez przerwy walcząc nie było nigdy tak łatwe jak teraz... Po prostu Hit And Run, strach pomyśleć jak można zabijać tak bosy... 

**Obecne działanie**:  Bardzo ale to bardzo szybka regeneracja HP poza walką wręcz natychmiastowa (nie wiem jak tam na większych LVL)

**Oczekiwane działanie**: Powinno się regenerować w skali %. Nie pamiętam ile dokładnie, ale bez jedzenia FA, Heala etc nie dało się na żadnym LVL w 5s automatycznie wyleczyć do 100%.

**Co należy zrobić, aby odtworzyć ten błąd**:

1.  Zmniejszyć ilość HP i zobaczyć jak szybko się regeneruje (testuje na LOV LVL jbc)
2. 
3. 

**Linki WoWHead/OpenWoW**: 

1. Brak,
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**: Brak, nie potrzebna. (Startowa lokalizacja Ludzi JBC, ale mysle ze to wszedzie bedzie tak samo)

**Comment by NoobSunwell** [comment]
To nie jest błąd. Wyjaśnione w innym zgłoszeniu.
