### ISSUE TITLE
[DPS = TANK with no Items] DPS lepszy niż tank I to bez itemow!... DMG zadawane przez NPC.

### ISSUE THREAD

**Issue by Wilhelm1720** [NoobSunwell/Sunwell-BugTracker#83]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Warrior ARMS bez talentów w protect początkowa klasa Human 4lvl. Mam 209pkt arrmora. Co daje 22% Armora. Bije się z NPC na tym samym LVL co ja. Link ponizej. Npc formalnie powinien zadawac od 5-6 DMG w skali HP. Rzecz jasna zalezy to od naszych talentow i itemow. Lecz NPC zadaje nam 1DMG + mija sobie nas caly szas... Żeby było śmieszniej rozebrałem się do gołej klaty i pięści... Efekt ten sam... Podejrzewam że to nie tylko ten NPC ale to problem globalny z jakimś skalowaniem tylko nie wiem czego. Testowalem to na poczatkowej lokalizacji dla ludzi 1-5 lvl efekt dla wszystkich NPC taki sam.

**Obecne działanie**: DMG otrzymywane nie jest adekwatne do tego jaki powinnismy otrzymac.

Dodatkowo nagi skoczylem z wiezy... Odebralo mi 5 HP i odzyskalem je w tym samym czasie, blad z odzyskiwaniem HP tez zglosilem. 

PS: Bez itemow zabilem piesciami bosa w EF 1lvl wiekszego ode mnie. Stracilem 15 hp odzyskalem w momencie zabicia Bosa. Jego obstawa nie reagowala... Opisalem ten problem tez w innym zgloszeniu.

**Oczekiwane działanie**: Powinno nie byc moda Terminatora i walczyc tak by korzystac z jedzenia talentow i potionow + heala.

**Co należy zrobić, aby odtworzyć ten błąd**:

1.  Miec 1-5 lvl, rozebrac sie, byc tankiem na zawsze bez heala.
2. 
3. 

**Linki WoWHead/OpenWoW**:

1. http://wotlk.openwow.com/npc=38
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

W linku chyba jest i jak juz mowie nie mam dostepu do .gps i chyba jest zbedny w tym przypadku skoro to problem globalny.

**Comment by NoobSunwell** [comment]
Jak już pisałem na forum - npc na levelu 1-5 CELOWO maja znerfiony DMG - tak to zrobił Blizzard w patchu 3.3. Dodatkowo co też już pisałem - openwow nie jest dobrym źródłem na podawanie dmg, bo ma stare dane odnośnie tego. Do levelu 15 masz też zwiększony regen hp i many +kilka innych czynników. 

PS. Każdy ma komendę gps. Ty też.
