### ISSUE TITLE
[Turbo Bust Skills]Expresowe wbijanie skili.

### ISSUE THREAD

**Issue by Wilhelm1720** [NoobSunwell/Sunwell-BugTracker#84]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Jak wiadomo co 1 lvl otrzymujemy +5 do maksymalnej wartosci do kazdego skila. Deffense, Weapons, Miss, itp, itd, etc.... Jeżeli  mnie pamięć nie myli to czasami przy dobrym Expieniu nie dało się w trakcie 1 LVL wbić tych 5 pkt w danym skilu np w broni jaką walczymy. I zawsze byliśmy o 1pkt do tyłu wraz z lvl UP. A jak wiadomo za 100% pkt w skilu jest bonus. Lecz tutaj mamy turbo bust. Zaczynamy walke z pierwszym lepszym NPC po wbiciu LVL zanim skonczymy sie z nim bic mamy full skill w danej broni i w deffense (majac na sobie tylko bron lol). 

**Obecne działanie**: Wbijanie full skila lub 2-4pkt na jednym NPC dowolnie wybranym.

**Oczekiwane działanie**:  Powinno sie ro wbijac randomowo czyli dany % szansy ze nam wpadnie +1 a nie 80-100% szansy na wszystko przy 1 hicie...

**Co należy zrobić, aby odtworzyć ten błąd**:

1.  Dokładnie to nie wiem co to powoduje, lecz pewnie znerfienie tego czy też poprawienie przelicznika.
2. 
3. 

**Linki WoWHead/OpenWoW**:

1. Brak, Nie ma linka do tego.
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**: Nie posiadam dostepu do .gps ale jest tak na lov lvl pozycja startowa ludzi, dowolny npc w EF.

**Comment by ThePuppetMaster** [comment]
W sumie tyczy się to 2-3 twoich zgłoszeń. Do 10 levela masz zwiększone niebotycznie wszystko od regenu po szybkość wbijania skilla i tak być powinno. Wszystkie te rzeczy działają prawidłowo, no może poza dmg od mobów, ale nie mam dowodu.
