### ISSUE TITLE
[Loot % Chance]Jak w temacie procentowosc lootu.

### ISSUE THREAD

**Issue by Wilhelm1720** [NoobSunwell/Sunwell-BugTracker#85]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Zauwazylem tez ze % lotu chyba bardzo szwankuje... Jak w linku do itemu i q. Mamy 40% szansy ze po zabicu NPC bedziemy miec lot QI. Formalnie na 10 zabitych npc +- powinnismy miec 3-5 itemow. A tu niespodzianka! 5-6 NPC 10 itemow 100% lot + x2 czasami. Myslalem ze to może tylko ten Q. Zobaczylem tez drugi Q (2 link na dole) tam item byl z przedmiotu (skrzyni, wiadra). Jak widac na stonie lot na niego jest 100%. Lecz problem w tym ze to dropilo x2 (zawsze). Wiec zamiast zebrac 10 wiader zebralem ich 5. Pomijajac fakt ze zaden npc mnie nie gonil itp itd... To turbo exp mozna zaliczyc.

**Obecne działanie**:  % szansy dropniecia jest zawyzony tak samo jak iloraz jego liczby.

**Oczekiwane działanie**: Powinno byc adekwatne do % szansy jego dropu i jego liczebnosci.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Byc na niskim LVL 2-5 sprobowac zrobic q z linkow ponizej w EF lokalizacja ludzi.
2. 
3. 

**Linki WoWHead/OpenWoW**:

1. http://wotlk.openwow.com/item=752
2. http://wotlk.openwow.com/item=11119#contained-in-object
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**: Brak dostepu do .gps opis i linki powyzej z lokalizacja. Mysle ze to problem globalny.

**Comment by NoobSunwell** [comment]
752 - loot w bazie jest ustawiony na 80% - 1 sztuka.
11119 - 100% 1 sztuka.
