### ISSUE TITLE
[NPC] Watch Commander Zalaphil - zbyt duży dmg

### ISSUE THREAD

**Issue by dawix2104** [NoobSunwell/Sunwell-BugTracker#87]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:
Otóż NPC zwany Watch Commander Zalaphil zadaje zbyt duży damage.

**Obecne działanie**: NPC  zadaje jakieś 32-33 dmg, 50 crit.

**Oczekiwane działanie**: Zalaphil powinien zadawać jakieś 11-12 dmg co widać na filmiku: https://youtu.be/BauCX6bQhxc?t=6m50s .

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Zaatakować NPC.

**Linki WoWHead/OpenWoW**:

Brak id z wowheada, ponieważ NPC obecnie na globie już nie istnieje.

1. http://db.vanillagaming.org/?npc=5809
2. https://wotlk.openwow.com/npc=5809

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

`http://i.imgur.com/2MKfwDp.jpg`

**Comment by NoobSunwell** [comment]
Będzie naprawione po update.
