### ISSUE TITLE
[TALENT/MOBS MECHANICS] Frostbite

### ISSUE THREAD

**Issue by ThePuppetMaster** [NoobSunwell/Sunwell-BugTracker#88]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:
Błędne zachowanie mobów po procu Frostbite. Bug niesamowicie ułatwia solowanie trudnych przeciwników, zwłaszcza przy kilku prockach pod rząd .
ID: 12497

**Obecne działanie**:
Jeżeli mob jest daleko od gracza i zostanie zamrożony przez efekt Frostbite, będzie stał w miejscu nawet gdy efekt się skończy, póki nie otrzyma dmg, lub gracz się nie przemieści. Jeżeli efekt zostanie nałożony na humanoida, który w wyniku ostatniego dmg-jącego skilla (który jednocześnie nałożył efekt) dostał feara, mob teleportuje się w inne miejsce z nałożonym zamrożeniem. Podejrzenie: zakładam, że może to być wyliczony koniec ścieżki jaką miał pokonać mob, jeżeli nie zginął podczas feara, zanim wróci do gracza, ale oczywiście, mogę się mylić i wróżę tu trochę z fusów.

**Oczekiwane działanie**:
Mob powinien od razu po zakończeniu efektu zacząć kierować się w stronę gracza, niezależnie od otrzymanego dmg lub ruchu gracza. Moby nie powinny się teleportować w wyniku otrzymania frostbite w jakichkolwiek okolicznościach.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Dać min 1 pkt w talent Frostbite w drzewku frost u maga.
2. Bić moba z ataku nakładającego chill effect do póki frostbite nie procnie.
3. Czekać na samoistne zakończenie efektu, bez dmg-owania moba i nie ruszać się, lub uderzyć tylko raz by przerwać efekt i nadal się nie ruszać. Atak musi być range.

**Linki WoWHead/OpenWoW**:

1. http://wotlk.openwow.com/spell=12497
2. Common sense.

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
Globalny

**Comment by NoobSunwell** [comment]
Stawiam, że problemem były MMapy. Po ostatnich poprawkach nie mam u siebie problemów ze zgłoszonym błędem - więc pewnie po update będzie działać jak powinno.

**Comment by ThePuppetMaster** [comment]
Proszę o ponowne otwarcie. Problem nadal występuje po updacie.

**Comment by NoobSunwell** [comment]
Problem z teleportem będzie naprawiony po update.
