### ISSUE TITLE
[Gameplay] Target not in line of sight.

### ISSUE THREAD

**Issue by kovaq** [NoobSunwell/Sunwell-BugTracker#9]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:

**Obecne działanie**: Niektore elementy swiata wywoluja niewidzialna bariere. Mozna przez nia przejsc, lecz strzaly wywoluja efekt "not in line of sight". Miejsca, w ktorych spotkalem sie z problemem. Namiot wykopaliskowy na grobach pomiedzy Brill a Garren's Haunt, Tirisfal Glades, oraz Wejscie do Agamand family's crypt, Tirisfal Glades. Pierwsze sprawdzane na thrownie rogue'a, drugie na thrownie oraz auto shoocie huntera.

**Oczekiwane działanie**: Normalna mozliwosc strzalu/rzutu.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Stac na zewnatrz wejscia, celujac w moba po drugiej stronie "bariery".
2. 
3. 

ID spotkanych mobow:
Namiot: http://www.wowhead.com/npc=1941/rot-hide-graverobber
Krypta: http://www.wowhead.com/quest=408/the-family-crypt

Notka ode mnie: Wiem ,ze byl juz temat o ty, lecz w konkretnym jednym przypadku. Tutaj chcialbym zaznaczyc, ze elementy swiata powoduja takie problemy, nie tylko pochodnia od kolegi z mulgore. Za niepotrzebny spam, przepraszam.

**Comment by NoobSunwell** [comment]
Brak screenów, nie mam jak zweryfikować w konkretnej lokalizacji.

**Comment by kovaq** [comment]
https://youtu.be/LsmDQS_Ot-c Namiot. Ewidentnie slupek nie zaslania, specjalnie shcodzilem nizej by nie bylo wymowki, ze gora namiotu zaslania. pullnal sie bez rzutu to dopiero bylem able by rzucic. Krypta niestety nie jest avaible bym sam to sprawdzil bo nie ma mobow stojacych tak jakbym tego potrzebowal, aczkolwiek schody moga tam byc traktowane jako zagiecie terenu i dlatego hitboxa sie "chowa" w dol krypty.

**Comment by NoobSunwell** [comment]
Problem na 90% leży w błędnie wygenerowanych VMapach generowanych przez SunwellCore. Jestem w trakcie przepisywania.

**Comment by kovaq** [comment]
Update:
https://youtu.be/ji_7NQJ3N7o
http://wotlk.openwow.com/npc=1892 stoi wryty w ziemie, jak na filmie.

Dorzucac kazdy kolejny napotkany problem tego typu?

**Comment by NoobSunwell** [comment]
Problem powinien być naprawiony po aktualizacji.
