### ISSUE TITLE
Inspekcja talentów

### ISSUE THREAD

**Issue by ThePuppetMaster** [NoobSunwell/Sunwell-BugTracker#90]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:
Inspektowanie talentów nie pokazuje rozdanych talentów graczy.

**Obecne działanie**:
Jak wyżej. Przetestowane w pt i poza nim, po wywaleniu cache i wtf i przed, oraz z wyłączonymi i włączonymi addonami.

**Oczekiwane działanie**:
Talenty graczy powinny być widoczne kiedy się je inspektuje.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Dać inspekcje talentów na graczu, który jest dla nas friendly.

**Linki WoWHead/OpenWoW**:

1. Brak

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
Nie dotyczy.

**Comment by NoobSunwell** [comment]
![image](https://cloud.githubusercontent.com/assets/22621466/19382275/c072576a-91ff-11e6-8c16-e59bdc24593d.png)

Sprawdź po update.
