### ISSUE TITLE
Respawn po śmierci w Ragefire Chasm.

### ISSUE THREAD

**Issue by Xanador** [NoobSunwell/Sunwell-BugTracker#91]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:
 Po śmierci w RFC, nasza postać zamiast odrodzić się w Durotarze( na końcu przejścia między Razor Hill - Orgrimmar ), robi to w Crossroad.

**Obecne działanie**:
Po śmierci w RFC nasza postać odradza się w Crossroad, zamist w Durotarze.

**Oczekiwane działanie**:
Nasz postać powinna odrodzić się w Durotarze.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Wejść do RFC.
2. Umrzeć.
3. Zobaczyć, gdzie będzie nasz spawn po śmierci.

**Linki WoWHead/OpenWoW**:
1. http://www.wowhead.com/zone=2437/ragefire-chasm

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
1. Miejsce w którym powinniśmy się odrodzić. SS1
2. Miejsce gdzie się odradzamy. SS2
http://imgur.com/a/Rq0Ie

**Comment by NoobSunwell** [comment]
https://github.com/NoobSunwell/Sunwell-BugTracker/issues/77

Tu masz odpowiedź.
