### ISSUE TITLE
QUEST- Portal - The Wrap Rifts

### ISSUE THREAD

**Issue by microjp** [NoobSunwell/Sunwell-BugTracker#92]
QUEST ITEM
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:Dostajemy od npc questa o nazwie The Wrap Rifts, w którym za zadanie mamy przywołanie portalu we wskazanym miejscu za pomocą quest itemu "Unstable Warp Rift Generator", portal zostaje przywołany, zabijamy moby, zbieramy 3/3 quest itemy Warp Nether, wracamy oddać questa.

**Obecne działanie**: Problem tkwi w tym że ów portal nie znika po zakończeniu questa i cały czas spawnuje dwa moby o nazwie Unstable Voidwalker w liczbie 2

**Oczekiwane działanie**: Po zebraniu 3 quest itemów portal powinien zniknąć

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Przywołać portal quest itemem.
2. zabić 3 kolejne moby do zebrania 3 quest itemów.
3. patrzeć jak portal nie znika, również po oddaniu questa do npc

**Linki WoWHead/OpenWoW**:

1. http://www.wowhead.com/npc=20145/unstable-voidwalker - Mob
2. http://www.wowhead.com/item=29051/warp-nether - Zbierany quest item
3. http://www.wowhead.com/quest=10278/the-warp-rifts - Quest
4. http://www.wowhead.com/item=29027/unstable-warp-rift-generator - Quest item przywołujący portal

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
http://imgur.com/a/c8ngZ

**Comment by NoobSunwell** [comment]
Będzie naprawione po update.
