### ISSUE TITLE
QUEST: Blueleaf Tubers 

### ISSUE THREAD

**Issue by Xanador** [NoobSunwell/Sunwell-BugTracker#93]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Po wzięciu questa udajemy się we wskazane miejsce. Jednak tam nie możemy zrobić użyć quest itemu.

**Obecne działanie**: 
Po wejściu do RFK ( http://www.wowhead.com/zone=491/razorfen-kraul ) i po udaniu się w odpowiednie miejsce na mapie( SS 1 ) nie możemy używać quest itemu.

**Oczekiwane działanie**: 
Po wejściu do RFK ( http://www.wowhead.com/zone=491/razorfen-kraul ) i po udaniu się w odpowiednie miejsce na mapie( SS 1 ) powinniśmy móc użyć: http://wotlk.openwow.com/item=5880 aby tym samym po prostu zespawnował się : http://wotlk.openwow.com/npc=4781. (Wg; https://www.youtube.com/watch?v=mD8mg1iQ9T0 jako nasz guardian).
Zaraz po pojawieniu się mały NPC powinien powiedzieć: **"Snufflenose Gopher nervously crawls from the crate."**
Wtedy powinniśmy móc użyć na pojawionym się NPC tego itemu: http://wotlk.openwow.com/item=6684.
Następnie po użyciu itemu, NPC powinien powiedzieć **"Snufflenose Gopher wiggles it's whiskers at <character name>"** i **"Snufflenose Gopher sniffs at the ground..."**i zacząć szukać miejsc spawnu: http://wotlk.openwow.com/object=300011 . 
Gdy znajdzie jakiś powinien się zatrzymać i wykopać z ziemi: http://wotlk.openwow.com/object=20920 ,
którego to my jako gracze powinniśmy móc zebrać w postaci: http://wotlk.openwow.com/item=5876 
:)

**Co należy zrobić, aby odtworzyć ten błąd**:
1. Wziąć quest: http://wotlk.openwow.com/quest=1221.
2. Udać się do RFK: http://www.wowhead.com/zone=491/razorfen-kraul
3. Udać się we wskazane miejsce ( SS 1 )

**Linki WoWHead/OpenWoW**:
Wszystko krok po kroku opisane wyżej, nie będę robił tego zgłoszenia dłuższego xD. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
http://imgur.com/a/PkRWO

**Comment by NoobSunwell** [comment]
Będzie naprawiony po update.

**Comment by Xanador** [comment]
Quest ma się na pewno o wiele lepiej niż wcześniej, jednakże są małe problemy z prawidłowym działaniem.

1. http://wotlk.openwow.com/npc=4781 ( mob przywoływany przez http://wotlk.openwow.com/item=5880 ) Biega jakby miał wściekliznę :D. Po prostu jakby miał .mod speed 3.

2. http://wotlk.openwow.com/item=6684 można użyć na http://wotlk.openwow.com/npc=4781 tylko raz, następne użycie nie daje żadnego efektu.( To znaczy castuje się, ale http://wotlk.openwow.com/npc=4781 nie szuka kolejnych http://wotlk.openwow.com/object=20920 )

3. http://wotlk.openwow.com/item=5880 prawidłowo przywołuje jednego http://wotlk.openwow.com/npc=4781, jednakże po ponownym użyciu nie zabiera nam poprzedniego, przez co mamy dwa http://wotlk.openwow.com/npc=4781.

**Comment by NoobSunwell** [comment]
Porusza się, jakby miał wściekliznę. - nie miałeś podczas testowania komendy .mod aktywnej?

**Comment by Xanador** [comment]
Rzeczywiście. Tu masz rację. Komenda wpłynęła na niego.

**Comment by NoobSunwell** [comment]
Zwiększyłem zasięg poszukiwań obiektu dla NPC, wyłączyłem mu też tryb agresora. Będzie poprawione po update.

**Comment by Xanador** [comment]
Sir, Mamy problem. 
http://wotlk.openwow.com/npc=4781 w ogóle się nie przywołuje, po użyciu http://wotlk.openwow.com/item=5880
