### ISSUE TITLE
QUEST - A Spirit Guide

### ISSUE THREAD

**Issue by microjp** [NoobSunwell/Sunwell-BugTracker#94]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: w queście chodzi o to by użyć quest itemu blisko ciała poległego npc "Fel Orc Corpse", po czym powinien pojawić się duch wilka który zaprowadzi nas do wioski orków z klanu "The Mag'har"

**Obecne działanie**: po użyciu quest itemu pojawia się wilk, po krótkiej chwili i kilku linijkach tekstu wypowiedzianych przez niego, z dużą szybkością ucieka w strone wioski do której powinien mnie prowadzić i po jakiś 100 yd znika. Quest widnieje jako zaliczony, lecz nie można go oddać.

**Oczekiwane działanie**: Wilk powinien nas zaprowadzić w tempie biegu do wioski, tam powinniśmy oddać quest przywódcy czyli Gorkan Bloodfist

**Co należy zrobić, aby odtworzyć ten błąd**:

1. użyć quest itemu przy zwłokach npc "Fel Orc Corpse"
2. 
3. 

**Linki WoWHead/OpenWoW**:

1. http://www.wowhead.com/quest=9410/a-spirit-guide - quest
2. http://www.wowhead.com/npc=17062/fel-orc-corpse - npc przy którym używamy quest itemu
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
http://imgur.com/a/PvDud

**Comment by NoobSunwell** [comment]
Będzie naprawione po update.
