### ISSUE TITLE
[MMAPS] Niewidzialne ściany po updacie

### ISSUE THREAD

**Issue by ThePuppetMaster** [NoobSunwell/Sunwell-BugTracker#95]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:
Po updacie nadal moby evadeuja od razu po ataku z range.
ID przykładowych mobów: 2564

**Obecne działanie**:
Niewidzialne ściany, moby evadeuja, trzeba podejść blisko, żeby załapały.

**Oczekiwane działanie**:
Nie powinny evadeować, tylko biec do gracza.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Uderzyć z max range któregoś z przykładowych mobów (patrz gps)

**Linki WoWHead/OpenWoW**:

1. http://www.wowhead.com/npc=2564/boulderfist-enforcer

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
1. https://s18.postimg.org/dtdscgmll/image.png
2. https://s15.postimg.org/6e76jh6sr/image.png

**Comment by NoobSunwell** [comment]
Idzie kolejny update na MMapy - w tej lokalizacji udało mi się naprawić z tego co zauważyłem, może i w innych będzie lepiej.
