### ISSUE TITLE
[VISUAL] [QUEST] Spellfire Robes

### ISSUE THREAD

**Issue by ThePuppetMaster** [NoobSunwell/Sunwell-BugTracker#96]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:
Quest jest followupem Gathering Materials (horde), po oddaniu poprzednika, NPCowi pojawia sie nad glowa znak zapytania i możemy odebrać item (liczone jako osobny quest, dobrze działa).
Quest ID: 1962

**Obecne działanie**:
Po ukończeniu Spellfire Robes nie znika znak zapytania.

**Oczekiwane działanie**:
Powinien znikać.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Ukończyć Spellfire Robes.

**Linki WoWHead/OpenWoW**:

1. http://www.wowhead.com/quest=1962/spellfire-robes

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
Nie dotyczy.

**Comment by NoobSunwell** [comment]
Będzie naprawione po update.
