### ISSUE TITLE
DUCH - przepaść i tp na cmentarz.

### ISSUE THREAD

**Issue by Kougraa** [NoobSunwell/Sunwell-BugTracker#97]
**Opis:** W chwili gdy spadniemy w przepaść będąc w formie ducha, nie przenosi nas na cmantarz.

**Obecne działanie:** - I I -

**Oczekiwane działanie:** Po spadnięciu w przepaść powinno nas przenieść na cmentarz.
[Unstuck nie pomaga]
**Co należy zrobić, aby odtworzyć ten błąd:** -

**1.** http://i.imgur.com/iDeQe0f.jpg
**2.** http://i.imgur.com/rY7uu9v.jpg
**3**. -

**Linki WoWHead/OpenWoW:**-

**1.** -
**2.** -
**3.** -

**Lokalizacja z koordynatów GPS (X, Y, Z, Map):** -

**Comment by NoobSunwell** [comment]
Będzie naprawione po update.
