### ISSUE TITLE
[QUEST-Mage]Investigate the Blue Recluse - dalej

### ISSUE THREAD

**Issue by nirvaaa** [NoobSunwell/Sunwell-BugTracker#98]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: http://wotlk.openwow.com/quest=1920

**Obecne działanie**: 
1. http://wotlk.openwow.com/item=7308#contained-in-object ten item ma za duży zasięg - prawdopodobnie wykrywa wszystkie mobki zamiast mniej więcej całą piwnicę.
2. po użyciu Cantation of Manifestation wszystkie 6-7 mobkow atakuje gracza.
3. http://wotlk.openwow.com/item=7247 ten item sam się używa, gdy powinien to robić gracz.

**Oczekiwane działanie**: 

**Co należy zrobić, aby odtworzyć ten błąd**: zacząć q
screen: https://s21.postimg.org/o6v7wg59z/Wo_WScrn_Shot_101416_204514.jpg
id q: 1920

**Comment by NoobSunwell** [comment]
"po użyciu Cantation of Manifestation wszystkie 6-7 mobkow atakuje gracza." - jak tam jest ich tylko 4 :D

**Comment by NoobSunwell** [comment]
Co do zasięgu ściągania - jest ok - 10 yardów. Wystarczy użyć przy wejściu do pomieszczenia. 

Już sprawdzam problem z itemem.

**Comment by NoobSunwell** [comment]
Będzie naprawione po update.
