### ISSUE TITLE
[QUEST] Branch of Cenarius

### ISSUE THREAD

**Issue by turboszczur** [NoobSunwell/Sunwell-BugTracker#99]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Quest item dropnał mi z mobka Prince Raze.

**Obecne działanie**: Dropi z nie tego moba co trzeba.

**Oczekiwane działanie**: Powinien dropić tylko z Geltharis.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Wziąść questa.
2. Zabić Prince Raze.
3. Nie wiem ile ma dropa a ciężko to powtórzyć bo zabiłem go fartem na moim lvlu.

**Linki WoWHead/OpenWoW**:

1. http://wotlk.openwow.com/item=5461
2. http://wotlk.openwow.com/quest=1031
3. http://wotlk.openwow.com/npc=4619

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

http://imgur.com/a/NjupH

**Comment by NoobSunwell** [comment]
Będzie naprawione po update.
